if(NOT FFMPEG_NATIVE_OBJECT_LIST)
    message(FATAL_ERROR "FFMPEG_NATIVE_OBJECT_LIST is required")
endif()
if(NOT EXISTS "${FFMPEG_NATIVE_OBJECT_LIST}")
    message(FATAL_ERROR "Object list does not exist: ${FFMPEG_NATIVE_OBJECT_LIST}")
endif()

get_filename_component(_ffmpeg_object_dir "${FFMPEG_NATIVE_OBJECT_LIST}" DIRECTORY)
file(STRINGS "${FFMPEG_NATIVE_OBJECT_LIST}" _ffmpeg_objects)

foreach(_ffmpeg_object IN LISTS _ffmpeg_objects)
    if(EXISTS "${_ffmpeg_object}")
        continue()
    endif()
    if(NOT _ffmpeg_object MATCHES "\\.asm\\.obj$")
        continue()
    endif()

    get_filename_component(_ffmpeg_object_name "${_ffmpeg_object}" NAME)
    string(REGEX REPLACE "\\.asm\\.obj$" ".obj" _ffmpeg_flat_object_name "${_ffmpeg_object_name}")
    set(_ffmpeg_flat_object "${_ffmpeg_object_dir}/${_ffmpeg_flat_object_name}")
    if(NOT EXISTS "${_ffmpeg_flat_object}")
        continue()
    endif()

    get_filename_component(_ffmpeg_expected_dir "${_ffmpeg_object}" DIRECTORY)
    file(MAKE_DIRECTORY "${_ffmpeg_expected_dir}")
    file(COPY_FILE "${_ffmpeg_flat_object}" "${_ffmpeg_object}" ONLY_IF_DIFFERENT)
endforeach()
