include_guard(GLOBAL)

function(_ffmpeg_native_make_condition_enabled _out _condition)
    string(STRIP "${_condition}" _ffmpeg_condition)
    set(_ffmpeg_negated FALSE)
    if(_ffmpeg_condition MATCHES "^!([A-Za-z0-9_]+)$")
        set(_ffmpeg_negated TRUE)
        set(_ffmpeg_condition "${CMAKE_MATCH_1}")
    endif()

    list(FIND FFMPEG_NATIVE_ENABLED_OBJECT_MACROS "${_ffmpeg_condition}" _ffmpeg_condition_index)
    if(_ffmpeg_condition_index EQUAL -1)
        set(_ffmpeg_enabled FALSE)
    else()
        set(_ffmpeg_enabled TRUE)
    endif()

    if(_ffmpeg_negated)
        if(_ffmpeg_enabled)
            set(_ffmpeg_enabled FALSE)
        else()
            set(_ffmpeg_enabled TRUE)
        endif()
    endif()

    set(${_out} "${_ffmpeg_enabled}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_expand_make_conditionals _out _text)
    set(_ffmpeg_text "${_text}")
    foreach(_ffmpeg_unused RANGE 0 64)
        if(_ffmpeg_text MATCHES "\\$\\(if[ \t]+\\$\\((!?[A-Za-z0-9_]+)\\),[ \t]*([^\\)]*)\\)")
            set(_ffmpeg_expr "${CMAKE_MATCH_0}")
            set(_ffmpeg_condition "${CMAKE_MATCH_1}")
            set(_ffmpeg_true_value "${CMAKE_MATCH_2}")
            _ffmpeg_native_make_condition_enabled(_ffmpeg_condition_enabled "${_ffmpeg_condition}")
            if(_ffmpeg_condition_enabled)
                string(REPLACE "${_ffmpeg_expr}" "${_ffmpeg_true_value}" _ffmpeg_text "${_ffmpeg_text}")
            else()
                string(REPLACE "${_ffmpeg_expr}" "" _ffmpeg_text "${_ffmpeg_text}")
            endif()
        else()
            break()
        endif()
    endforeach()
    set(${_out} "${_ffmpeg_text}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_expand_make_variable_refs _out _makefile _text)
    set(_ffmpeg_text "${_text}")
    foreach(_ffmpeg_unused RANGE 0 32)
        if(_ffmpeg_text MATCHES "\\$\\(([A-Za-z0-9_+.-]+)-yes\\)")
            set(_ffmpeg_expr "${CMAKE_MATCH_0}")
            set(_ffmpeg_ref_variable "${CMAKE_MATCH_1}")
            set(_ffmpeg_ref_objects)
            _ffmpeg_native_append_makefile_objects(_ffmpeg_ref_objects "${_makefile}" "${_ffmpeg_ref_variable}")
            if(_ffmpeg_ref_objects)
                string(REPLACE ";" " " _ffmpeg_ref_text "${_ffmpeg_ref_objects}")
            else()
                set(_ffmpeg_ref_text)
            endif()
            string(REPLACE "${_ffmpeg_expr}" "${_ffmpeg_ref_text}" _ffmpeg_text "${_ffmpeg_text}")
        else()
            break()
        endif()
    endforeach()
    set(${_out} "${_ffmpeg_text}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_append_makefile_objects _objects_var _makefile _variable)
    file(STRINGS "${_makefile}" _ffmpeg_makefile_lines)

    set(_ffmpeg_active FALSE)
    set(_ffmpeg_include_block FALSE)
    set(_ffmpeg_rhs)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_makefile_lines)
        string(REGEX REPLACE "#.*$" "" _ffmpeg_line "${_ffmpeg_line}")
        string(REGEX REPLACE "[ \t]+$" "" _ffmpeg_line "${_ffmpeg_line}")

        if(NOT _ffmpeg_active)
            if(_ffmpeg_line MATCHES "^${_variable}[ \t]*(\\+?=)[ \t]*(.*)$")
                set(_ffmpeg_active TRUE)
                set(_ffmpeg_include_block TRUE)
                set(_ffmpeg_line "${CMAKE_MATCH_2}")
            elseif(_ffmpeg_line MATCHES "^${_variable}-\\$\\((!?[A-Za-z0-9_]+)\\)[ \t]*\\+?=[ \t]*(.*)$")
                set(_ffmpeg_active TRUE)
                set(_ffmpeg_condition "${CMAKE_MATCH_1}")
                _ffmpeg_native_make_condition_enabled(_ffmpeg_include_block "${_ffmpeg_condition}")
                set(_ffmpeg_line "${CMAKE_MATCH_2}")
            else()
                continue()
            endif()
        endif()

        set(_ffmpeg_continues FALSE)
        if(_ffmpeg_line MATCHES "\\\\$")
            set(_ffmpeg_continues TRUE)
            string(REGEX REPLACE "\\\\$" "" _ffmpeg_line "${_ffmpeg_line}")
        endif()

        if(_ffmpeg_include_block)
            string(APPEND _ffmpeg_rhs " ${_ffmpeg_line}")
        endif()

        if(_ffmpeg_continues)
            continue()
        endif()

        if(_ffmpeg_include_block)
            _ffmpeg_native_expand_make_conditionals(_ffmpeg_rhs "${_ffmpeg_rhs}")
            _ffmpeg_native_expand_make_variable_refs(_ffmpeg_rhs "${_makefile}" "${_ffmpeg_rhs}")
            string(REGEX MATCHALL "[A-Za-z0-9_./+-]+\\.o" _ffmpeg_statement_objects "${_ffmpeg_rhs}")
            list(APPEND ${_objects_var} ${_ffmpeg_statement_objects})
        endif()

        set(_ffmpeg_active FALSE)
        set(_ffmpeg_include_block FALSE)
        set(_ffmpeg_rhs)
    endforeach()

    if(_ffmpeg_active AND _ffmpeg_include_block)
        _ffmpeg_native_expand_make_conditionals(_ffmpeg_rhs "${_ffmpeg_rhs}")
        _ffmpeg_native_expand_make_variable_refs(_ffmpeg_rhs "${_makefile}" "${_ffmpeg_rhs}")
        string(REGEX MATCHALL "[A-Za-z0-9_./+-]+\\.o" _ffmpeg_statement_objects "${_ffmpeg_rhs}")
        list(APPEND ${_objects_var} ${_ffmpeg_statement_objects})
    endif()

    set(${_objects_var} "${${_objects_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_objects_to_sources _out _base_dir)
    set(_ffmpeg_sources)
    foreach(_ffmpeg_object IN LISTS ARGN)
        if(_ffmpeg_object MATCHES "\\.spv\\.o$")
            message(VERBOSE "Skipping generated SPIR-V object in native source collector: ${_ffmpeg_object}")
            continue()
        endif()

        string(REGEX REPLACE "\\.o$" "" _ffmpeg_stem "${_ffmpeg_object}")
        set(_ffmpeg_c_source "${_base_dir}/${_ffmpeg_stem}.c")
        set(_ffmpeg_asm_source "${_base_dir}/${_ffmpeg_stem}.asm")

        if(EXISTS "${_ffmpeg_c_source}")
            list(APPEND _ffmpeg_sources "${_ffmpeg_c_source}")
        elseif(FFMPEG_NATIVE_EFFECTIVE_ENABLE_ASM AND EXISTS "${_ffmpeg_asm_source}")
            set_source_files_properties("${_ffmpeg_asm_source}" PROPERTIES LANGUAGE ASM_NASM)
            list(APPEND _ffmpeg_sources "${_ffmpeg_asm_source}")
        elseif(EXISTS "${_ffmpeg_asm_source}")
            message(VERBOSE "Skipping native assembly source because FFMPEG_NATIVE_ENABLE_ASM is OFF: ${_ffmpeg_asm_source}")
        else()
            message(VERBOSE "Skipping native source without C/ASM implementation: ${_base_dir}/${_ffmpeg_stem}")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_sources)
    set(${_out} "${_ffmpeg_sources}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_enabled_arch_dirs _out)
    set(_ffmpeg_arch_dirs ${FFMPEG_NATIVE_ENABLED_ARCH_FEATURES})
    if(x86 IN_LIST FFMPEG_NATIVE_ENABLED_ARCH_FEATURES OR
       x86_32 IN_LIST FFMPEG_NATIVE_ENABLED_ARCH_FEATURES OR
       x86_64 IN_LIST FFMPEG_NATIVE_ENABLED_ARCH_FEATURES)
        list(APPEND _ffmpeg_arch_dirs x86)
    endif()
    list(REMOVE_DUPLICATES _ffmpeg_arch_dirs)
    set(${_out} "${_ffmpeg_arch_dirs}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_append_makefile_includes _makefiles_var _makefile _library)
    file(STRINGS "${_makefile}" _ffmpeg_makefile_lines)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_makefile_lines)
        string(REGEX REPLACE "#.*$" "" _ffmpeg_line "${_ffmpeg_line}")
        string(REGEX REPLACE "[ \t]+$" "" _ffmpeg_line "${_ffmpeg_line}")
        if(_ffmpeg_line MATCHES "^-?include[ \t]+\\$\\(SRC_PATH\\)/lib${_library}/([^ \t]+)$")
            set(_ffmpeg_include_rel "${CMAKE_MATCH_1}")
            set(_ffmpeg_include_rels "${_ffmpeg_include_rel}")
            if(_ffmpeg_include_rel MATCHES "\\$\\(ARCH\\)")
                set(_ffmpeg_include_rels)
                _ffmpeg_native_enabled_arch_dirs(_ffmpeg_arch_dirs)
                foreach(_ffmpeg_arch_dir IN LISTS _ffmpeg_arch_dirs)
                    string(REPLACE "$(ARCH)" "${_ffmpeg_arch_dir}" _ffmpeg_expanded_include_rel "${_ffmpeg_include_rel}")
                    list(APPEND _ffmpeg_include_rels "${_ffmpeg_expanded_include_rel}")
                endforeach()
            endif()
            foreach(_ffmpeg_include_rel IN LISTS _ffmpeg_include_rels)
                set(_ffmpeg_include "${FFMPEG_SOURCE_DIR}/lib${_library}/${_ffmpeg_include_rel}")
                if(EXISTS "${_ffmpeg_include}")
                    list(APPEND ${_makefiles_var} "${_ffmpeg_include}")
                endif()
            endforeach()
        else()
            continue()
        endif()
    endforeach()

    set(${_makefiles_var} "${${_makefiles_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_append_arch_makefiles _makefiles_var _library)
    _ffmpeg_native_enabled_arch_dirs(_ffmpeg_arch_dirs)

    foreach(_ffmpeg_arch_dir IN LISTS _ffmpeg_arch_dirs)
        set(_ffmpeg_arch_makefile "${FFMPEG_SOURCE_DIR}/lib${_library}/${_ffmpeg_arch_dir}/Makefile")
        if(EXISTS "${_ffmpeg_arch_makefile}")
            list(APPEND ${_makefiles_var} "${_ffmpeg_arch_makefile}")
        endif()
    endforeach()

    set(${_makefiles_var} "${${_makefiles_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_append_special_arch_objects _objects_var _library)
    if(NOT FFMPEG_NATIVE_EFFECTIVE_ENABLE_ASM)
        set(${_objects_var} "${${_objects_var}}" PARENT_SCOPE)
        return()
    endif()
    if(NOT _library STREQUAL "avutil")
        set(${_objects_var} "${${_objects_var}}" PARENT_SCOPE)
        return()
    endif()
    if(NOT x86 IN_LIST FFMPEG_NATIVE_ENABLED_ARCH_FEATURES)
        set(${_objects_var} "${${_objects_var}}" PARENT_SCOPE)
        return()
    endif()

    set(_ffmpeg_has_mmx_external FALSE)
    set(_ffmpeg_has_mmx_inline FALSE)
    set(_ffmpeg_has_mm_empty FALSE)
    if(mmx_external IN_LIST FFMPEG_NATIVE_ENABLED_HAVE_FEATURES)
        set(_ffmpeg_has_mmx_external TRUE)
    endif()
    if(mmx_inline IN_LIST FFMPEG_NATIVE_ENABLED_HAVE_FEATURES)
        set(_ffmpeg_has_mmx_inline TRUE)
    endif()
    if(mm_empty IN_LIST FFMPEG_NATIVE_ENABLED_HAVE_FEATURES)
        set(_ffmpeg_has_mm_empty TRUE)
    endif()

    if(_ffmpeg_has_mmx_external AND NOT _ffmpeg_has_mmx_inline AND NOT _ffmpeg_has_mm_empty)
        list(APPEND ${_objects_var} x86/emms.o)
    endif()

    set(${_objects_var} "${${_objects_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_write_x86_tx_stub _out)
    set(_ffmpeg_stub "${FFMPEG_NATIVE_GENERATED_DIR}/libavutil/x86/tx_float_stub.c")
    set(_ffmpeg_content "/* Generated by ffmpeg-cmake native backend. */\n#include \"config.h\"\n#include \"libavutil/tx_priv.h\"\n\nconst FFTXCodelet * const ff_tx_codelet_list_float_x86[] = { NULL };\n")
    _ffmpeg_native_write_file_if_changed("${_ffmpeg_stub}" "${_ffmpeg_content}")
    set(${_out} "${_ffmpeg_stub}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_write_vvc_x86_stub _out)
    set(_ffmpeg_stub "${FFMPEG_NATIVE_GENERATED_DIR}/libavcodec/x86/vvc_dsp_stub.c")
    file(MAKE_DIRECTORY "${FFMPEG_NATIVE_GENERATED_DIR}/libavcodec/x86")
    set(_ffmpeg_content "/* Generated by ffmpeg-cmake native backend. */\n#include \"config.h\"\n#include \"libavcodec/vvc/dsp.h\"\n\nvoid ff_vvc_dsp_init_x86(VVCDSPContext *hpc, const int bit_depth)\n{\n    (void)hpc;\n    (void)bit_depth;\n}\n")
    _ffmpeg_native_write_file_if_changed("${_ffmpeg_stub}" "${_ffmpeg_content}")
    set(${_out} "${_ffmpeg_stub}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_collect_makefile_objects _out _library)
    set(_ffmpeg_makefile "${FFMPEG_SOURCE_DIR}/lib${_library}/Makefile")
    set(_ffmpeg_makefiles "${_ffmpeg_makefile}")
    _ffmpeg_native_append_makefile_includes(_ffmpeg_makefiles "${_ffmpeg_makefile}" "${_library}")
    _ffmpeg_native_append_arch_makefiles(_ffmpeg_makefiles "${_library}")
    set(_ffmpeg_objects)

    foreach(_ffmpeg_current_makefile IN LISTS _ffmpeg_makefiles)
        _ffmpeg_native_append_makefile_objects(_ffmpeg_objects "${_ffmpeg_current_makefile}" OBJS)
        if(FFMPEG_NATIVE_EFFECTIVE_ENABLE_ASM)
            _ffmpeg_native_append_makefile_objects(_ffmpeg_objects "${_ffmpeg_current_makefile}" X86ASM-OBJS)
        endif()
        if(FFMPEG_BUILD_STATIC)
            _ffmpeg_native_append_makefile_objects(_ffmpeg_objects "${_ffmpeg_current_makefile}" STLIBOBJS)
        endif()
        if(FFMPEG_BUILD_SHARED)
            _ffmpeg_native_append_makefile_objects(_ffmpeg_objects "${_ffmpeg_current_makefile}" SHLIBOBJS)
        endif()
    endforeach()

    _ffmpeg_native_append_special_arch_objects(_ffmpeg_objects "${_library}")
    if(_library STREQUAL "avutil" AND FFMPEG_NATIVE_EFFECTIVE_ENABLE_ASM AND NOT FFMPEG_NATIVE_EFFECTIVE_ENABLE_X86_TX_ASM)
        list(REMOVE_ITEM _ffmpeg_objects x86/tx_float.o x86/tx_float_init.o)
    endif()
    if(_library STREQUAL "avcodec" AND FFMPEG_NATIVE_EFFECTIVE_ENABLE_ASM AND CMAKE_GENERATOR MATCHES "Visual Studio")
        # CMake's Visual Studio NASM rule writes several assembly files by basename,
        # which collides for VVC/HEVC sources such as sao.asm. Keep VVC on its C path.
        list(FILTER _ffmpeg_objects EXCLUDE REGEX "^x86/vvc/")
    endif()
    _ffmpeg_native_objects_to_sources(_ffmpeg_sources "${FFMPEG_SOURCE_DIR}/lib${_library}" ${_ffmpeg_objects})
    if(_library STREQUAL "avutil" AND FFMPEG_NATIVE_EFFECTIVE_ENABLE_ASM AND NOT FFMPEG_NATIVE_EFFECTIVE_ENABLE_X86_TX_ASM)
        _ffmpeg_native_write_x86_tx_stub(_ffmpeg_tx_stub)
        list(APPEND _ffmpeg_sources "${_ffmpeg_tx_stub}")
    endif()
    if(_library STREQUAL "avcodec" AND FFMPEG_NATIVE_EFFECTIVE_ENABLE_ASM AND CMAKE_GENERATOR MATCHES "Visual Studio")
        _ffmpeg_native_write_vvc_x86_stub(_ffmpeg_vvc_stub)
        list(APPEND _ffmpeg_sources "${_ffmpeg_vvc_stub}")
    endif()
    set(${_out} "${_ffmpeg_sources}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_write_binary_c _path _source _symbol)
    file(READ "${_source}" _ffmpeg_hex HEX)
    string(LENGTH "${_ffmpeg_hex}" _ffmpeg_hex_len)
    math(EXPR _ffmpeg_len "${_ffmpeg_hex_len} / 2")
    string(REGEX MATCHALL ".." _ffmpeg_bytes "${_ffmpeg_hex}")

    set(_ffmpeg_content "/* Generated by ffmpeg-cmake native backend. */\n#include <stddef.h>\n\n")
    string(APPEND _ffmpeg_content "const unsigned char ff_${_symbol}_data[] = {\n")
    set(_ffmpeg_col 0)
    foreach(_ffmpeg_byte IN LISTS _ffmpeg_bytes)
        if(_ffmpeg_col EQUAL 0)
            string(APPEND _ffmpeg_content "    ")
        endif()
        string(APPEND _ffmpeg_content "0x${_ffmpeg_byte}, ")
        math(EXPR _ffmpeg_col "${_ffmpeg_col} + 1")
        if(_ffmpeg_col EQUAL 12)
            string(APPEND _ffmpeg_content "\n")
            set(_ffmpeg_col 0)
        endif()
    endforeach()
    if(NOT _ffmpeg_col EQUAL 0)
        string(APPEND _ffmpeg_content "\n")
    endif()
    string(APPEND _ffmpeg_content "    0x00\n};\n")
    string(APPEND _ffmpeg_content "const unsigned int ff_${_symbol}_len = ${_ffmpeg_len};\n")
    _ffmpeg_native_write_file_if_changed("${_path}" "${_ffmpeg_content}")
endfunction()

function(_ffmpeg_native_generate_ffmpeg_resources _out)
    set(_ffmpeg_resource_dir "${FFMPEG_NATIVE_GENERATED_DIR}/fftools/resources")
    file(MAKE_DIRECTORY "${_ffmpeg_resource_dir}")

    set(_ffmpeg_graph_html_c "${_ffmpeg_resource_dir}/graph.html.c")
    set(_ffmpeg_graph_css_c "${_ffmpeg_resource_dir}/graph.css.c")
    _ffmpeg_native_write_binary_c("${_ffmpeg_graph_html_c}" "${FFMPEG_SOURCE_DIR}/fftools/resources/graph.html" graph_html)
    _ffmpeg_native_write_binary_c("${_ffmpeg_graph_css_c}" "${FFMPEG_SOURCE_DIR}/fftools/resources/graph.css" graph_css)

    set(${_out} "${_ffmpeg_graph_html_c};${_ffmpeg_graph_css_c}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_collect_fftool_sources _out _tool)
    set(_ffmpeg_makefile "${FFMPEG_SOURCE_DIR}/fftools/Makefile")
    set(_ffmpeg_objects
        "fftools/cmdutils.o"
        "fftools/opt_common.o"
        "fftools/${_tool}.o")
    _ffmpeg_native_append_makefile_objects(_ffmpeg_objects "${_ffmpeg_makefile}" "OBJS-${_tool}")

    if(_tool STREQUAL "ffmpeg")
        _ffmpeg_native_append_makefile_objects(_ffmpeg_objects "${FFMPEG_SOURCE_DIR}/fftools/resources/Makefile" "OBJS-resman")
    endif()

    _ffmpeg_native_objects_to_sources(_ffmpeg_sources "${FFMPEG_SOURCE_DIR}" ${_ffmpeg_objects})

    if(_tool STREQUAL "ffmpeg")
        _ffmpeg_native_generate_ffmpeg_resources(_ffmpeg_resource_sources)
        list(APPEND _ffmpeg_sources ${_ffmpeg_resource_sources})
    endif()

    list(REMOVE_DUPLICATES _ffmpeg_sources)
    set(${_out} "${_ffmpeg_sources}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_collect_enabled_examples _out)
    set(_ffmpeg_makefile "${FFMPEG_SOURCE_DIR}/doc/examples/Makefile")
    if(NOT EXISTS "${_ffmpeg_makefile}")
        set(${_out} "" PARENT_SCOPE)
        return()
    endif()

    file(STRINGS "${_ffmpeg_makefile}" _ffmpeg_lines)
    set(_ffmpeg_examples)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_lines)
        string(REGEX REPLACE "#.*$" "" _ffmpeg_line "${_ffmpeg_line}")
        string(REGEX REPLACE "[ \t]+$" "" _ffmpeg_line "${_ffmpeg_line}")
        if(_ffmpeg_line MATCHES "^EXAMPLES-\\$\\((!?[A-Za-z0-9_]+)\\)[ \t]*\\+?=[ \t]*(.*)$")
            set(_ffmpeg_condition "${CMAKE_MATCH_1}")
            set(_ffmpeg_items "${CMAKE_MATCH_2}")
            _ffmpeg_native_make_condition_enabled(_ffmpeg_enabled "${_ffmpeg_condition}")
            if(_ffmpeg_enabled)
                _ffmpeg_native_normalize_words(_ffmpeg_example_names "${_ffmpeg_items}")
                list(APPEND _ffmpeg_examples ${_ffmpeg_example_names})
            endif()
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_examples)
    list(SORT _ffmpeg_examples)
    set(${_out} "${_ffmpeg_examples}" PARENT_SCOPE)
endfunction()
