include_guard(GLOBAL)

option(FFMPEG_NATIVE_AUDIT_DEPENDENCIES "Inspect native external dependency targets and write a static/import/CRT audit report." ON)
option(FFMPEG_NATIVE_WARN_ON_DEPENDENCY_AUDIT_ISSUES "Emit CMake warnings for native dependency audit issues." ON)
option(FFMPEG_NATIVE_REQUIRE_STATIC_EXTERNAL_DEPENDENCIES "Fail configure if a native static FFmpeg build links to shared/import external dependency libraries." OFF)
option(FFMPEG_NATIVE_REQUIRE_MATCHED_MSVC_RUNTIME "Fail configure if native static dependency archives advertise a CRT family that does not match CMAKE_MSVC_RUNTIME_LIBRARY." OFF)
set(FFMPEG_NATIVE_DUMPBIN "" CACHE FILEPATH "Optional dumpbin executable used to inspect MSVC .lib dependencies for import libraries and CRT directives.")

function(_ffmpeg_native_audit_find_dumpbin _out)
    if(FFMPEG_NATIVE_DUMPBIN AND EXISTS "${FFMPEG_NATIVE_DUMPBIN}")
        set(${_out} "${FFMPEG_NATIVE_DUMPBIN}" PARENT_SCOPE)
        return()
    endif()

    set(_ffmpeg_hints)
    foreach(_ffmpeg_tool_var IN ITEMS CMAKE_LINKER CMAKE_C_COMPILER CMAKE_AR)
        if(DEFINED ${_ffmpeg_tool_var} AND NOT "${${_ffmpeg_tool_var}}" STREQUAL "")
            get_filename_component(_ffmpeg_tool_dir "${${_ffmpeg_tool_var}}" DIRECTORY)
            if(IS_DIRECTORY "${_ffmpeg_tool_dir}")
                list(APPEND _ffmpeg_hints "${_ffmpeg_tool_dir}")
            endif()
        endif()
    endforeach()

    find_program(_ffmpeg_dumpbin NAMES dumpbin.exe dumpbin HINTS ${_ffmpeg_hints} NO_CACHE)
    if(_ffmpeg_dumpbin)
        set(FFMPEG_NATIVE_DUMPBIN "${_ffmpeg_dumpbin}" CACHE FILEPATH "Optional dumpbin executable used to inspect MSVC .lib dependencies for import libraries and CRT directives." FORCE)
    endif()
    set(${_out} "${_ffmpeg_dumpbin}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_audit_normalize_link_item _out _item)
    set(_ffmpeg_item "${_item}")
    foreach(_ffmpeg_unused RANGE 0 4)
        if(_ffmpeg_item MATCHES "^\\$<LINK_ONLY:(.*)>$")
            set(_ffmpeg_item "${CMAKE_MATCH_1}")
        elseif(_ffmpeg_item MATCHES "^\\$<BUILD_INTERFACE:(.*)>$")
            set(_ffmpeg_item "${CMAKE_MATCH_1}")
        elseif(_ffmpeg_item MATCHES "^\\$<INSTALL_INTERFACE:(.*)>$")
            set(_ffmpeg_item "${CMAKE_MATCH_1}")
        else()
            break()
        endif()
    endforeach()
    set(${_out} "${_ffmpeg_item}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_audit_append_target_locations _target)
    get_target_property(_ffmpeg_aliased "${_target}" ALIASED_TARGET)
    if(_ffmpeg_aliased)
        set(_target "${_ffmpeg_aliased}")
    endif()

    set(_ffmpeg_configs)
    get_target_property(_ffmpeg_imported_configs "${_target}" IMPORTED_CONFIGURATIONS)
    if(_ffmpeg_imported_configs)
        list(APPEND _ffmpeg_configs ${_ffmpeg_imported_configs})
    endif()
    list(APPEND _ffmpeg_configs NOCONFIG DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
    list(REMOVE_DUPLICATES _ffmpeg_configs)

    set(_ffmpeg_properties IMPORTED_LOCATION IMPORTED_IMPLIB)
    foreach(_ffmpeg_property IN LISTS _ffmpeg_properties)
        get_target_property(_ffmpeg_value "${_target}" "${_ffmpeg_property}")
        if(_ffmpeg_value AND EXISTS "${_ffmpeg_value}")
            set_property(GLOBAL APPEND PROPERTY FFMPEG_NATIVE_AUDIT_FILES "${_ffmpeg_value}")
        endif()
        foreach(_ffmpeg_config IN LISTS _ffmpeg_configs)
            get_target_property(_ffmpeg_value "${_target}" "${_ffmpeg_property}_${_ffmpeg_config}")
            if(_ffmpeg_value AND EXISTS "${_ffmpeg_value}")
                set_property(GLOBAL APPEND PROPERTY FFMPEG_NATIVE_AUDIT_FILES "${_ffmpeg_value}")
            endif()
        endforeach()
    endforeach()
endfunction()

function(_ffmpeg_native_audit_visit_target _target)
    if(NOT TARGET "${_target}")
        return()
    endif()

    get_target_property(_ffmpeg_aliased "${_target}" ALIASED_TARGET)
    if(_ffmpeg_aliased)
        set(_target "${_ffmpeg_aliased}")
    endif()

    get_property(_ffmpeg_visited GLOBAL PROPERTY FFMPEG_NATIVE_AUDIT_VISITED_TARGETS)
    if(_target IN_LIST _ffmpeg_visited)
        return()
    endif()
    set_property(GLOBAL APPEND PROPERTY FFMPEG_NATIVE_AUDIT_VISITED_TARGETS "${_target}")
    set_property(GLOBAL APPEND PROPERTY FFMPEG_NATIVE_AUDIT_TARGETS "${_target}")

    _ffmpeg_native_audit_append_target_locations("${_target}")

    foreach(_ffmpeg_property IN ITEMS
            INTERFACE_LINK_LIBRARIES
            IMPORTED_LINK_INTERFACE_LIBRARIES
            LINK_LIBRARIES)
        get_target_property(_ffmpeg_links "${_target}" "${_ffmpeg_property}")
        foreach(_ffmpeg_link IN LISTS _ffmpeg_links)
            if(_ffmpeg_link STREQUAL "debug" OR _ffmpeg_link STREQUAL "optimized" OR _ffmpeg_link STREQUAL "general")
                continue()
            endif()
            _ffmpeg_native_audit_normalize_link_item(_ffmpeg_link "${_ffmpeg_link}")
            if(TARGET "${_ffmpeg_link}")
                _ffmpeg_native_audit_visit_target("${_ffmpeg_link}")
            elseif(IS_ABSOLUTE "${_ffmpeg_link}" AND EXISTS "${_ffmpeg_link}")
                set_property(GLOBAL APPEND PROPERTY FFMPEG_NATIVE_AUDIT_FILES "${_ffmpeg_link}")
            elseif(NOT _ffmpeg_link MATCHES "^\\$<")
                set_property(GLOBAL APPEND PROPERTY FFMPEG_NATIVE_AUDIT_LINK_ITEMS "${_ffmpeg_link}")
            endif()
        endforeach()
    endforeach()
endfunction()

function(_ffmpeg_native_audit_extract_crt _out _directives)
    string(TOUPPER "${_directives}" _ffmpeg_text)
    string(REGEX MATCHALL "/DEFAULTLIB:\"?[A-Z0-9_.+-]+\"?" _ffmpeg_defaultlibs "${_ffmpeg_text}")

    set(_ffmpeg_crt)
    foreach(_ffmpeg_defaultlib IN LISTS _ffmpeg_defaultlibs)
        string(REGEX REPLACE "^/DEFAULTLIB:\"?([^\" ]+)\"?$" "\\1" _ffmpeg_defaultlib "${_ffmpeg_defaultlib}")
        if(_ffmpeg_defaultlib MATCHES "^(LIBCMTD|LIBCMT|MSVCRTD|MSVCRT|LIBCD|LIBC)$")
            list(APPEND _ffmpeg_crt "${_ffmpeg_defaultlib}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_crt)
    list(SORT _ffmpeg_crt)
    set(${_out} "${_ffmpeg_crt}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_audit_extract_dlls _out _headers)
    string(REGEX MATCHALL "DLL name[ \t]+[^ \r\n][^\r\n]*" _ffmpeg_dll_lines "${_headers}")
    set(_ffmpeg_dlls)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_dll_lines)
        string(REGEX REPLACE "^DLL name[ \t]+" "" _ffmpeg_dll "${_ffmpeg_line}")
        string(STRIP "${_ffmpeg_dll}" _ffmpeg_dll)
        if(_ffmpeg_dll)
            list(APPEND _ffmpeg_dlls "${_ffmpeg_dll}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_dlls)
    list(SORT _ffmpeg_dlls)
    set(${_out} "${_ffmpeg_dlls}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_audit_inspect_file _out_kind _out_crt _out_dlls _path)
    get_filename_component(_ffmpeg_ext "${_path}" EXT)
    string(TOLOWER "${_ffmpeg_ext}" _ffmpeg_ext)

    set(_ffmpeg_kind "link item")
    set(_ffmpeg_crt)
    set(_ffmpeg_dlls)

    if(_ffmpeg_ext STREQUAL ".dll")
        set(_ffmpeg_kind "shared library")
    elseif(_ffmpeg_ext STREQUAL ".so" OR _ffmpeg_ext STREQUAL ".dylib")
        set(_ffmpeg_kind "shared library")
    elseif(_ffmpeg_ext STREQUAL ".a")
        set(_ffmpeg_kind "static archive")
    elseif(_ffmpeg_ext STREQUAL ".lib")
        set(_ffmpeg_kind "MSVC library")
        _ffmpeg_native_audit_find_dumpbin(_ffmpeg_dumpbin)
        if(_ffmpeg_dumpbin)
            execute_process(
                COMMAND "${_ffmpeg_dumpbin}" /headers "${_path}"
                RESULT_VARIABLE _ffmpeg_headers_result
                OUTPUT_VARIABLE _ffmpeg_headers
                ERROR_VARIABLE _ffmpeg_headers_error
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_STRIP_TRAILING_WHITESPACE)
            if(_ffmpeg_headers_result EQUAL 0)
                _ffmpeg_native_audit_extract_dlls(_ffmpeg_dlls "${_ffmpeg_headers}")
                if(_ffmpeg_dlls)
                    set(_ffmpeg_kind "import library")
                elseif(_ffmpeg_headers MATCHES "SECTION HEADER|\\.text|\\.drectve")
                    set(_ffmpeg_kind "static archive")
                endif()
            endif()

            execute_process(
                COMMAND "${_ffmpeg_dumpbin}" /directives "${_path}"
                RESULT_VARIABLE _ffmpeg_directives_result
                OUTPUT_VARIABLE _ffmpeg_directives
                ERROR_VARIABLE _ffmpeg_directives_error
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_STRIP_TRAILING_WHITESPACE)
            if(_ffmpeg_directives_result EQUAL 0)
                _ffmpeg_native_audit_extract_crt(_ffmpeg_crt "${_ffmpeg_directives}")
                if(_ffmpeg_crt AND _ffmpeg_kind STREQUAL "MSVC library")
                    set(_ffmpeg_kind "static archive")
                endif()
            endif()
        endif()
    endif()

    set(${_out_kind} "${_ffmpeg_kind}" PARENT_SCOPE)
    set(${_out_crt} "${_ffmpeg_crt}" PARENT_SCOPE)
    set(${_out_dlls} "${_ffmpeg_dlls}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_audit_expected_msvc_crt _out)
    if(NOT MSVC)
        set(${_out} "" PARENT_SCOPE)
        return()
    endif()

    string(TOUPPER "${CMAKE_MSVC_RUNTIME_LIBRARY}" _ffmpeg_runtime)
    if(_ffmpeg_runtime MATCHES "DLL")
        set(${_out} "dynamic" PARENT_SCOPE)
    elseif(_ffmpeg_runtime MATCHES "MULTITHREADED")
        set(${_out} "static" PARENT_SCOPE)
    else()
        set(${_out} "" PARENT_SCOPE)
    endif()
endfunction()

function(_ffmpeg_native_audit_check_file _warnings_var _feature _path _kind _crt)
    if(FFMPEG_BUILD_STATIC AND FFMPEG_NATIVE_REQUIRE_STATIC_EXTERNAL_DEPENDENCIES)
        if(_kind STREQUAL "import library" OR _kind STREQUAL "shared library")
            list(APPEND ${_warnings_var} "${_feature}: ${_path} is a ${_kind}")
        endif()
    endif()

    if(MSVC AND _kind STREQUAL "static archive" AND _crt)
        _ffmpeg_native_audit_expected_msvc_crt(_ffmpeg_expected_crt)
        if(_ffmpeg_expected_crt STREQUAL "static")
            foreach(_ffmpeg_crt IN LISTS _crt)
                if(_ffmpeg_crt STREQUAL "MSVCRT" OR _ffmpeg_crt STREQUAL "MSVCRTD")
                    list(APPEND ${_warnings_var} "${_feature}: ${_path} advertises DLL CRT ${_ffmpeg_crt} but CMAKE_MSVC_RUNTIME_LIBRARY selects static CRT")
                endif()
            endforeach()
        elseif(_ffmpeg_expected_crt STREQUAL "dynamic")
            foreach(_ffmpeg_crt IN LISTS _crt)
                if(_ffmpeg_crt STREQUAL "LIBCMT" OR _ffmpeg_crt STREQUAL "LIBCMTD")
                    list(APPEND ${_warnings_var} "${_feature}: ${_path} advertises static CRT ${_ffmpeg_crt} but CMAKE_MSVC_RUNTIME_LIBRARY selects DLL CRT")
                endif()
            endforeach()
        endif()
    endif()

    set(${_warnings_var} "${${_warnings_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_audit_table_value _out _values)
    if(_values)
        string(REPLACE ";" ", " _ffmpeg_text "${_values}")
    else()
        set(_ffmpeg_text "none")
    endif()
    string(REPLACE "|" "\\|" _ffmpeg_text "${_ffmpeg_text}")
    set(${_out} "${_ffmpeg_text}" PARENT_SCOPE)
endfunction()

function(ffmpeg_native_audit_dependencies _out_file)
    set(FFMPEG_NATIVE_DEPENDENCY_AUDIT_FILE "" PARENT_SCOPE)
    set(FFMPEG_NATIVE_DEPENDENCY_AUDIT_SUMMARY "" PARENT_SCOPE)
    set(FFMPEG_NATIVE_DEPENDENCY_AUDIT_WARNINGS "" PARENT_SCOPE)

    if(NOT FFMPEG_NATIVE_AUDIT_DEPENDENCIES)
        set(${_out_file} "" PARENT_SCOPE)
        return()
    endif()

    set(_ffmpeg_content "# FFmpeg Native Dependency Audit\n\n")
    string(APPEND _ffmpeg_content "Generated from imported native external targets and their transitive link interfaces.\n")
    string(APPEND _ffmpeg_content "The audit is best-effort: MSVC .lib classification requires dumpbin; unresolved system library names are listed separately.\n\n")

    set(_ffmpeg_summary)
    set(_ffmpeg_warnings)
    set(_ffmpeg_any_rows FALSE)

    foreach(_ffmpeg_target IN LISTS FFMPEG_NATIVE_DEPENDENCY_TARGETS)
        string(REPLACE "FFmpegExternal::" "" _ffmpeg_feature "${_ffmpeg_target}")
        set_property(GLOBAL PROPERTY FFMPEG_NATIVE_AUDIT_VISITED_TARGETS "")
        set_property(GLOBAL PROPERTY FFMPEG_NATIVE_AUDIT_TARGETS "")
        set_property(GLOBAL PROPERTY FFMPEG_NATIVE_AUDIT_FILES "")
        set_property(GLOBAL PROPERTY FFMPEG_NATIVE_AUDIT_LINK_ITEMS "")

        _ffmpeg_native_audit_visit_target("${_ffmpeg_target}")

        get_property(_ffmpeg_visited_targets GLOBAL PROPERTY FFMPEG_NATIVE_AUDIT_TARGETS)
        get_property(_ffmpeg_files GLOBAL PROPERTY FFMPEG_NATIVE_AUDIT_FILES)
        get_property(_ffmpeg_link_items GLOBAL PROPERTY FFMPEG_NATIVE_AUDIT_LINK_ITEMS)
        list(REMOVE_DUPLICATES _ffmpeg_visited_targets)
        list(REMOVE_DUPLICATES _ffmpeg_files)
        list(REMOVE_DUPLICATES _ffmpeg_link_items)
        list(SORT _ffmpeg_visited_targets)
        list(SORT _ffmpeg_files)
        list(SORT _ffmpeg_link_items)

        string(APPEND _ffmpeg_content "## ${_ffmpeg_feature}\n\n")
        _ffmpeg_native_audit_table_value(_ffmpeg_targets_text "${_ffmpeg_visited_targets}")
        _ffmpeg_native_audit_table_value(_ffmpeg_link_items_text "${_ffmpeg_link_items}")
        string(APPEND _ffmpeg_content "Targets: ${_ffmpeg_targets_text}\n\n")
        string(APPEND _ffmpeg_content "Unresolved/system link items: ${_ffmpeg_link_items_text}\n\n")
        string(APPEND _ffmpeg_content "| Path | Kind | CRT defaultlibs | Import DLLs |\n")
        string(APPEND _ffmpeg_content "| --- | --- | --- | --- |\n")

        set(_ffmpeg_kinds)
        set(_ffmpeg_crt_all)
        foreach(_ffmpeg_file IN LISTS _ffmpeg_files)
            _ffmpeg_native_audit_inspect_file(_ffmpeg_kind _ffmpeg_crt _ffmpeg_dlls "${_ffmpeg_file}")
            _ffmpeg_native_audit_check_file(_ffmpeg_warnings "${_ffmpeg_feature}" "${_ffmpeg_file}" "${_ffmpeg_kind}" "${_ffmpeg_crt}")
            list(APPEND _ffmpeg_kinds "${_ffmpeg_kind}")
            list(APPEND _ffmpeg_crt_all ${_ffmpeg_crt})
            _ffmpeg_native_audit_table_value(_ffmpeg_crt_text "${_ffmpeg_crt}")
            _ffmpeg_native_audit_table_value(_ffmpeg_dlls_text "${_ffmpeg_dlls}")
            string(REPLACE "|" "\\|" _ffmpeg_file_text "${_ffmpeg_file}")
            string(APPEND _ffmpeg_content "| `${_ffmpeg_file_text}` | ${_ffmpeg_kind} | ${_ffmpeg_crt_text} | ${_ffmpeg_dlls_text} |\n")
            set(_ffmpeg_any_rows TRUE)
        endforeach()
        if(NOT _ffmpeg_files)
            string(APPEND _ffmpeg_content "| none | none | none | none |\n")
        endif()
        string(APPEND _ffmpeg_content "\n")

        list(REMOVE_DUPLICATES _ffmpeg_kinds)
        list(REMOVE_DUPLICATES _ffmpeg_crt_all)
        list(SORT _ffmpeg_kinds)
        list(SORT _ffmpeg_crt_all)
        if(_ffmpeg_kinds)
            string(REPLACE ";" "/" _ffmpeg_kind_summary "${_ffmpeg_kinds}")
        else()
            set(_ffmpeg_kind_summary "target-only")
        endif()
        if(_ffmpeg_crt_all)
            string(REPLACE ";" "," _ffmpeg_crt_summary "${_ffmpeg_crt_all}")
            list(APPEND _ffmpeg_summary "${_ffmpeg_feature}: ${_ffmpeg_kind_summary}; CRT ${_ffmpeg_crt_summary}")
        else()
            list(APPEND _ffmpeg_summary "${_ffmpeg_feature}: ${_ffmpeg_kind_summary}")
        endif()
    endforeach()

    if(_ffmpeg_warnings)
        list(REMOVE_DUPLICATES _ffmpeg_warnings)
        list(SORT _ffmpeg_warnings)
        string(APPEND _ffmpeg_content "## Audit Warnings\n\n")
        foreach(_ffmpeg_warning IN LISTS _ffmpeg_warnings)
            string(APPEND _ffmpeg_content "- ${_ffmpeg_warning}\n")
            if(FFMPEG_NATIVE_WARN_ON_DEPENDENCY_AUDIT_ISSUES)
                message(WARNING "${_ffmpeg_warning}")
            endif()
        endforeach()
        if(FFMPEG_NATIVE_REQUIRE_STATIC_EXTERNAL_DEPENDENCIES OR FFMPEG_NATIVE_REQUIRE_MATCHED_MSVC_RUNTIME)
            string(REPLACE ";" "\n  " _ffmpeg_warning_text "${_ffmpeg_warnings}")
            message(FATAL_ERROR "Native FFmpeg dependency audit failed:\n  ${_ffmpeg_warning_text}")
        endif()
    else()
        string(APPEND _ffmpeg_content "## Audit Warnings\n\nnone\n")
    endif()

    if(NOT _ffmpeg_any_rows)
        list(APPEND _ffmpeg_summary "no file-backed dependency link items")
    endif()

    set(_ffmpeg_file "${CMAKE_CURRENT_BINARY_DIR}/ffmpeg-native/native-dependency-audit.md")
    _ffmpeg_native_write_file_if_changed("${_ffmpeg_file}" "${_ffmpeg_content}")

    set(FFMPEG_NATIVE_DEPENDENCY_AUDIT_FILE "${_ffmpeg_file}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_DEPENDENCY_AUDIT_SUMMARY "${_ffmpeg_summary}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_DEPENDENCY_AUDIT_WARNINGS "${_ffmpeg_warnings}" PARENT_SCOPE)
    set(${_out_file} "${_ffmpeg_file}" PARENT_SCOPE)
endfunction()
