include_guard(GLOBAL)

function(_ffmpeg_native_coverage_intersection _out _left _right)
    set(_ffmpeg_result)
    foreach(_ffmpeg_item IN LISTS _left)
        if(_ffmpeg_item IN_LIST _right)
            list(APPEND _ffmpeg_result "${_ffmpeg_item}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_result)
    list(SORT _ffmpeg_result)
    set(${_out} "${_ffmpeg_result}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_coverage_difference _out _left _right)
    set(_ffmpeg_result)
    foreach(_ffmpeg_item IN LISTS _left)
        if(NOT _ffmpeg_item IN_LIST _right)
            list(APPEND _ffmpeg_result "${_ffmpeg_item}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_result)
    list(SORT _ffmpeg_result)
    set(${_out} "${_ffmpeg_result}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_coverage_suffix _out _values _suffix)
    set(_ffmpeg_result)
    foreach(_ffmpeg_item IN LISTS _values)
        if(_ffmpeg_item MATCHES "_${_suffix}$")
            list(APPEND _ffmpeg_result "${_ffmpeg_item}")
        endif()
    endforeach()
    list(SORT _ffmpeg_result)
    set(${_out} "${_ffmpeg_result}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_coverage_hardware _out _values)
    set(_ffmpeg_result)
    foreach(_ffmpeg_item IN LISTS _values)
        if(_ffmpeg_item MATCHES "_hwaccel$" OR
           _ffmpeg_item MATCHES "(^|_)(amf|cuda|cuvid|d3d11va|d3d12va|dxva2|ffnvcodec|libmfx|libvpl|mediacodec|mediafoundation|mf|mmal|nvdec|nvenc|ohcodec|omx|opencl|qsv|qsvdec|qsvenc|qsvvpp|rkmpp|vaapi|vdpau|videotoolbox|vulkan|v4l2_m2m)($|_)")
            list(APPEND _ffmpeg_result "${_ffmpeg_item}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_result)
    list(SORT _ffmpeg_result)
    set(${_out} "${_ffmpeg_result}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_coverage_append_row _content_var _summary_var _label _all_values _enabled_values)
    _ffmpeg_native_coverage_intersection(_ffmpeg_enabled "${_all_values}" "${_enabled_values}")
    _ffmpeg_native_coverage_difference(_ffmpeg_disabled "${_all_values}" "${_enabled_values}")
    list(LENGTH _all_values _ffmpeg_all_count)
    list(LENGTH _ffmpeg_enabled _ffmpeg_enabled_count)
    list(LENGTH _ffmpeg_disabled _ffmpeg_disabled_count)
    string(APPEND ${_content_var} "| ${_label} | ${_ffmpeg_all_count} | ${_ffmpeg_enabled_count} | ${_ffmpeg_disabled_count} |\n")
    list(APPEND ${_summary_var} "${_label}: ${_ffmpeg_enabled_count}/${_ffmpeg_all_count}")
    set(${_content_var} "${${_content_var}}" PARENT_SCOPE)
    set(${_summary_var} "${${_summary_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_coverage_append_list _content_var _label _values)
    if(_values)
        string(REPLACE ";" ", " _ffmpeg_text "${_values}")
    else()
        set(_ffmpeg_text "none")
    endif()
    string(APPEND ${_content_var} "\n### ${_label}\n\n${_ffmpeg_text}\n")
    set(${_content_var} "${${_content_var}}" PARENT_SCOPE)
endfunction()

function(ffmpeg_native_write_coverage_report _out_file)
    set(_ffmpeg_all_features
        ${FFMPEG_NATIVE_ALL_CONFIG_FEATURES}
        ${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}
        ${FFMPEG_NATIVE_ALL_HAVE_FEATURES}
        ${FFMPEG_NATIVE_ALL_ARCH_FEATURES})
    set(_ffmpeg_enabled_features
        ${FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES}
        ${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}
        ${FFMPEG_NATIVE_ENABLED_HAVE_FEATURES}
        ${FFMPEG_NATIVE_ENABLED_ARCH_FEATURES})
    list(REMOVE_DUPLICATES _ffmpeg_all_features)
    list(REMOVE_DUPLICATES _ffmpeg_enabled_features)
    list(SORT _ffmpeg_all_features)
    list(SORT _ffmpeg_enabled_features)

    _ffmpeg_native_coverage_suffix(_ffmpeg_encoders "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" encoder)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_encoders "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" encoder)
    _ffmpeg_native_coverage_suffix(_ffmpeg_decoders "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" decoder)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_decoders "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" decoder)
    _ffmpeg_native_coverage_suffix(_ffmpeg_hwaccels "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" hwaccel)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_hwaccels "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" hwaccel)
    _ffmpeg_native_coverage_suffix(_ffmpeg_muxers "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" muxer)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_muxers "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" muxer)
    _ffmpeg_native_coverage_suffix(_ffmpeg_demuxers "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" demuxer)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_demuxers "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" demuxer)
    _ffmpeg_native_coverage_suffix(_ffmpeg_parsers "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" parser)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_parsers "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" parser)
    _ffmpeg_native_coverage_suffix(_ffmpeg_bsfs "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" bsf)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_bsfs "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" bsf)
    _ffmpeg_native_coverage_suffix(_ffmpeg_protocols "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" protocol)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_protocols "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" protocol)
    _ffmpeg_native_coverage_suffix(_ffmpeg_indevs "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" indev)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_indevs "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" indev)
    _ffmpeg_native_coverage_suffix(_ffmpeg_outdevs "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" outdev)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_outdevs "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" outdev)
    _ffmpeg_native_coverage_suffix(_ffmpeg_filters "${FFMPEG_NATIVE_ALL_COMPONENT_FEATURES}" filter)
    _ffmpeg_native_coverage_suffix(_ffmpeg_enabled_filters "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}" filter)

    _ffmpeg_native_coverage_hardware(_ffmpeg_all_hardware "${_ffmpeg_all_features}")
    _ffmpeg_native_coverage_hardware(_ffmpeg_enabled_hardware "${_ffmpeg_enabled_features}")
    _ffmpeg_native_coverage_difference(_ffmpeg_disabled_hardware "${_ffmpeg_all_hardware}" "${_ffmpeg_enabled_hardware}")

    set(_ffmpeg_content "# FFmpeg Native CMake Coverage\n\n")
    string(APPEND _ffmpeg_content "Generated from the FFmpeg configure metadata and native CMake feature model.\n")
    string(APPEND _ffmpeg_content "Counts are configure-symbol coverage, not a guarantee that every source file has been build-validated.\n\n")
    string(APPEND _ffmpeg_content "## Summary\n\n")
    string(APPEND _ffmpeg_content "| Category | Known | Enabled | Disabled |\n")
    string(APPEND _ffmpeg_content "| --- | ---: | ---: | ---: |\n")

    set(_ffmpeg_summary)
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Config features" "${FFMPEG_NATIVE_ALL_CONFIG_FEATURES}" "${FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "HAVE features" "${FFMPEG_NATIVE_ALL_HAVE_FEATURES}" "${FFMPEG_NATIVE_ENABLED_HAVE_FEATURES}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Arch features" "${FFMPEG_NATIVE_ALL_ARCH_FEATURES}" "${FFMPEG_NATIVE_ENABLED_ARCH_FEATURES}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Encoders" "${_ffmpeg_encoders}" "${_ffmpeg_enabled_encoders}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Decoders" "${_ffmpeg_decoders}" "${_ffmpeg_enabled_decoders}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "HW accels" "${_ffmpeg_hwaccels}" "${_ffmpeg_enabled_hwaccels}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Muxers" "${_ffmpeg_muxers}" "${_ffmpeg_enabled_muxers}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Demuxers" "${_ffmpeg_demuxers}" "${_ffmpeg_enabled_demuxers}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Parsers" "${_ffmpeg_parsers}" "${_ffmpeg_enabled_parsers}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Bitstream filters" "${_ffmpeg_bsfs}" "${_ffmpeg_enabled_bsfs}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Protocols" "${_ffmpeg_protocols}" "${_ffmpeg_enabled_protocols}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Input devices" "${_ffmpeg_indevs}" "${_ffmpeg_enabled_indevs}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Output devices" "${_ffmpeg_outdevs}" "${_ffmpeg_enabled_outdevs}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Filters" "${_ffmpeg_filters}" "${_ffmpeg_enabled_filters}")
    _ffmpeg_native_coverage_append_row(_ffmpeg_content _ffmpeg_summary "Hardware-related" "${_ffmpeg_all_hardware}" "${_ffmpeg_enabled_hardware}")

    string(APPEND _ffmpeg_content "\n## Hardware Details\n")
    _ffmpeg_native_coverage_append_list(_ffmpeg_content "Enabled hardware-related features" "${_ffmpeg_enabled_hardware}")
    _ffmpeg_native_coverage_append_list(_ffmpeg_content "Disabled hardware-related features" "${_ffmpeg_disabled_hardware}")
    _ffmpeg_native_coverage_append_list(_ffmpeg_content "Found external dependencies" "${FFMPEG_NATIVE_FOUND_EXTERNAL_DEPENDENCIES}")
    _ffmpeg_native_coverage_append_list(_ffmpeg_content "Missing external dependencies" "${FFMPEG_NATIVE_MISSING_EXTERNAL_DEPENDENCIES}")

    string(APPEND _ffmpeg_content "\n## Enabled Components\n")
    _ffmpeg_native_coverage_append_list(_ffmpeg_content "Encoders" "${_ffmpeg_enabled_encoders}")
    _ffmpeg_native_coverage_append_list(_ffmpeg_content "Decoders" "${_ffmpeg_enabled_decoders}")
    _ffmpeg_native_coverage_append_list(_ffmpeg_content "HW accels" "${_ffmpeg_enabled_hwaccels}")
    _ffmpeg_native_coverage_append_list(_ffmpeg_content "Filters" "${_ffmpeg_enabled_filters}")

    set(_ffmpeg_file "${CMAKE_CURRENT_BINARY_DIR}/ffmpeg-native/native-coverage.md")
    _ffmpeg_native_write_file_if_changed("${_ffmpeg_file}" "${_ffmpeg_content}")

    set(FFMPEG_NATIVE_COVERAGE_FILE "${_ffmpeg_file}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_COVERAGE_SUMMARY "${_ffmpeg_summary}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_HARDWARE_ENABLED_FEATURES "${_ffmpeg_enabled_hardware}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_HARDWARE_DISABLED_FEATURES "${_ffmpeg_disabled_hardware}" PARENT_SCOPE)
    set(${_out_file} "${_ffmpeg_file}" PARENT_SCOPE)
endfunction()
