if(NOT FFMPEG_DEVICE_CHECK_FFMPEG)
    message(FATAL_ERROR "FFMPEG_DEVICE_CHECK_FFMPEG is required")
endif()
if(NOT EXISTS "${FFMPEG_DEVICE_CHECK_FFMPEG}")
    message(FATAL_ERROR "FFmpeg executable does not exist: ${FFMPEG_DEVICE_CHECK_FFMPEG}")
endif()
if(NOT FFMPEG_DEVICE_CHECK_NAMES AND FFMPEG_DEVICE_CHECK_NAMES_CSV)
    string(REPLACE "," ";" FFMPEG_DEVICE_CHECK_NAMES "${FFMPEG_DEVICE_CHECK_NAMES_CSV}")
endif()
if(NOT FFMPEG_DEVICE_CHECK_NAMES)
    message(FATAL_ERROR "FFMPEG_DEVICE_CHECK_NAMES is required")
endif()
if(NOT FFMPEG_DEVICE_CHECK_TIMEOUT)
    set(FFMPEG_DEVICE_CHECK_TIMEOUT 30)
endif()

execute_process(
    COMMAND "${FFMPEG_DEVICE_CHECK_FFMPEG}" -hide_banner -devices
    RESULT_VARIABLE _ffmpeg_result
    OUTPUT_VARIABLE _ffmpeg_stdout
    ERROR_VARIABLE _ffmpeg_stderr
    TIMEOUT "${FFMPEG_DEVICE_CHECK_TIMEOUT}")
if(NOT _ffmpeg_result STREQUAL "0")
    message(STATUS "ffmpeg -devices stdout:\n${_ffmpeg_stdout}")
    message(STATUS "ffmpeg -devices stderr:\n${_ffmpeg_stderr}")
    message(FATAL_ERROR "ffmpeg -devices failed with exit code ${_ffmpeg_result}")
endif()

set(_ffmpeg_output "${_ffmpeg_stdout}\n${_ffmpeg_stderr}")
string(REPLACE "\r" "" _ffmpeg_output_lines "${_ffmpeg_output}")
string(REPLACE "\n" ";" _ffmpeg_output_lines "${_ffmpeg_output_lines}")
foreach(_ffmpeg_device IN LISTS FFMPEG_DEVICE_CHECK_NAMES)
    set(_ffmpeg_device_found FALSE)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_output_lines)
        string(STRIP "${_ffmpeg_line}" _ffmpeg_line)
        if(NOT _ffmpeg_line MATCHES "^D")
            continue()
        endif()
        string(REGEX REPLACE "[ \t]+" ";" _ffmpeg_fields "${_ffmpeg_line}")
        list(LENGTH _ffmpeg_fields _ffmpeg_field_count)
        if(_ffmpeg_field_count GREATER 1)
            list(GET _ffmpeg_fields 1 _ffmpeg_listed_device)
            if(_ffmpeg_listed_device STREQUAL _ffmpeg_device)
                set(_ffmpeg_device_found TRUE)
                break()
            endif()
        endif()
    endforeach()
    if(NOT _ffmpeg_device_found)
        message(STATUS "ffmpeg -devices stdout:\n${_ffmpeg_stdout}")
        message(STATUS "ffmpeg -devices stderr:\n${_ffmpeg_stderr}")
        message(FATAL_ERROR "ffmpeg -devices did not list expected device '${_ffmpeg_device}'")
    endif()
endforeach()
