include_guard(GLOBAL)

function(_ffmpeg_native_append_user_features _list_var)
    foreach(_ffmpeg_name IN LISTS ${_list_var})
        if(_ffmpeg_name STREQUAL "")
            continue()
        endif()

        if(_ffmpeg_name IN_LIST _ffmpeg_all_components)
            list(APPEND _ffmpeg_enabled_components "${_ffmpeg_name}")
            list(APPEND _ffmpeg_explicit_components "${_ffmpeg_name}")
        elseif(_ffmpeg_name IN_LIST _ffmpeg_all_have)
            list(APPEND _ffmpeg_enabled_have "${_ffmpeg_name}")
            list(APPEND _ffmpeg_explicit_have "${_ffmpeg_name}")
        elseif(_ffmpeg_name IN_LIST _ffmpeg_all_arch)
            list(APPEND _ffmpeg_enabled_arch "${_ffmpeg_name}")
            list(APPEND _ffmpeg_explicit_arch "${_ffmpeg_name}")
        else()
            list(APPEND _ffmpeg_enabled_config "${_ffmpeg_name}")
            list(APPEND _ffmpeg_explicit_config "${_ffmpeg_name}")
        endif()
    endforeach()

    set(_ffmpeg_enabled_config "${_ffmpeg_enabled_config}" PARENT_SCOPE)
    set(_ffmpeg_explicit_config "${_ffmpeg_explicit_config}" PARENT_SCOPE)
    set(_ffmpeg_enabled_components "${_ffmpeg_enabled_components}" PARENT_SCOPE)
    set(_ffmpeg_explicit_components "${_ffmpeg_explicit_components}" PARENT_SCOPE)
    set(_ffmpeg_enabled_have "${_ffmpeg_enabled_have}" PARENT_SCOPE)
    set(_ffmpeg_explicit_have "${_ffmpeg_explicit_have}" PARENT_SCOPE)
    set(_ffmpeg_enabled_arch "${_ffmpeg_enabled_arch}" PARENT_SCOPE)
    set(_ffmpeg_explicit_arch "${_ffmpeg_explicit_arch}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_remove_disabled _enabled_var _disabled)
    foreach(_ffmpeg_disabled IN LISTS _disabled)
        list(REMOVE_ITEM ${_enabled_var} "${_ffmpeg_disabled}")
    endforeach()
    set(${_enabled_var} "${${_enabled_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_expand_disabled_features _out _disabled)
    set(_ffmpeg_expanded)
    foreach(_ffmpeg_disabled IN LISTS _disabled)
        if(_ffmpeg_disabled STREQUAL "")
            continue()
        endif()

        list(APPEND _ffmpeg_expanded "${_ffmpeg_disabled}")

        if("${_ffmpeg_disabled}_external" IN_LIST _ffmpeg_all_have)
            list(APPEND _ffmpeg_expanded "${_ffmpeg_disabled}_external")
        endif()
        if("${_ffmpeg_disabled}_inline" IN_LIST _ffmpeg_all_have)
            list(APPEND _ffmpeg_expanded "${_ffmpeg_disabled}_inline")
        endif()

        if(_ffmpeg_disabled STREQUAL "x86asm")
            foreach(_ffmpeg_have IN LISTS _ffmpeg_all_have)
                if(_ffmpeg_have MATCHES "_external$")
                    list(APPEND _ffmpeg_expanded "${_ffmpeg_have}")
                endif()
            endforeach()
        elseif(_ffmpeg_disabled STREQUAL "asm")
            _ffmpeg_native_expand_configure_list(_ffmpeg_arch_ext ARCH_EXT_LIST)
            list(APPEND _ffmpeg_expanded x86asm ${_ffmpeg_all_arch})
            list(APPEND _ffmpeg_expanded ${_ffmpeg_arch_ext})
            foreach(_ffmpeg_have IN LISTS _ffmpeg_all_have)
                if(_ffmpeg_have MATCHES "_external$" OR _ffmpeg_have MATCHES "_inline$")
                    list(APPEND _ffmpeg_expanded "${_ffmpeg_have}")
                endif()
            endforeach()
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_expanded)
    set(${_out} "${_ffmpeg_expanded}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dependency_rule_feature _out _feature)
    set(_ffmpeg_rule_feature "${_feature}")
    if(NOT DEFINED FFMPEG_NATIVE_RULE_${_ffmpeg_rule_feature}_deps AND _feature MATCHES "^(.*)_example$")
        set(_ffmpeg_base_feature "${CMAKE_MATCH_1}")
        if(DEFINED FFMPEG_NATIVE_RULE_${_ffmpeg_base_feature}_deps)
            set(_ffmpeg_rule_feature "${_ffmpeg_base_feature}")
        endif()
    endif()
    set(${_out} "${_ffmpeg_rule_feature}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_feature_is_known _out _feature)
    if(_feature IN_LIST _ffmpeg_all_config OR
       _feature IN_LIST _ffmpeg_all_components OR
       _feature IN_LIST _ffmpeg_all_have OR
       _feature IN_LIST _ffmpeg_all_arch)
        set(${_out} TRUE PARENT_SCOPE)
    else()
        set(${_out} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_ffmpeg_native_feature_is_enabled _out _feature)
    if(_feature IN_LIST _ffmpeg_enabled_config OR
       _feature IN_LIST _ffmpeg_enabled_components OR
       _feature IN_LIST _ffmpeg_enabled_have OR
       _feature IN_LIST _ffmpeg_enabled_arch)
        set(${_out} TRUE PARENT_SCOPE)
    else()
        set(${_out} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_ffmpeg_native_enable_known_feature _changed_var _feature)
    if(_feature IN_LIST _ffmpeg_disabled_features OR
       _feature IN_LIST _ffmpeg_disabled_components)
        set(_ffmpeg_enabled_config "${_ffmpeg_enabled_config}" PARENT_SCOPE)
        set(_ffmpeg_enabled_components "${_ffmpeg_enabled_components}" PARENT_SCOPE)
        set(_ffmpeg_enabled_have "${_ffmpeg_enabled_have}" PARENT_SCOPE)
        set(_ffmpeg_enabled_arch "${_ffmpeg_enabled_arch}" PARENT_SCOPE)
        return()
    endif()

    if(_feature IN_LIST _ffmpeg_all_components)
        list(FIND _ffmpeg_enabled_components "${_feature}" _ffmpeg_index)
        if(_ffmpeg_index EQUAL -1)
            list(APPEND _ffmpeg_enabled_components "${_feature}")
            set(${_changed_var} TRUE PARENT_SCOPE)
        endif()
    elseif(_feature IN_LIST _ffmpeg_all_config)
        list(FIND _ffmpeg_enabled_config "${_feature}" _ffmpeg_index)
        if(_ffmpeg_index EQUAL -1)
            list(APPEND _ffmpeg_enabled_config "${_feature}")
            set(${_changed_var} TRUE PARENT_SCOPE)
        endif()
    elseif(_feature IN_LIST _ffmpeg_all_have)
        list(FIND _ffmpeg_enabled_have "${_feature}" _ffmpeg_index)
        if(_ffmpeg_index EQUAL -1)
            list(APPEND _ffmpeg_enabled_have "${_feature}")
            set(${_changed_var} TRUE PARENT_SCOPE)
        endif()
    elseif(_feature IN_LIST _ffmpeg_all_arch)
        list(FIND _ffmpeg_enabled_arch "${_feature}" _ffmpeg_index)
        if(_ffmpeg_index EQUAL -1)
            list(APPEND _ffmpeg_enabled_arch "${_feature}")
            set(${_changed_var} TRUE PARENT_SCOPE)
        endif()
    endif()

    set(_ffmpeg_enabled_config "${_ffmpeg_enabled_config}" PARENT_SCOPE)
    set(_ffmpeg_enabled_components "${_ffmpeg_enabled_components}" PARENT_SCOPE)
    set(_ffmpeg_enabled_have "${_ffmpeg_enabled_have}" PARENT_SCOPE)
    set(_ffmpeg_enabled_arch "${_ffmpeg_enabled_arch}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_feature_missing_deps _out _feature)
    _ffmpeg_native_dependency_rule_feature(_ffmpeg_rule_feature "${_feature}")
    set(_ffmpeg_missing_deps)
    foreach(_ffmpeg_rule_kind IN ITEMS deps select)
        foreach(_ffmpeg_dep IN LISTS FFMPEG_NATIVE_RULE_${_ffmpeg_rule_feature}_${_ffmpeg_rule_kind})
            _ffmpeg_native_feature_is_known(_ffmpeg_known_dep "${_ffmpeg_dep}")
            if(_ffmpeg_known_dep)
                _ffmpeg_native_feature_is_enabled(_ffmpeg_dep_enabled "${_ffmpeg_dep}")
                if(NOT _ffmpeg_dep_enabled)
                    list(APPEND _ffmpeg_missing_deps "${_ffmpeg_dep}")
                endif()
            endif()
        endforeach()
    endforeach()
    set(${_out} "${_ffmpeg_missing_deps}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_prune_missing_deps _changed_var _enabled_var _explicit_var)
    foreach(_ffmpeg_feature IN LISTS ${_enabled_var})
        _ffmpeg_native_feature_missing_deps(_ffmpeg_missing_deps "${_ffmpeg_feature}")
        if(_ffmpeg_missing_deps AND NOT _ffmpeg_feature IN_LIST ${_explicit_var})
            list(REMOVE_ITEM ${_enabled_var} "${_ffmpeg_feature}")
            set(${_changed_var} TRUE PARENT_SCOPE)
        endif()
    endforeach()

    set(${_enabled_var} "${${_enabled_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_feature_conditions_failed _out _feature)
    set(_ffmpeg_failed FALSE)

    if(DEFINED FFMPEG_NATIVE_RULE_${_feature}_if AND FFMPEG_NATIVE_RULE_${_feature}_if)
        set(_ffmpeg_has_all TRUE)
        foreach(_ffmpeg_dep IN LISTS FFMPEG_NATIVE_RULE_${_feature}_if)
            _ffmpeg_native_feature_is_enabled(_ffmpeg_dep_enabled "${_ffmpeg_dep}")
            if(NOT _ffmpeg_dep_enabled)
                set(_ffmpeg_has_all FALSE)
                break()
            endif()
        endforeach()
        if(NOT _ffmpeg_has_all)
            set(_ffmpeg_failed TRUE)
        endif()
    endif()

    if(DEFINED FFMPEG_NATIVE_RULE_${_feature}_if_any AND FFMPEG_NATIVE_RULE_${_feature}_if_any)
        set(_ffmpeg_has_any FALSE)
        foreach(_ffmpeg_dep IN LISTS FFMPEG_NATIVE_RULE_${_feature}_if_any)
            _ffmpeg_native_feature_is_enabled(_ffmpeg_dep_enabled "${_ffmpeg_dep}")
            if(_ffmpeg_dep_enabled)
                set(_ffmpeg_has_any TRUE)
                break()
            endif()
        endforeach()
        if(NOT _ffmpeg_has_any)
            set(_ffmpeg_failed TRUE)
        endif()
    endif()

    set(${_out} "${_ffmpeg_failed}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_prune_failed_conditions _changed_var _enabled_var _explicit_var)
    foreach(_ffmpeg_feature IN LISTS ${_enabled_var})
        _ffmpeg_native_feature_conditions_failed(_ffmpeg_failed_conditions "${_ffmpeg_feature}")
        if(_ffmpeg_failed_conditions AND NOT _ffmpeg_feature IN_LIST ${_explicit_var})
            list(REMOVE_ITEM ${_enabled_var} "${_ffmpeg_feature}")
            set(${_changed_var} TRUE PARENT_SCOPE)
        endif()
    endforeach()

    set(${_enabled_var} "${${_enabled_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_validate_explicit_feature_deps)
    foreach(_ffmpeg_feature IN LISTS
            _ffmpeg_explicit_config
            _ffmpeg_explicit_components
            _ffmpeg_explicit_have
            _ffmpeg_explicit_arch)
        _ffmpeg_native_feature_missing_deps(_ffmpeg_missing_deps "${_ffmpeg_feature}")
        if(_ffmpeg_missing_deps)
            list(GET _ffmpeg_missing_deps 0 _ffmpeg_first_missing_dep)
            message(FATAL_ERROR "Native FFmpeg feature '${_ffmpeg_feature}' requires '${_ffmpeg_first_missing_dep}'. Enable it explicitly or provide a detector for it.")
        endif()
        _ffmpeg_native_feature_conditions_failed(_ffmpeg_failed_conditions "${_ffmpeg_feature}")
        if(_ffmpeg_failed_conditions)
            message(FATAL_ERROR "Native FFmpeg feature '${_ffmpeg_feature}' was requested explicitly but its configure condition is not satisfied.")
        endif()
    endforeach()
endfunction()

function(_ffmpeg_native_resolve_dependency_rules)
    foreach(_ffmpeg_unused RANGE 0 200)
        set(_ffmpeg_changed FALSE)

        foreach(_ffmpeg_feature IN LISTS
                _ffmpeg_enabled_config
                _ffmpeg_enabled_components
                _ffmpeg_enabled_have
                _ffmpeg_enabled_arch)
            foreach(_ffmpeg_selected IN LISTS FFMPEG_NATIVE_RULE_${_ffmpeg_feature}_select)
                _ffmpeg_native_enable_known_feature(_ffmpeg_changed "${_ffmpeg_selected}")
            endforeach()
        endforeach()

        foreach(_ffmpeg_feature IN LISTS FFMPEG_NATIVE_RULE_FEATURES)
            if(DEFINED FFMPEG_NATIVE_RULE_${_ffmpeg_feature}_if_any)
                set(_ffmpeg_has_any FALSE)
                foreach(_ffmpeg_dep IN LISTS FFMPEG_NATIVE_RULE_${_ffmpeg_feature}_if_any)
                    _ffmpeg_native_feature_is_enabled(_ffmpeg_dep_enabled "${_ffmpeg_dep}")
                    if(_ffmpeg_dep_enabled)
                        set(_ffmpeg_has_any TRUE)
                        break()
                    endif()
                endforeach()
                if(_ffmpeg_has_any)
                    _ffmpeg_native_enable_known_feature(_ffmpeg_changed "${_ffmpeg_feature}")
                endif()
            endif()

            if(DEFINED FFMPEG_NATIVE_RULE_${_ffmpeg_feature}_if)
                set(_ffmpeg_has_all TRUE)
                foreach(_ffmpeg_dep IN LISTS FFMPEG_NATIVE_RULE_${_ffmpeg_feature}_if)
                    _ffmpeg_native_feature_is_enabled(_ffmpeg_dep_enabled "${_ffmpeg_dep}")
                    if(NOT _ffmpeg_dep_enabled)
                        set(_ffmpeg_has_all FALSE)
                        break()
                    endif()
                endforeach()
                if(_ffmpeg_has_all)
                    _ffmpeg_native_enable_known_feature(_ffmpeg_changed "${_ffmpeg_feature}")
                endif()
            endif()
        endforeach()

        if(NOT _ffmpeg_changed)
            break()
        endif()
    endforeach()

    foreach(_ffmpeg_unused RANGE 0 200)
        set(_ffmpeg_changed FALSE)

        _ffmpeg_native_prune_missing_deps(_ffmpeg_changed _ffmpeg_enabled_config _ffmpeg_explicit_config)
        _ffmpeg_native_prune_missing_deps(_ffmpeg_changed _ffmpeg_enabled_components _ffmpeg_explicit_components)
        _ffmpeg_native_prune_missing_deps(_ffmpeg_changed _ffmpeg_enabled_have _ffmpeg_explicit_have)
        _ffmpeg_native_prune_missing_deps(_ffmpeg_changed _ffmpeg_enabled_arch _ffmpeg_explicit_arch)
        _ffmpeg_native_prune_failed_conditions(_ffmpeg_changed _ffmpeg_enabled_config _ffmpeg_explicit_config)
        _ffmpeg_native_prune_failed_conditions(_ffmpeg_changed _ffmpeg_enabled_components _ffmpeg_explicit_components)
        _ffmpeg_native_prune_failed_conditions(_ffmpeg_changed _ffmpeg_enabled_have _ffmpeg_explicit_have)
        _ffmpeg_native_prune_failed_conditions(_ffmpeg_changed _ffmpeg_enabled_arch _ffmpeg_explicit_arch)

        if(NOT _ffmpeg_changed)
            break()
        endif()
    endforeach()

    foreach(_ffmpeg_feature IN LISTS
            _ffmpeg_enabled_config
            _ffmpeg_enabled_components
            _ffmpeg_enabled_have
            _ffmpeg_enabled_arch)
        foreach(_ffmpeg_conflict IN LISTS FFMPEG_NATIVE_RULE_${_ffmpeg_feature}_conflict)
            _ffmpeg_native_feature_is_enabled(_ffmpeg_conflict_enabled "${_ffmpeg_conflict}")
            if(_ffmpeg_conflict_enabled)
                message(FATAL_ERROR "Native FFmpeg feature '${_ffmpeg_feature}' conflicts with enabled feature '${_ffmpeg_conflict}'")
            endif()
        endforeach()
    endforeach()

    _ffmpeg_native_validate_explicit_feature_deps()

    set(_ffmpeg_enabled_config "${_ffmpeg_enabled_config}" PARENT_SCOPE)
    set(_ffmpeg_enabled_components "${_ffmpeg_enabled_components}" PARENT_SCOPE)
    set(_ffmpeg_enabled_have "${_ffmpeg_enabled_have}" PARENT_SCOPE)
    set(_ffmpeg_enabled_arch "${_ffmpeg_enabled_arch}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_validate_license_gates)
    foreach(_ffmpeg_lib IN LISTS FFMPEG_ENABLE_EXTERNAL_LIBRARIES FFMPEG_ENABLE_FEATURES _ffmpeg_enabled_config)
        if(_ffmpeg_lib IN_LIST _ffmpeg_external_gpl AND NOT FFMPEG_ENABLE_GPL)
            message(FATAL_ERROR "Native FFmpeg feature '${_ffmpeg_lib}' is GPL. Enable FFMPEG_ENABLE_GPL=ON.")
        endif()
        if(_ffmpeg_lib IN_LIST _ffmpeg_external_nonfree AND NOT FFMPEG_ENABLE_NONFREE)
            message(FATAL_ERROR "Native FFmpeg feature '${_ffmpeg_lib}' is nonfree. Enable FFMPEG_ENABLE_NONFREE=ON.")
        endif()
        if(_ffmpeg_lib IN_LIST _ffmpeg_external_version3 AND NOT FFMPEG_ENABLE_VERSION3)
            message(FATAL_ERROR "Native FFmpeg feature '${_ffmpeg_lib}' requires version3. Enable FFMPEG_ENABLE_VERSION3=ON.")
        endif()
        if(_ffmpeg_lib IN_LIST _ffmpeg_external_gplv3 AND (NOT FFMPEG_ENABLE_GPL OR NOT FFMPEG_ENABLE_VERSION3))
            message(FATAL_ERROR "Native FFmpeg feature '${_ffmpeg_lib}' is GPLv3. Enable FFMPEG_ENABLE_GPL=ON and FFMPEG_ENABLE_VERSION3=ON.")
        endif()
    endforeach()
endfunction()
