include_guard(GLOBAL)

function(_ffmpeg_native_read_quoted_assignment _out _name)
    set(_ffmpeg_configure "${FFMPEG_SOURCE_DIR}/configure")
    if(NOT EXISTS "${_ffmpeg_configure}")
        message(FATAL_ERROR "Could not find FFmpeg configure script: ${_ffmpeg_configure}")
    endif()

    file(STRINGS "${_ffmpeg_configure}" _ffmpeg_lines)
    set(_ffmpeg_collecting FALSE)
    set(_ffmpeg_value)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_lines)
        if(NOT _ffmpeg_collecting)
            if(_ffmpeg_line MATCHES "^${_name}=\"(.*)$")
                set(_ffmpeg_collecting TRUE)
                set(_ffmpeg_line "${CMAKE_MATCH_1}")
            else()
                continue()
            endif()
        endif()

        if(_ffmpeg_line MATCHES "^(.*)\"[ \t]*$")
            string(APPEND _ffmpeg_value "\n${CMAKE_MATCH_1}")
            break()
        endif()
        string(APPEND _ffmpeg_value "\n${_ffmpeg_line}")
    endforeach()

    set(${_out} "${_ffmpeg_value}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_normalize_words _out _text)
    string(REGEX REPLACE "#[^\n\r]*" " " _ffmpeg_text "${_text}")
    string(REGEX REPLACE "[\r\n\t ]+" ";" _ffmpeg_words "${_ffmpeg_text}")

    set(_ffmpeg_result)
    foreach(_ffmpeg_word IN LISTS _ffmpeg_words)
        if(_ffmpeg_word STREQUAL "" OR _ffmpeg_word MATCHES "^\\$\\(" OR _ffmpeg_word MATCHES "^\\$")
            continue()
        endif()
        list(APPEND _ffmpeg_result "${_ffmpeg_word}")
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_result)
    set(${_out} "${_ffmpeg_result}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_expand_configure_list _out _name)
    _ffmpeg_native_read_quoted_assignment(_ffmpeg_raw "${_name}")
    set(_ffmpeg_text "${_ffmpeg_raw}")

    foreach(_ffmpeg_unused RANGE 0 24)
        set(_ffmpeg_changed FALSE)

        while(_ffmpeg_text MATCHES "\\$\\(add_suffix[ \t]+([^ \t\\)]+)[ \t]+\\$([A-Za-z0-9_]+)\\)")
            set(_ffmpeg_expression "${CMAKE_MATCH_0}")
            set(_ffmpeg_suffix "${CMAKE_MATCH_1}")
            set(_ffmpeg_ref "${CMAKE_MATCH_2}")
            _ffmpeg_native_expand_configure_list(_ffmpeg_ref_items "${_ffmpeg_ref}")
            set(_ffmpeg_expanded)
            foreach(_ffmpeg_item IN LISTS _ffmpeg_ref_items)
                string(APPEND _ffmpeg_expanded " ${_ffmpeg_item}${_ffmpeg_suffix}")
            endforeach()
            string(REPLACE "${_ffmpeg_expression}" "${_ffmpeg_expanded}" _ffmpeg_text "${_ffmpeg_text}")
            set(_ffmpeg_changed TRUE)
        endwhile()

        string(REGEX MATCHALL "\\$[A-Za-z0-9_]+" _ffmpeg_refs "${_ffmpeg_text}")
        if(_ffmpeg_refs)
            foreach(_ffmpeg_ref_token IN LISTS _ffmpeg_refs)
                string(SUBSTRING "${_ffmpeg_ref_token}" 1 -1 _ffmpeg_ref)
                if(_ffmpeg_ref STREQUAL "${_name}")
                    continue()
                endif()
                _ffmpeg_native_expand_configure_list(_ffmpeg_ref_items "${_ffmpeg_ref}")
                list(JOIN _ffmpeg_ref_items " " _ffmpeg_ref_text)
                string(REPLACE "${_ffmpeg_ref_token}" "${_ffmpeg_ref_text}" _ffmpeg_text "${_ffmpeg_text}")
                set(_ffmpeg_changed TRUE)
            endforeach()
        endif()

        if(NOT _ffmpeg_changed)
            break()
        endif()
    endforeach()

    _ffmpeg_native_normalize_words(_ffmpeg_result "${_ffmpeg_text}")
    set(${_out} "${_ffmpeg_result}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_load_dependency_rules)
    file(STRINGS "${FFMPEG_SOURCE_DIR}/configure" _ffmpeg_lines)

    set(_ffmpeg_collecting FALSE)
    set(_ffmpeg_name)
    set(_ffmpeg_kind)
    set(_ffmpeg_value)
    set(_ffmpeg_rule_features)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_lines)
        if(NOT _ffmpeg_collecting)
            if(_ffmpeg_line MATCHES "^([A-Za-z0-9_]+)_(deps|deps_any|select|suggest|if|if_any|conflict)=\"(.*)$")
                set(_ffmpeg_collecting TRUE)
                set(_ffmpeg_name "${CMAKE_MATCH_1}")
                set(_ffmpeg_kind "${CMAKE_MATCH_2}")
                set(_ffmpeg_line "${CMAKE_MATCH_3}")
                set(_ffmpeg_value)
            else()
                continue()
            endif()
        endif()

        if(_ffmpeg_line MATCHES "^(.*)\"[ \t]*$")
            string(APPEND _ffmpeg_value " ${CMAKE_MATCH_1}")
            _ffmpeg_native_normalize_words(_ffmpeg_items "${_ffmpeg_value}")
            set("FFMPEG_NATIVE_RULE_${_ffmpeg_name}_${_ffmpeg_kind}" "${_ffmpeg_items}")
            set("FFMPEG_NATIVE_RULE_${_ffmpeg_name}_${_ffmpeg_kind}" "${_ffmpeg_items}" PARENT_SCOPE)
            list(APPEND _ffmpeg_rule_features "${_ffmpeg_name}")
            set(_ffmpeg_collecting FALSE)
        else()
            string(APPEND _ffmpeg_value " ${_ffmpeg_line}")
        endif()
    endforeach()

    _ffmpeg_native_expand_configure_list(_ffmpeg_x86_simd ARCH_EXT_LIST_X86_SIMD)
    foreach(_ffmpeg_ext IN LISTS _ffmpeg_x86_simd)
        if(_ffmpeg_ext STREQUAL "mmx")
            continue()
        endif()

        set(_ffmpeg_external_deps)
        set(_ffmpeg_inline_deps)
        foreach(_ffmpeg_dep IN LISTS FFMPEG_NATIVE_RULE_${_ffmpeg_ext}_deps)
            list(APPEND _ffmpeg_external_deps "${_ffmpeg_dep}_external")
            list(APPEND _ffmpeg_inline_deps "${_ffmpeg_dep}_inline")
        endforeach()

        set("FFMPEG_NATIVE_RULE_${_ffmpeg_ext}_external_deps" "${_ffmpeg_external_deps}")
        set("FFMPEG_NATIVE_RULE_${_ffmpeg_ext}_inline_deps" "${_ffmpeg_inline_deps}")
        set("FFMPEG_NATIVE_RULE_${_ffmpeg_ext}_suggest" "${_ffmpeg_ext}_external;${_ffmpeg_ext}_inline")
        set("FFMPEG_NATIVE_RULE_${_ffmpeg_ext}_external_deps" "${_ffmpeg_external_deps}" PARENT_SCOPE)
        set("FFMPEG_NATIVE_RULE_${_ffmpeg_ext}_inline_deps" "${_ffmpeg_inline_deps}" PARENT_SCOPE)
        set("FFMPEG_NATIVE_RULE_${_ffmpeg_ext}_suggest" "${_ffmpeg_ext}_external;${_ffmpeg_ext}_inline" PARENT_SCOPE)
        list(APPEND _ffmpeg_rule_features "${_ffmpeg_ext}_external" "${_ffmpeg_ext}_inline")
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_rule_features)
    set(FFMPEG_NATIVE_RULE_FEATURES "${_ffmpeg_rule_features}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_to_macro_suffix _out _name)
    string(TOUPPER "${_name}" _ffmpeg_macro)
    string(REGEX REPLACE "[^A-Z0-9]" "_" _ffmpeg_macro "${_ffmpeg_macro}")
    set(${_out} "${_ffmpeg_macro}" PARENT_SCOPE)
endfunction()
