set(CMAKE_C_COMPILER clang-20 CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER clang++-20 CACHE FILEPATH "")

set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-stdlib=libc++")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-stdlib=libc++")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-stdlib=libc++")

