include_guard(GLOBAL)

if(NOT DEFINED FFMPEG_SOURCE_DIR)
    set(FFMPEG_SOURCE_DIR "${PROJECT_SOURCE_DIR}/ffmpeg" CACHE PATH "Path to the FFmpeg source tree")
endif()
set(FFMPEG_BINARY_DIR "${PROJECT_BINARY_DIR}/ffmpeg-build" CACHE PATH "Out-of-tree FFmpeg build directory")
set(FFMPEG_INSTALL_PREFIX "${PROJECT_BINARY_DIR}/ffmpeg-install" CACHE PATH "Prefix where the external FFmpeg build is installed")

option(FFMPEG_BUILD_STATIC "Build FFmpeg static libraries" ON)
option(FFMPEG_BUILD_SHARED "Build FFmpeg shared libraries" OFF)
option(FFMPEG_BUILD_PROGRAMS "Build FFmpeg command line programs" ON)
option(FFMPEG_BUILD_DOC "Build FFmpeg documentation" OFF)
option(FFMPEG_DISABLE_AUTODETECT "Pass --disable-autodetect to FFmpeg configure" OFF)
option(FFMPEG_ENABLE_GPL "Enable GPL code in FFmpeg" OFF)
option(FFMPEG_ENABLE_VERSION3 "Enable LGPL/GPL version 3 code in FFmpeg" OFF)
option(FFMPEG_ENABLE_NONFREE "Enable nonfree FFmpeg code" OFF)
option(FFMPEG_ENABLE_RPATH "Enable rpath in FFmpeg-built programs" OFF)
option(FFMPEG_PASS_CMAKE_TOOLCHAIN "Pass CMake compiler/binutils settings to FFmpeg configure" ON)

foreach(_ffmpeg_lib IN ITEMS AVCODEC AVDEVICE AVFILTER AVFORMAT AVUTIL SWRESAMPLE SWSCALE)
    option(FFMPEG_ENABLE_${_ffmpeg_lib} "Build lib${_ffmpeg_lib}" ON)
endforeach()

set(FFMPEG_CONFIGURE_OPTIONS "" CACHE STRING "Extra raw options passed to FFmpeg configure")
set(FFMPEG_ENABLE_FEATURES "" CACHE STRING "Semicolon-separated configure features passed as --enable-<feature>")
set(FFMPEG_DISABLE_FEATURES "" CACHE STRING "Semicolon-separated configure features passed as --disable-<feature>")
set(FFMPEG_ENABLE_EXTERNAL_LIBRARIES "" CACHE STRING "Semicolon-separated external libraries passed as --enable-<name>")
set(FFMPEG_DISABLE_EXTERNAL_LIBRARIES "" CACHE STRING "Semicolon-separated external libraries passed as --disable-<name>")

foreach(_ffmpeg_kind IN ITEMS ENCODERS DECODERS HWACCELS MUXERS DEMUXERS PARSERS BSFS PROTOCOLS INDEVS OUTDEVS FILTERS)
    string(TOLOWER "${_ffmpeg_kind}" _ffmpeg_kind_lc)
    set(FFMPEG_ENABLE_${_ffmpeg_kind} "" CACHE STRING "Semicolon-separated ${_ffmpeg_kind_lc} to enable with FFmpeg configure")
    set(FFMPEG_DISABLE_${_ffmpeg_kind} "" CACHE STRING "Semicolon-separated ${_ffmpeg_kind_lc} to disable with FFmpeg configure")
endforeach()

set(FFMPEG_TARGET_OS "" CACHE STRING "FFmpeg --target-os value")
set(FFMPEG_ARCH "" CACHE STRING "FFmpeg --arch value")
set(FFMPEG_CPU "" CACHE STRING "FFmpeg --cpu value")
set(FFMPEG_TOOLCHAIN "" CACHE STRING "FFmpeg --toolchain value")
set(FFMPEG_CROSS_PREFIX "" CACHE STRING "FFmpeg --cross-prefix value")
set(FFMPEG_SYSROOT "" CACHE PATH "FFmpeg --sysroot value")

set(FFMPEG_CC "" CACHE FILEPATH "Compiler passed as FFmpeg --cc")
set(FFMPEG_CXX "" CACHE FILEPATH "Compiler passed as FFmpeg --cxx")
set(FFMPEG_AR "" CACHE FILEPATH "Archiver passed as FFmpeg --ar")
set(FFMPEG_AS "" CACHE FILEPATH "Assembler passed as FFmpeg --as")
set(FFMPEG_X86ASM "" CACHE FILEPATH "nasm-compatible x86 assembler passed as FFmpeg --x86asmexe")
set(FFMPEG_LD "" CACHE FILEPATH "Linker passed as FFmpeg --ld")
set(FFMPEG_NM "" CACHE FILEPATH "nm passed as FFmpeg --nm")
set(FFMPEG_RANLIB "" CACHE FILEPATH "ranlib passed as FFmpeg --ranlib")
set(FFMPEG_STRIP "" CACHE FILEPATH "strip passed as FFmpeg --strip")
set(FFMPEG_PKG_CONFIG "" CACHE FILEPATH "pkg-config executable passed as FFmpeg --pkg-config")

set(FFMPEG_EXTRA_CFLAGS "" CACHE STRING "Value passed to FFmpeg --extra-cflags")
set(FFMPEG_EXTRA_CXXFLAGS "" CACHE STRING "Value passed to FFmpeg --extra-cxxflags")
set(FFMPEG_EXTRA_LDFLAGS "" CACHE STRING "Value passed to FFmpeg --extra-ldflags")
set(FFMPEG_EXTRA_LIBS "" CACHE STRING "Value passed to FFmpeg --extra-libs")

function(_ffmpeg_append_switch _out _enabled _enable_arg _disable_arg)
    if(${_enabled})
        list(APPEND ${_out} "${_enable_arg}")
    else()
        list(APPEND ${_out} "${_disable_arg}")
    endif()
    set(${_out} "${${_out}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_append_name_options _out _prefix _names)
    foreach(_ffmpeg_name IN LISTS ${_names})
        if(NOT _ffmpeg_name STREQUAL "")
            list(APPEND ${_out} "${_prefix}${_ffmpeg_name}")
        endif()
    endforeach()
    set(${_out} "${${_out}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_append_component_options _out _option_name _configure_name)
    foreach(_ffmpeg_name IN LISTS FFMPEG_ENABLE_${_option_name})
        if(NOT _ffmpeg_name STREQUAL "")
            list(APPEND ${_out} "--enable-${_configure_name}=${_ffmpeg_name}")
        endif()
    endforeach()
    foreach(_ffmpeg_name IN LISTS FFMPEG_DISABLE_${_option_name})
        if(NOT _ffmpeg_name STREQUAL "")
            list(APPEND ${_out} "--disable-${_configure_name}=${_ffmpeg_name}")
        endif()
    endforeach()
    set(${_out} "${${_out}}" PARENT_SCOPE)
endfunction()

function(ffmpeg_resolve_assembler_tools)
    if(NOT FFMPEG_X86ASM)
        find_program(_ffmpeg_x86asm_exe NAMES nasm NO_CACHE)
        if(_ffmpeg_x86asm_exe)
            set(FFMPEG_X86ASM "${_ffmpeg_x86asm_exe}" CACHE FILEPATH "nasm-compatible x86 assembler passed as FFmpeg --x86asmexe" FORCE)
        endif()
    endif()
endfunction()

function(ffmpeg_compose_configure_options _out)
    if(NOT FFMPEG_BUILD_STATIC AND NOT FFMPEG_BUILD_SHARED)
        message(FATAL_ERROR "At least one of FFMPEG_BUILD_STATIC or FFMPEG_BUILD_SHARED must be enabled")
    endif()

    file(TO_CMAKE_PATH "${FFMPEG_INSTALL_PREFIX}" _ffmpeg_prefix)
    set(_ffmpeg_args
        "--prefix=${_ffmpeg_prefix}"
        "--pkgconfigdir=${_ffmpeg_prefix}/${CMAKE_INSTALL_LIBDIR}/pkgconfig")

    _ffmpeg_append_switch(_ffmpeg_args FFMPEG_BUILD_STATIC "--enable-static" "--disable-static")
    _ffmpeg_append_switch(_ffmpeg_args FFMPEG_BUILD_SHARED "--enable-shared" "--disable-shared")

    if(NOT FFMPEG_BUILD_PROGRAMS)
        list(APPEND _ffmpeg_args "--disable-programs")
    endif()
    if(NOT FFMPEG_BUILD_DOC)
        list(APPEND _ffmpeg_args "--disable-doc")
    endif()
    if(FFMPEG_DISABLE_AUTODETECT)
        list(APPEND _ffmpeg_args "--disable-autodetect")
    endif()
    if(FFMPEG_ENABLE_GPL)
        list(APPEND _ffmpeg_args "--enable-gpl")
    endif()
    if(FFMPEG_ENABLE_VERSION3)
        list(APPEND _ffmpeg_args "--enable-version3")
    endif()
    if(FFMPEG_ENABLE_NONFREE)
        list(APPEND _ffmpeg_args "--enable-nonfree")
    endif()
    if(FFMPEG_ENABLE_RPATH)
        list(APPEND _ffmpeg_args "--enable-rpath")
    endif()

    foreach(_ffmpeg_lib IN ITEMS AVCODEC AVDEVICE AVFILTER AVFORMAT AVUTIL SWRESAMPLE SWSCALE)
        string(TOLOWER "${_ffmpeg_lib}" _ffmpeg_lib_lc)
        if(NOT FFMPEG_ENABLE_${_ffmpeg_lib})
            list(APPEND _ffmpeg_args "--disable-${_ffmpeg_lib_lc}")
        endif()
    endforeach()

    _ffmpeg_append_name_options(_ffmpeg_args "--enable-" FFMPEG_ENABLE_FEATURES)
    _ffmpeg_append_name_options(_ffmpeg_args "--disable-" FFMPEG_DISABLE_FEATURES)
    _ffmpeg_append_name_options(_ffmpeg_args "--enable-" FFMPEG_ENABLE_EXTERNAL_LIBRARIES)
    _ffmpeg_append_name_options(_ffmpeg_args "--disable-" FFMPEG_DISABLE_EXTERNAL_LIBRARIES)

    _ffmpeg_append_component_options(_ffmpeg_args ENCODERS encoder)
    _ffmpeg_append_component_options(_ffmpeg_args DECODERS decoder)
    _ffmpeg_append_component_options(_ffmpeg_args HWACCELS hwaccel)
    _ffmpeg_append_component_options(_ffmpeg_args MUXERS muxer)
    _ffmpeg_append_component_options(_ffmpeg_args DEMUXERS demuxer)
    _ffmpeg_append_component_options(_ffmpeg_args PARSERS parser)
    _ffmpeg_append_component_options(_ffmpeg_args BSFS bsf)
    _ffmpeg_append_component_options(_ffmpeg_args PROTOCOLS protocol)
    _ffmpeg_append_component_options(_ffmpeg_args INDEVS indev)
    _ffmpeg_append_component_options(_ffmpeg_args OUTDEVS outdev)
    _ffmpeg_append_component_options(_ffmpeg_args FILTERS filter)

    set(_ffmpeg_config_vars TARGET_OS ARCH CPU TOOLCHAIN CROSS_PREFIX SYSROOT)
    set(_ffmpeg_config_args target-os arch cpu toolchain cross-prefix sysroot)
    foreach(_ffmpeg_var _ffmpeg_arg IN ZIP_LISTS _ffmpeg_config_vars _ffmpeg_config_args)
        if(FFMPEG_${_ffmpeg_var})
            list(APPEND _ffmpeg_args "--${_ffmpeg_arg}=${FFMPEG_${_ffmpeg_var}}")
        endif()
    endforeach()

    set(_ffmpeg_tool_CC "${FFMPEG_CC}")
    set(_ffmpeg_tool_CXX "${FFMPEG_CXX}")
    set(_ffmpeg_tool_AR "${FFMPEG_AR}")
    set(_ffmpeg_tool_AS "${FFMPEG_AS}")
    set(_ffmpeg_tool_LD "${FFMPEG_LD}")
    set(_ffmpeg_tool_NM "${FFMPEG_NM}")
    set(_ffmpeg_tool_RANLIB "${FFMPEG_RANLIB}")
    set(_ffmpeg_tool_STRIP "${FFMPEG_STRIP}")

    if(FFMPEG_PASS_CMAKE_TOOLCHAIN)
        set(_ffmpeg_tools CC CXX AR AS NM RANLIB STRIP)
        set(_ffmpeg_cmake_vars
            CMAKE_C_COMPILER
            CMAKE_CXX_COMPILER
            CMAKE_AR
            CMAKE_ASM_COMPILER
            CMAKE_NM
            CMAKE_RANLIB
            CMAKE_STRIP)
        foreach(_ffmpeg_tool _ffmpeg_cmake_var IN ZIP_LISTS _ffmpeg_tools _ffmpeg_cmake_vars)
            set(_ffmpeg_current_tool "${_ffmpeg_tool_${_ffmpeg_tool}}")
            if(NOT _ffmpeg_current_tool AND DEFINED ${_ffmpeg_cmake_var} AND NOT "${${_ffmpeg_cmake_var}}" STREQUAL "")
                set(_ffmpeg_tool_${_ffmpeg_tool} "${${_ffmpeg_cmake_var}}")
            endif()
        endforeach()
    endif()

    if(NOT FFMPEG_PKG_CONFIG)
        find_program(_ffmpeg_pkg_config_exe NAMES pkg-config)
        if(_ffmpeg_pkg_config_exe)
            set(FFMPEG_PKG_CONFIG "${_ffmpeg_pkg_config_exe}" CACHE FILEPATH "pkg-config executable passed as FFmpeg --pkg-config" FORCE)
        endif()
    endif()

    set(_ffmpeg_tools CC CXX AR AS LD NM RANLIB STRIP)
    set(_ffmpeg_tool_args cc cxx ar as ld nm ranlib strip)
    foreach(_ffmpeg_tool _ffmpeg_arg IN ZIP_LISTS _ffmpeg_tools _ffmpeg_tool_args)
        if(_ffmpeg_tool_${_ffmpeg_tool})
            list(APPEND _ffmpeg_args "--${_ffmpeg_arg}=${_ffmpeg_tool_${_ffmpeg_tool}}")
        endif()
    endforeach()

    if(FFMPEG_PKG_CONFIG)
        list(APPEND _ffmpeg_args "--pkg-config=${FFMPEG_PKG_CONFIG}")
    endif()
    if(FFMPEG_X86ASM)
        list(APPEND _ffmpeg_args "--x86asmexe=${FFMPEG_X86ASM}")
    endif()

    set(_ffmpeg_extra_vars EXTRA_CFLAGS EXTRA_CXXFLAGS EXTRA_LDFLAGS EXTRA_LIBS)
    set(_ffmpeg_extra_args extra-cflags extra-cxxflags extra-ldflags extra-libs)
    foreach(_ffmpeg_var _ffmpeg_arg IN ZIP_LISTS _ffmpeg_extra_vars _ffmpeg_extra_args)
        if(FFMPEG_${_ffmpeg_var})
            list(APPEND _ffmpeg_args "--${_ffmpeg_arg}=${FFMPEG_${_ffmpeg_var}}")
        endif()
    endforeach()

    if(FFMPEG_CONFIGURE_OPTIONS)
        separate_arguments(_ffmpeg_raw_options NATIVE_COMMAND "${FFMPEG_CONFIGURE_OPTIONS}")
        list(APPEND _ffmpeg_args ${_ffmpeg_raw_options})
    endif()

    set(${_out} "${_ffmpeg_args}" PARENT_SCOPE)
endfunction()
