include_guard(GLOBAL)

function(ffmpeg_enable_ide_folders)
    set_property(GLOBAL PROPERTY USE_FOLDERS ON)
    set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMake/Targets")
endfunction()

function(ffmpeg_set_target_folder _target _folder)
    if(TARGET "${_target}")
        set_target_properties("${_target}" PROPERTIES FOLDER "${_folder}")
    endif()
endfunction()

function(ffmpeg_cache_common_cmake_options)
    if(NOT DEFINED CMAKE_PREFIX_PATH)
        set(CMAKE_PREFIX_PATH "" CACHE STRING "Semicolon-separated prefixes searched by find_package and FFmpeg dependency discovery")
    else()
        set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" CACHE STRING "Semicolon-separated prefixes searched by find_package and FFmpeg dependency discovery")
    endif()

    if(NOT DEFINED CMAKE_POSITION_INDEPENDENT_CODE)
        set(CMAKE_POSITION_INDEPENDENT_CODE OFF CACHE BOOL "Build position-independent code where supported")
    else()
        set(CMAKE_POSITION_INDEPENDENT_CODE "${CMAKE_POSITION_INDEPENDENT_CODE}" CACHE BOOL "Build position-independent code where supported")
    endif()

    if(WIN32)
        if(NOT DEFINED CMAKE_DEBUG_POSTFIX)
            set(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Postfix appended to debug build artifacts")
        else()
            set(CMAKE_DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}" CACHE STRING "Postfix appended to debug build artifacts")
        endif()
    endif()
endfunction()

function(ffmpeg_apply_msvc_runtime_default)
    if(NOT MSVC)
        return()
    endif()

    if(DEFINED CMAKE_MSVC_RUNTIME_LIBRARY)
        set(CMAKE_MSVC_RUNTIME_LIBRARY "${CMAKE_MSVC_RUNTIME_LIBRARY}" CACHE STRING "MSVC runtime library used by CMake targets")
        return()
    endif()

    set(_ffmpeg_static_runtime FALSE)
    if(FFMPEG_BUILD_FROM_SOURCE AND FFMPEG_BUILD_STATIC AND NOT FFMPEG_BUILD_SHARED)
        set(_ffmpeg_static_runtime TRUE)
    endif()
    if(FFMPEG_FIND_INSTALLED AND FFmpeg_USE_STATIC_LIBS)
        set(_ffmpeg_static_runtime TRUE)
    endif()

    if(_ffmpeg_static_runtime)
        set(_ffmpeg_msvc_runtime "$<$<CONFIG:Debug>:MultiThreadedDebug>$<$<CONFIG:Release>:MultiThreaded>")
    else()
        set(_ffmpeg_msvc_runtime "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
    endif()

    set(CMAKE_MSVC_RUNTIME_LIBRARY "${_ffmpeg_msvc_runtime}" CACHE STRING "MSVC runtime library used by CMake targets")
endfunction()
