include_guard(GLOBAL)

set(FFMPEG_REPORT_MAX_LINE_LENGTH 112 CACHE STRING "Maximum line length used by the configure-time FFmpeg report before wrapping lists.")

function(_ffmpeg_report_heading _label)
    message(STATUS "")
    message(STATUS "  ${_label}:")
endfunction()

function(_ffmpeg_report_value_at _indent _label _value)
    if("${_value}" STREQUAL "")
        set(_value "none")
    endif()
    message(STATUS "${_indent}${_label}: ${_value}")
endfunction()

function(_ffmpeg_report_value _label _value)
    _ffmpeg_report_value_at("  " "${_label}" "${_value}")
endfunction()

function(_ffmpeg_report_list_at _indent _label _values)
    set(_ffmpeg_values)
    foreach(_ffmpeg_item IN LISTS _values)
        string(STRIP "${_ffmpeg_item}" _ffmpeg_item)
        string(REGEX REPLACE "^[,;]+[ \t]*" "" _ffmpeg_item "${_ffmpeg_item}")
        if(NOT "${_ffmpeg_item}" STREQUAL "")
            list(APPEND _ffmpeg_values "${_ffmpeg_item}")
        endif()
    endforeach()

    if(NOT _ffmpeg_values)
        message(STATUS "${_indent}${_label}: none")
        return()
    endif()

    string(REPLACE ";" ", " _ffmpeg_text "${_ffmpeg_values}")
    string(LENGTH "${_indent}${_label}: ${_ffmpeg_text}" _ffmpeg_one_line_length)
    if(_ffmpeg_one_line_length LESS_EQUAL FFMPEG_REPORT_MAX_LINE_LENGTH)
        message(STATUS "${_indent}${_label}: ${_ffmpeg_text}")
        return()
    endif()

    message(STATUS "${_indent}${_label}:")

    set(_ffmpeg_line)
    foreach(_ffmpeg_item IN LISTS _ffmpeg_values)
        if("${_ffmpeg_line}" STREQUAL "")
            set(_ffmpeg_candidate "${_ffmpeg_item}")
        else()
            set(_ffmpeg_candidate "${_ffmpeg_line}, ${_ffmpeg_item}")
        endif()

        string(LENGTH "${_indent}  ${_ffmpeg_candidate}" _ffmpeg_candidate_length)
        if(_ffmpeg_candidate_length GREATER FFMPEG_REPORT_MAX_LINE_LENGTH AND NOT "${_ffmpeg_line}" STREQUAL "")
            message(STATUS "${_indent}  ${_ffmpeg_line}")
            set(_ffmpeg_line "${_ffmpeg_item}")
        else()
            set(_ffmpeg_line "${_ffmpeg_candidate}")
        endif()
    endforeach()

    if(NOT "${_ffmpeg_line}" STREQUAL "")
        message(STATUS "${_indent}  ${_ffmpeg_line}")
    endif()
endfunction()

function(_ffmpeg_report_list _label _values)
    _ffmpeg_report_list_at("  " "${_label}" "${_values}")
endfunction()

function(_ffmpeg_report_bool_at _indent _label _value)
    if(${_value})
        message(STATUS "${_indent}${_label}: yes")
    else()
        message(STATUS "${_indent}${_label}: no")
    endif()
endfunction()

function(_ffmpeg_report_bool _label _value)
    _ffmpeg_report_bool_at("  " "${_label}" "${_value}")
endfunction()

function(_ffmpeg_report_append_components _out _var _suffix)
    foreach(_ffmpeg_name IN LISTS ${_var})
        if(NOT _ffmpeg_name STREQUAL "")
            if(_ffmpeg_name MATCHES "_${_suffix}$")
                list(APPEND ${_out} "${_ffmpeg_name}")
            else()
                list(APPEND ${_out} "${_ffmpeg_name}_${_suffix}")
            endif()
        endif()
    endforeach()
    set(${_out} "${${_out}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_report_requested_features _out)
    set(_ffmpeg_requested ${FFMPEG_ENABLE_FEATURES} ${FFMPEG_ENABLE_EXTERNAL_LIBRARIES})
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_ENCODERS encoder)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_DECODERS decoder)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_HWACCELS hwaccel)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_MUXERS muxer)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_DEMUXERS demuxer)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_PARSERS parser)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_BSFS bsf)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_PROTOCOLS protocol)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_INDEVS indev)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_OUTDEVS outdev)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_FILTERS filter)
    list(REMOVE_DUPLICATES _ffmpeg_requested)
    list(SORT _ffmpeg_requested)
    set(${_out} "${_ffmpeg_requested}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_report_disabled_features _out)
    set(_ffmpeg_disabled ${FFMPEG_DISABLE_FEATURES} ${FFMPEG_DISABLE_EXTERNAL_LIBRARIES})
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_ENCODERS encoder)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_DECODERS decoder)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_HWACCELS hwaccel)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_MUXERS muxer)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_DEMUXERS demuxer)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_PARSERS parser)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_BSFS bsf)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_PROTOCOLS protocol)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_INDEVS indev)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_OUTDEVS outdev)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_FILTERS filter)
    list(REMOVE_DUPLICATES _ffmpeg_disabled)
    list(SORT _ffmpeg_disabled)
    set(${_out} "${_ffmpeg_disabled}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_report_build_libraries _out_enabled _out_disabled)
    set(_ffmpeg_enabled)
    set(_ffmpeg_disabled)
    foreach(_ffmpeg_lib IN ITEMS AVCODEC AVDEVICE AVFILTER AVFORMAT AVUTIL SWRESAMPLE SWSCALE)
        string(TOLOWER "${_ffmpeg_lib}" _ffmpeg_lib_lc)
        if(FFMPEG_ENABLE_${_ffmpeg_lib})
            list(APPEND _ffmpeg_enabled "${_ffmpeg_lib_lc}")
        else()
            list(APPEND _ffmpeg_disabled "${_ffmpeg_lib_lc}")
        endif()
    endforeach()
    set(${_out_enabled} "${_ffmpeg_enabled}" PARENT_SCOPE)
    set(${_out_disabled} "${_ffmpeg_disabled}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_report_installed_import)
    if(NOT FFMPEG_FIND_INSTALLED)
        return()
    endif()

    set(_ffmpeg_missing)
    foreach(_ffmpeg_component IN LISTS FFMPEG_IMPORT_COMPONENTS)
        if(NOT FFmpeg_${_ffmpeg_component}_FOUND)
            list(APPEND _ffmpeg_missing "${_ffmpeg_component}")
        endif()
    endforeach()

    message(STATUS "")
    message(STATUS " Installed FFmpeg import:")
    _ffmpeg_report_bool_at("    " "Use static pkg-config closure" "${FFmpeg_USE_STATIC_LIBS}")
    _ffmpeg_report_value_at("    " "FFmpeg root" "${FFmpeg_ROOT}")
    _ffmpeg_report_value_at("    " "Version" "${FFmpeg_VERSION}")
    _ffmpeg_report_list_at("    " "Found components" "${FFmpeg_COMPONENTS}")
    _ffmpeg_report_list_at("    " "Missing components" "${_ffmpeg_missing}")
    _ffmpeg_report_list_at("    " "Imported targets" "${FFmpeg_TARGETS}")
endfunction()

function(_ffmpeg_report_source_build)
    if(NOT FFMPEG_BUILD_FROM_SOURCE)
        return()
    endif()

    _ffmpeg_report_build_libraries(_ffmpeg_enabled_libraries _ffmpeg_disabled_libraries)
    _ffmpeg_report_requested_features(_ffmpeg_requested_features)
    _ffmpeg_report_disabled_features(_ffmpeg_disabled_features)
    if(FFMPEG_EFFECTIVE_BUILD_BACKEND STREQUAL "NATIVE_CMAKE" AND FFMPEG_NATIVE_COMPONENTS)
        set(_ffmpeg_enabled_libraries "${FFMPEG_NATIVE_COMPONENTS}")
        set(_ffmpeg_disabled_libraries)
        foreach(_ffmpeg_component IN LISTS FFMPEG_IMPORT_COMPONENTS)
            if(NOT _ffmpeg_component IN_LIST _ffmpeg_enabled_libraries)
                list(APPEND _ffmpeg_disabled_libraries "${_ffmpeg_component}")
            endif()
        endforeach()
    endif()

    message(STATUS "")
    message(STATUS " Source FFmpeg build:")
    _ffmpeg_report_heading("Paths")
    _ffmpeg_report_value_at("    " "Source directory" "${FFMPEG_SOURCE_DIR}")
    _ffmpeg_report_value_at("    " "Backend" "${FFMPEG_EFFECTIVE_BUILD_BACKEND}")
    _ffmpeg_report_value_at("    " "Install prefix" "${FFMPEG_INSTALL_PREFIX}")
    if(FFMPEG_NV_CODEC_HEADERS_FOUND)
        _ffmpeg_report_value_at("    " "nv-codec-headers" "${FFMPEG_NV_CODEC_HEADERS_INCLUDE_DIR} (${FFMPEG_NV_CODEC_HEADERS_ORIGIN})")
    else()
        _ffmpeg_report_value_at("    " "nv-codec-headers" "not found")
    endif()
    if(FFMPEG_AMF_HEADERS_FOUND)
        set(_ffmpeg_amf_report "${FFMPEG_AMF_HEADERS_INCLUDE_DIR} (${FFMPEG_AMF_HEADERS_ORIGIN}")
        if(FFMPEG_AMF_HEADERS_VERSION)
            string(APPEND _ffmpeg_amf_report "; version ${FFMPEG_AMF_HEADERS_VERSION}")
        endif()
        if(NOT FFMPEG_AMF_HEADERS_USABLE)
            string(APPEND _ffmpeg_amf_report "; requires >= 1.5.0.0")
        endif()
        string(APPEND _ffmpeg_amf_report ")")
        _ffmpeg_report_value_at("    " "AMD AMF headers" "${_ffmpeg_amf_report}")
    else()
        _ffmpeg_report_value_at("    " "AMD AMF headers" "not found")
    endif()

    _ffmpeg_report_heading("Build switches")
    _ffmpeg_report_bool_at("    " "Static libraries" "${FFMPEG_BUILD_STATIC}")
    _ffmpeg_report_bool_at("    " "Shared libraries" "${FFMPEG_BUILD_SHARED}")
    _ffmpeg_report_bool_at("    " "Programs" "${FFMPEG_BUILD_PROGRAMS}")
    _ffmpeg_report_bool_at("    " "Documentation" "${FFMPEG_BUILD_DOC}")
    set(_ffmpeg_autodetect ON)
    if(FFMPEG_DISABLE_AUTODETECT)
        set(_ffmpeg_autodetect OFF)
    endif()
    _ffmpeg_report_bool_at("    " "Autodetect" "${_ffmpeg_autodetect}")

    _ffmpeg_report_heading("Libraries")
    _ffmpeg_report_list_at("    " "Enabled" "${_ffmpeg_enabled_libraries}")
    _ffmpeg_report_list_at("    " "Disabled" "${_ffmpeg_disabled_libraries}")

    _ffmpeg_report_heading("License")
    _ffmpeg_report_bool_at("    " "GPL" "${FFMPEG_ENABLE_GPL}")
    _ffmpeg_report_bool_at("    " "Version3" "${FFMPEG_ENABLE_VERSION3}")
    _ffmpeg_report_bool_at("    " "Nonfree" "${FFMPEG_ENABLE_NONFREE}")

    _ffmpeg_report_heading("User-requested options")
    _ffmpeg_report_list_at("    " "Feature enables" "${_ffmpeg_requested_features}")
    _ffmpeg_report_list_at("    " "Feature disables" "${_ffmpeg_disabled_features}")

    _ffmpeg_report_heading("Tool overrides")
    _ffmpeg_report_value_at("    " "Assembler (--as)" "${FFMPEG_AS}")
    _ffmpeg_report_value_at("    " "x86 assembler (--x86asmexe)" "${FFMPEG_X86ASM}")

    if(FFMPEG_EFFECTIVE_BUILD_BACKEND STREQUAL "OFFICIAL_CONFIGURE")
        _ffmpeg_report_heading("Official configure backend")
        _ffmpeg_report_value_at("    " "Configure shell" "${FFMPEG_CONFIGURE_SHELL}")
        _ffmpeg_report_value_at("    " "Make program" "${FFMPEG_MAKE_PROGRAM}")
        _ffmpeg_report_list_at("    " "Configure options" "${FFMPEG_OFFICIAL_CONFIGURE_OPTIONS}")
        _ffmpeg_report_value_at("    " "Not-found dependencies" "resolved by FFmpeg configure during the external configure step")
    elseif(FFMPEG_EFFECTIVE_BUILD_BACKEND STREQUAL "NATIVE_CMAKE")
        _ffmpeg_report_heading("Native backend")
        _ffmpeg_report_value_at("    " "License" "${FFMPEG_NATIVE_LICENSE}")
        _ffmpeg_report_list_at("    " "Components" "${FFMPEG_NATIVE_COMPONENTS}")
        _ffmpeg_report_list_at("    " "Programs" "${FFMPEG_NATIVE_PROGRAMS}")
        _ffmpeg_report_list_at("    " "Examples" "${FFMPEG_NATIVE_EXAMPLES}")
        _ffmpeg_report_list_at("    " "Smoke tests" "${FFMPEG_NATIVE_SMOKE_TESTS}")
        _ffmpeg_report_bool_at("    " "x86 transform assembly" "${FFMPEG_NATIVE_EFFECTIVE_ENABLE_X86_TX_ASM}")
        _ffmpeg_report_value_at("    " "Coverage report" "${FFMPEG_NATIVE_COVERAGE_FILE}")
        _ffmpeg_report_list_at("    " "Coverage summary" "${FFMPEG_NATIVE_COVERAGE_SUMMARY}")

        _ffmpeg_report_heading("Native feature model")
        _ffmpeg_report_list_at("    " "Enabled config features" "${FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES}")
        _ffmpeg_report_list_at("    " "Enabled component features" "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}")
        _ffmpeg_report_list_at("    " "Enabled arch features" "${FFMPEG_NATIVE_ENABLED_ARCH_FEATURES}")
        _ffmpeg_report_list_at("    " "Enabled HAVE features" "${FFMPEG_NATIVE_ENABLED_HAVE_FEATURES}")

        _ffmpeg_report_heading("Native hardware acceleration")
        _ffmpeg_report_list_at("    " "Enabled hardware features" "${FFMPEG_NATIVE_HARDWARE_ENABLED_FEATURES}")
        _ffmpeg_report_value_at("    " "QSV backend" "${FFMPEG_NATIVE_QSV_BACKEND}")
        _ffmpeg_report_value_at("    " "QSV backend note" "${FFMPEG_NATIVE_QSV_BACKEND_NOTE}")
        list(LENGTH FFMPEG_NATIVE_HARDWARE_DISABLED_FEATURES _ffmpeg_disabled_hw_count)
        _ffmpeg_report_value_at("    " "Disabled hardware features" "${_ffmpeg_disabled_hw_count} (see coverage report)")

        _ffmpeg_report_heading("Native dependencies")
        _ffmpeg_report_list_at("    " "Found external deps" "${FFMPEG_NATIVE_FOUND_EXTERNAL_DEPENDENCIES}")
        _ffmpeg_report_list_at("    " "Missing external deps" "${FFMPEG_NATIVE_MISSING_EXTERNAL_DEPENDENCIES}")
        _ffmpeg_report_list_at("    " "Dependency targets" "${FFMPEG_NATIVE_DEPENDENCY_TARGETS}")
        _ffmpeg_report_value_at("    " "Dependency audit" "${FFMPEG_NATIVE_DEPENDENCY_AUDIT_FILE}")
        _ffmpeg_report_list_at("    " "Dependency audit summary" "${FFMPEG_NATIVE_DEPENDENCY_AUDIT_SUMMARY}")
        _ffmpeg_report_list_at("    " "Dependency audit warnings" "${FFMPEG_NATIVE_DEPENDENCY_AUDIT_WARNINGS}")
    endif()
endfunction()

function(ffmpeg_print_report)
    message(STATUS "")
    message(STATUS "=========================================================================")
    message(STATUS "= FFmpeg CMake report                                                   =")
    message(STATUS "=========================================================================")
    message(STATUS "")
    message(STATUS " General:")
    _ffmpeg_report_value("CMake version" "${CMAKE_VERSION}")
    _ffmpeg_report_value("System" "${CMAKE_SYSTEM_NAME}")
    _ffmpeg_report_value("Generator" "${CMAKE_GENERATOR}")
    _ffmpeg_report_value("Build type" "${CMAKE_BUILD_TYPE}")
    _ffmpeg_report_list("Configuration types" "${CMAKE_CONFIGURATION_TYPES}")
    _ffmpeg_report_value("C compiler" "${CMAKE_C_COMPILER}")
    _ffmpeg_report_value("C standard" "${CMAKE_C_STANDARD}")
    _ffmpeg_report_value("C++ standard" "${CMAKE_CXX_STANDARD}")
    _ffmpeg_report_list("CMAKE_PREFIX_PATH" "${CMAKE_PREFIX_PATH}")
    _ffmpeg_report_bool("CMAKE_POSITION_INDEPENDENT_CODE" "${CMAKE_POSITION_INDEPENDENT_CODE}")
    if(WIN32)
        _ffmpeg_report_value("CMAKE_DEBUG_POSTFIX" "${CMAKE_DEBUG_POSTFIX}")
    endif()
    if(MSVC)
        _ffmpeg_report_value("CMAKE_MSVC_RUNTIME_LIBRARY" "${CMAKE_MSVC_RUNTIME_LIBRARY}")
    endif()

    _ffmpeg_report_installed_import()
    _ffmpeg_report_source_build()

    message(STATUS "")
    message(STATUS "=========================================================================")
    message(STATUS "")
endfunction()
