include_guard(GLOBAL)

include(CheckIncludeFile)
include(FFmpegPkgConfigTargets)

option(FFMPEG_NATIVE_REQUIRE_EXTERNAL_DEPENDENCIES "Stop configure when a requested native FFmpeg dependency cannot be found or imported." ON)

function(_ffmpeg_native_dep_prefix_include_dirs _out)
    set(_ffmpeg_dirs)
    if(FFMPEG_NV_CODEC_HEADERS_INCLUDE_DIR AND IS_DIRECTORY "${FFMPEG_NV_CODEC_HEADERS_INCLUDE_DIR}")
        list(APPEND _ffmpeg_dirs "${FFMPEG_NV_CODEC_HEADERS_INCLUDE_DIR}")
    endif()
    if(FFMPEG_AMF_HEADERS_INCLUDE_DIR AND IS_DIRECTORY "${FFMPEG_AMF_HEADERS_INCLUDE_DIR}")
        list(APPEND _ffmpeg_dirs "${FFMPEG_AMF_HEADERS_INCLUDE_DIR}")
    endif()
    foreach(_ffmpeg_prefix IN LISTS CMAKE_PREFIX_PATH)
        if(_ffmpeg_prefix STREQUAL "")
            continue()
        endif()
        foreach(_ffmpeg_suffix IN ITEMS
                include
                include/vpl
                include/mfx
                include/fribidi
                include/harfbuzz
                include/freetype2
                include/openjpeg-2.5
                include/openjpeg-2.4)
            if(IS_DIRECTORY "${_ffmpeg_prefix}/${_ffmpeg_suffix}")
                list(APPEND _ffmpeg_dirs "${_ffmpeg_prefix}/${_ffmpeg_suffix}")
            endif()
        endforeach()
    endforeach()
    foreach(_ffmpeg_dir IN LISTS CMAKE_INCLUDE_PATH)
        if(IS_DIRECTORY "${_ffmpeg_dir}")
            list(APPEND _ffmpeg_dirs "${_ffmpeg_dir}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_dirs)
    set(${_out} "${_ffmpeg_dirs}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_library_dirs _out)
    set(_ffmpeg_dirs)
    foreach(_ffmpeg_prefix IN LISTS CMAKE_PREFIX_PATH)
        if(_ffmpeg_prefix STREQUAL "")
            continue()
        endif()
        foreach(_ffmpeg_suffix IN ITEMS lib lib64 bin)
            if(IS_DIRECTORY "${_ffmpeg_prefix}/${_ffmpeg_suffix}")
                list(APPEND _ffmpeg_dirs "${_ffmpeg_prefix}/${_ffmpeg_suffix}")
            endif()
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_dirs)
    set(${_out} "${_ffmpeg_dirs}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_find_header_dir _out _header)
    _ffmpeg_native_dep_prefix_include_dirs(_ffmpeg_include_dirs)
    foreach(_ffmpeg_include_dir IN LISTS _ffmpeg_include_dirs)
        if(EXISTS "${_ffmpeg_include_dir}/${_header}")
            set(${_out} "${_ffmpeg_include_dir}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${_out} "" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_header_available _out _header)
    _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "${_header}")
    if(_ffmpeg_header_dir)
        set(${_out} TRUE PARENT_SCOPE)
        return()
    endif()

    string(MAKE_C_IDENTIFIER "FFMPEG_NATIVE_DEP_HAVE_HEADER_${_header}" _ffmpeg_header_var)
    check_include_file("${_header}" "${_ffmpeg_header_var}")
    set(${_out} "${${_ffmpeg_header_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_has_manual_fallback _out _feature)
    if(_feature STREQUAL "ffnvcodec" OR
       _feature STREQUAL "amf" OR
       _feature STREQUAL "d3d11va" OR
       _feature STREQUAL "d3d12va" OR
       _feature STREQUAL "dshow_indev" OR
       _feature STREQUAL "dxva2" OR
       _feature STREQUAL "gdigrab_indev" OR
       _feature STREQUAL "lcms2" OR
       _feature STREQUAL "libass" OR
       _feature STREQUAL "libbluray" OR
       _feature STREQUAL "libdav1d" OR
       _feature STREQUAL "libfdk_aac" OR
       _feature STREQUAL "libfontconfig" OR
       _feature STREQUAL "libfribidi" OR
       _feature STREQUAL "libjxl" OR
       _feature STREQUAL "libjxl_threads" OR
       _feature STREQUAL "libkvazaar" OR
       _feature STREQUAL "libmfx" OR
       _feature STREQUAL "libmp3lame" OR
       _feature STREQUAL "libmysofa" OR
       _feature STREQUAL "libopenh264" OR
       _feature STREQUAL "libopenmpt" OR
       _feature STREQUAL "libopencore_amrnb" OR
       _feature STREQUAL "libopencore_amrwb" OR
       _feature STREQUAL "librav1e" OR
       _feature STREQUAL "libshine" OR
       _feature STREQUAL "libsnappy" OR
       _feature STREQUAL "libsoxr" OR
       _feature STREQUAL "libspeex" OR
       _feature STREQUAL "libsvtav1" OR
       _feature STREQUAL "libtheora" OR
       _feature STREQUAL "libtwolame" OR
       _feature STREQUAL "libvidstab" OR
       _feature STREQUAL "libvo_amrwbenc" OR
       _feature STREQUAL "libvorbis" OR
       _feature STREQUAL "libvorbisenc" OR
       _feature STREQUAL "libvpl" OR
       _feature STREQUAL "libwebp" OR
       _feature STREQUAL "libx264" OR
       _feature STREQUAL "libx265" OR
       _feature STREQUAL "libxvid" OR
       _feature STREQUAL "libzimg" OR
       _feature STREQUAL "mediafoundation" OR
       _feature STREQUAL "network" OR
       _feature STREQUAL "openssl" OR
       _feature STREQUAL "vfwcap_indev" OR
       _feature STREQUAL "vulkan")
        set(${_out} TRUE PARENT_SCOPE)
    else()
        set(${_out} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_ffmpeg_native_dep_var_suffix _out _name)
    string(TOUPPER "${_name}" _ffmpeg_suffix)
    string(REGEX REPLACE "[^A-Z0-9_]" "_" _ffmpeg_suffix "${_ffmpeg_suffix}")
    set(${_out} "${_ffmpeg_suffix}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_escape _out _value)
    string(REPLACE "\\" "\\\\" _ffmpeg_value "${_value}")
    string(REPLACE "\"" "\\\"" _ffmpeg_value "${_ffmpeg_value}")
    set(${_out} "${_ffmpeg_value}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_append_list _out _var)
    string(APPEND ${_out} "    set(${_var}\n")
    foreach(_ffmpeg_value IN LISTS ARGN)
        _ffmpeg_native_dep_escape(_ffmpeg_escaped "${_ffmpeg_value}")
        string(APPEND ${_out} "        \"${_ffmpeg_escaped}\"\n")
    endforeach()
    string(APPEND ${_out} "    )\n")
    set(${_out} "${${_out}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_split_words _out _text)
    set(_ffmpeg_text "${_text}")
    set(_ffmpeg_words)
    foreach(_ffmpeg_unused RANGE 0 64)
        string(STRIP "${_ffmpeg_text}" _ffmpeg_text)
        if(_ffmpeg_text STREQUAL "")
            break()
        elseif(_ffmpeg_text MATCHES "^\"([^\"]*)\"[ \t]*(.*)$")
            list(APPEND _ffmpeg_words "${CMAKE_MATCH_1}")
            set(_ffmpeg_text "${CMAKE_MATCH_2}")
        elseif(_ffmpeg_text MATCHES "^'([^']*)'[ \t]*(.*)$")
            list(APPEND _ffmpeg_words "${CMAKE_MATCH_1}")
            set(_ffmpeg_text "${CMAKE_MATCH_2}")
        elseif(_ffmpeg_text MATCHES "^([^ \t;&|{}()]+)[ \t]*(.*)$")
            list(APPEND _ffmpeg_words "${CMAKE_MATCH_1}")
            set(_ffmpeg_text "${CMAKE_MATCH_2}")
        else()
            break()
        endif()
    endforeach()

    set(${_out} "${_ffmpeg_words}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_add_pkg_rule _feature _pkg)
    if(_feature STREQUAL "" OR _pkg STREQUAL "")
        return()
    endif()
    if(_pkg MATCHES "^([A-Za-z0-9_.+-]+)")
        set(_pkg "${CMAKE_MATCH_1}")
    endif()
    if(_feature MATCHES "[^A-Za-z0-9_]" OR _feature MATCHES "^\\$" OR _pkg MATCHES "\\$")
        return()
    endif()

    _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_feature}")
    set(_ffmpeg_var "FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix}")
    list(APPEND ${_ffmpeg_var} "${_pkg}")
    list(REMOVE_DUPLICATES ${_ffmpeg_var})
    set(${_ffmpeg_var} "${${_ffmpeg_var}}" PARENT_SCOPE)

    set(FFMPEG_NATIVE_DEP_FEATURES "${FFMPEG_NATIVE_DEP_FEATURES};${_feature}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_collect_pkg_rules)
    file(STRINGS "${FFMPEG_SOURCE_DIR}/configure" _ffmpeg_lines)
    set(FFMPEG_NATIVE_DEP_FEATURES)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_lines)
        set(_ffmpeg_rest "${_ffmpeg_line}")
        foreach(_ffmpeg_unused RANGE 0 8)
            if(_ffmpeg_rest MATCHES "((require|check|test)_pkg_config(_[A-Za-z0-9_]+)?)[ \t]+(.+)$")
                set(_ffmpeg_after "${CMAKE_MATCH_4}")
                _ffmpeg_native_dep_split_words(_ffmpeg_words "${_ffmpeg_after}")
                list(LENGTH _ffmpeg_words _ffmpeg_word_count)
                if(_ffmpeg_word_count GREATER 1)
                    list(GET _ffmpeg_words 0 _ffmpeg_feature)
                    list(GET _ffmpeg_words 1 _ffmpeg_pkg)
                    _ffmpeg_native_dep_add_pkg_rule("${_ffmpeg_feature}" "${_ffmpeg_pkg}")
                endif()
                set(_ffmpeg_rest "${_ffmpeg_after}")
            else()
                break()
            endif()
        endforeach()
    endforeach()

    set(_ffmpeg_alias_features
        ffnvcodec
        lcms2
        libaom
        libass
        libbluray
        libdav1d
        libfdk_aac
        libfontconfig
        libfreetype
        libfribidi
        libharfbuzz
        libjxl
        libjxl_threads
        libkvazaar
        libmfx
        libopenh264
        libopenjpeg
        libopenmpt
        libmysofa
        libopencore_amrnb
        libopencore_amrwb
        libopus
        librav1e
        libshine
        libsnappy
        libsoxr
        libspeex
        libsvtav1
        libvidstab
        libvo_amrwbenc
        libvorbis
        libvorbisenc
        libvpl
        libvpx
        libwebp
        libxml2
        libx264
        libx265
        libzimg
        zlib)
    set(_ffmpeg_alias_pkgs
        ffnvcodec
        lcms2
        aom
        libass
        libbluray
        dav1d
        fdk-aac
        fontconfig
        freetype2
        fribidi
        harfbuzz
        libjxl
        libjxl_threads
        kvazaar
        libmfx
        openh264
        libopenjp2
        libopenmpt
        libmysofa
        opencore-amrnb
        opencore-amrwb
        opus
        rav1e
        shine
        snappy
        soxr
        speex
        SvtAv1Enc
        vidstab
        vo-amrwbenc
        vorbis
        vorbisenc
        vpl
        vpx
        libwebp
        libxml-2.0
        x264
        x265
        zimg
        zlib)
    foreach(_ffmpeg_feature _ffmpeg_pkg IN ZIP_LISTS _ffmpeg_alias_features _ffmpeg_alias_pkgs)
        _ffmpeg_native_dep_add_pkg_rule("${_ffmpeg_feature}" "${_ffmpeg_pkg}")
    endforeach()

    list(REMOVE_DUPLICATES FFMPEG_NATIVE_DEP_FEATURES)
    foreach(_ffmpeg_feature IN LISTS FFMPEG_NATIVE_DEP_FEATURES)
        _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_ffmpeg_feature}")
        set(FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix} "${FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix}}" PARENT_SCOPE)
    endforeach()
    set(FFMPEG_NATIVE_DEP_FEATURES "${FFMPEG_NATIVE_DEP_FEATURES}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_create_pkg_target _out_target _out_found _feature _pkg)
    set(_ffmpeg_target "FFmpegExternal::${_feature}")
    if(TARGET "${_ffmpeg_target}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    _ffmpeg_pkg_config_path(_ffmpeg_pc_path "")
    _ffmpeg_pkg_config_output(_ffmpeg_unused _ffmpeg_exists "${_ffmpeg_pc_path}" --exists "${_pkg}")
    if(NOT _ffmpeg_exists EQUAL 0)
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} FALSE PARENT_SCOPE)
        return()
    endif()

    add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
    if(COMMAND ffmpeg_set_target_folder)
        ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
    endif()
    _ffmpeg_apply_pkg_config_target("${_ffmpeg_target}" "${_ffmpeg_pc_path}" "${FFMPEG_BUILD_STATIC}" "${_pkg}")
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_create_threads_target _out_target _out_found)
    set(_ffmpeg_target "FFmpegExternal::threads")
    if(NOT TARGET "${_ffmpeg_target}")
        find_package(Threads QUIET)
        if(NOT Threads_FOUND)
            set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
            set(${_out_found} FALSE PARENT_SCOPE)
            return()
        endif()
        add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
        if(COMMAND ffmpeg_set_target_folder)
            ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
        endif()
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_LINK_LIBRARIES "Threads::Threads")
    endif()
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_create_libdl_target _out_target _out_found)
    set(_ffmpeg_target "FFmpegExternal::libdl")
    if(NOT TARGET "${_ffmpeg_target}")
        add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
        if(COMMAND ffmpeg_set_target_folder)
            ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
        endif()
        if(CMAKE_DL_LIBS)
            set_target_properties("${_ffmpeg_target}" PROPERTIES
                INTERFACE_LINK_LIBRARIES "${CMAKE_DL_LIBS}")
        endif()
    endif()
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_sdl2_candidate_dirs _out)
    set(_ffmpeg_dirs)
    if(SDL2_DIR)
        list(APPEND _ffmpeg_dirs "${SDL2_DIR}")
    endif()

    foreach(_ffmpeg_prefix IN LISTS CMAKE_PREFIX_PATH)
        if(_ffmpeg_prefix STREQUAL "")
            continue()
        endif()
        foreach(_ffmpeg_suffix IN ITEMS "" lib/cmake/SDL2 lib64/cmake/SDL2)
            if(_ffmpeg_suffix STREQUAL "")
                set(_ffmpeg_dir "${_ffmpeg_prefix}")
            else()
                set(_ffmpeg_dir "${_ffmpeg_prefix}/${_ffmpeg_suffix}")
            endif()
            if(EXISTS "${_ffmpeg_dir}/SDL2Config.cmake")
                list(APPEND _ffmpeg_dirs "${_ffmpeg_dir}")
            endif()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_dirs)
    set(${_out} "${_ffmpeg_dirs}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_sdl2_include_config _target _dir _export _config)
    if(NOT TARGET "${_target}")
        return()
    endif()

    get_target_property(_ffmpeg_aliased "${_target}" ALIASED_TARGET)
    if(_ffmpeg_aliased)
        return()
    endif()

    string(TOUPPER "${_config}" _ffmpeg_config_uc)
    get_target_property(_ffmpeg_imported_configs "${_target}" IMPORTED_CONFIGURATIONS)
    if(_ffmpeg_imported_configs)
        list(FIND _ffmpeg_imported_configs "${_ffmpeg_config_uc}" _ffmpeg_existing_config)
        if(NOT _ffmpeg_existing_config EQUAL -1)
            return()
        endif()
    endif()

    string(TOLOWER "${_config}" _ffmpeg_config_lc)
    set(_ffmpeg_config_file "${_dir}/${_export}-${_ffmpeg_config_lc}.cmake")
    if(NOT EXISTS "${_ffmpeg_config_file}")
        return()
    endif()

    get_filename_component(_IMPORT_PREFIX "${_dir}/../../../" ABSOLUTE)
    include("${_ffmpeg_config_file}")
    unset(_IMPORT_PREFIX)
endfunction()

function(_ffmpeg_native_dep_augment_sdl2_configs)
    _ffmpeg_native_dep_sdl2_candidate_dirs(_ffmpeg_sdl2_dirs)
    foreach(_ffmpeg_dir IN LISTS _ffmpeg_sdl2_dirs)
        foreach(_ffmpeg_config IN ITEMS Debug Release RelWithDebInfo MinSizeRel)
            _ffmpeg_native_dep_sdl2_include_config(SDL2::SDL2-static "${_ffmpeg_dir}" SDL2staticTargets "${_ffmpeg_config}")
            _ffmpeg_native_dep_sdl2_include_config(SDL2::SDL2main "${_ffmpeg_dir}" SDL2mainTargets "${_ffmpeg_config}")
            _ffmpeg_native_dep_sdl2_include_config(SDL2::SDL2 "${_ffmpeg_dir}" SDL2Targets "${_ffmpeg_config}")
        endforeach()
    endforeach()
endfunction()

function(_ffmpeg_native_dep_create_sdl2_target _out_target _out_found)
    set(_ffmpeg_target "FFmpegExternal::sdl2")
    if(TARGET "${_ffmpeg_target}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    find_package(SDL2 CONFIG QUIET)
    _ffmpeg_native_dep_augment_sdl2_configs()

    set(_ffmpeg_sdl2_link_targets)
    if(WIN32 AND TARGET SDL2::SDL2main)
        list(APPEND _ffmpeg_sdl2_link_targets SDL2::SDL2main)
    endif()
    if(FFMPEG_BUILD_STATIC AND TARGET SDL2::SDL2-static)
        list(APPEND _ffmpeg_sdl2_link_targets SDL2::SDL2-static)
    elseif(TARGET SDL2::SDL2)
        list(APPEND _ffmpeg_sdl2_link_targets SDL2::SDL2)
    elseif(TARGET SDL2::SDL2-static)
        list(APPEND _ffmpeg_sdl2_link_targets SDL2::SDL2-static)
    endif()

    if(_ffmpeg_sdl2_link_targets)
        add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
        if(COMMAND ffmpeg_set_target_folder)
            ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
        endif()
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_LINK_LIBRARIES "${_ffmpeg_sdl2_link_targets}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    set(_ffmpeg_sdl2_include_dirs ${SDL2_INCLUDE_DIRS})
    if(NOT _ffmpeg_sdl2_include_dirs AND SDL2_INCLUDE_DIR)
        set(_ffmpeg_sdl2_include_dirs "${SDL2_INCLUDE_DIR}")
    endif()

    set(_ffmpeg_sdl2_libraries ${SDL2_LIBRARIES})
    if(NOT _ffmpeg_sdl2_libraries AND SDL2_LIBRARY)
        set(_ffmpeg_sdl2_libraries "${SDL2_LIBRARY}")
    endif()
    if(WIN32 AND SDL2MAIN_LIBRARY)
        list(PREPEND _ffmpeg_sdl2_libraries "${SDL2MAIN_LIBRARY}")
    endif()

    if(_ffmpeg_sdl2_libraries)
        add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
        if(COMMAND ffmpeg_set_target_folder)
            ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
        endif()
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_LINK_LIBRARIES "${_ffmpeg_sdl2_libraries}")
        if(_ffmpeg_sdl2_include_dirs)
            set_target_properties("${_ffmpeg_target}" PROPERTIES
                INTERFACE_INCLUDE_DIRECTORIES "${_ffmpeg_sdl2_include_dirs}")
        endif()
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} FALSE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_cmake_fallback _out_package _out_targets _feature)
    set(_ffmpeg_package)
    set(_ffmpeg_targets)

    if(_feature STREQUAL "zlib")
        set(_ffmpeg_package ZLIB)
        set(_ffmpeg_targets ZLIB::ZLIB)
    elseif(_feature STREQUAL "bzlib")
        set(_ffmpeg_package BZip2)
        set(_ffmpeg_targets BZip2::BZip2)
    elseif(_feature STREQUAL "lzma")
        set(_ffmpeg_package LibLZMA)
        set(_ffmpeg_targets LibLZMA::LibLZMA)
    elseif(_feature STREQUAL "iconv")
        set(_ffmpeg_package Iconv)
        set(_ffmpeg_targets Iconv::Iconv)
    elseif(_feature STREQUAL "openssl")
        set(_ffmpeg_package OpenSSL)
        set(_ffmpeg_targets OpenSSL::SSL OpenSSL::Crypto)
    elseif(_feature STREQUAL "libxml2")
        set(_ffmpeg_package LibXml2)
        set(_ffmpeg_targets LibXml2::LibXml2)
    elseif(_feature STREQUAL "libaom")
        set(_ffmpeg_package AOM)
        set(_ffmpeg_targets AOM::aom)
    elseif(_feature STREQUAL "lcms2")
        set(_ffmpeg_package lcms2)
        set(_ffmpeg_targets lcms2::lcms2)
    elseif(_feature STREQUAL "libfreetype")
        set(_ffmpeg_package Freetype)
        set(_ffmpeg_targets Freetype::Freetype)
    elseif(_feature STREQUAL "libharfbuzz")
        set(_ffmpeg_package harfbuzz)
        set(_ffmpeg_targets harfbuzz::harfbuzz)
    elseif(_feature STREQUAL "libmfx" AND "libvpl" IN_LIST FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES)
        set(_ffmpeg_package VPL)
        set(_ffmpeg_targets VPL::dispatcher)
    elseif(_feature STREQUAL "libopenjpeg")
        set(_ffmpeg_package OpenJPEG)
        set(_ffmpeg_targets openjp2)
    elseif(_feature STREQUAL "libopus")
        set(_ffmpeg_package Opus)
        set(_ffmpeg_targets Opus::opus)
    elseif(_feature STREQUAL "libvpl")
        set(_ffmpeg_package VPL)
        set(_ffmpeg_targets VPL::dispatcher)
    elseif(_feature STREQUAL "libvpx")
        set(_ffmpeg_package unofficial-libvpx)
        set(_ffmpeg_targets unofficial::libvpx::libvpx)
    elseif(_feature STREQUAL "vulkan")
        set(_ffmpeg_package Vulkan)
        set(_ffmpeg_targets Vulkan::Vulkan)
    elseif(_feature STREQUAL "opencl")
        set(_ffmpeg_package OpenCL)
        set(_ffmpeg_targets OpenCL::OpenCL)
    elseif(_feature STREQUAL "sdl2")
        set(_ffmpeg_package SDL2)
        set(_ffmpeg_targets FFmpegExternal::sdl2)
    endif()

    set(${_out_package} "${_ffmpeg_package}" PARENT_SCOPE)
    set(${_out_targets} "${_ffmpeg_targets}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_find_package _package)
    if(_package STREQUAL "Freetype")
        find_package(PNG CONFIG QUIET)
    endif()
    if(FFMPEG_BUILD_STATIC AND NOT WIN32)
        set(_ffmpeg_saved_suffixes ${CMAKE_FIND_LIBRARY_SUFFIXES})
        set(CMAKE_FIND_LIBRARY_SUFFIXES "${CMAKE_STATIC_LIBRARY_SUFFIX}" ${_ffmpeg_saved_suffixes})
        list(REMOVE_DUPLICATES CMAKE_FIND_LIBRARY_SUFFIXES)
        find_package("${_package}" QUIET)
        set(CMAKE_FIND_LIBRARY_SUFFIXES ${_ffmpeg_saved_suffixes})
    else()
        find_package("${_package}" QUIET)
    endif()
endfunction()

function(_ffmpeg_native_dep_create_cmake_target _out_target _out_found _feature)
    set(_ffmpeg_target "FFmpegExternal::${_feature}")
    if(TARGET "${_ffmpeg_target}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    _ffmpeg_native_dep_cmake_fallback(_ffmpeg_package _ffmpeg_link_targets "${_feature}")
    if(NOT _ffmpeg_package)
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} FALSE PARENT_SCOPE)
        return()
    endif()

    _ffmpeg_native_dep_find_package("${_ffmpeg_package}")
    foreach(_ffmpeg_link_target IN LISTS _ffmpeg_link_targets)
        if(NOT TARGET "${_ffmpeg_link_target}")
            set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
            set(${_out_found} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()

    if(_feature STREQUAL "openssl" AND WIN32)
        list(APPEND _ffmpeg_link_targets crypt32 ws2_32 user32 advapi32 bcrypt)
    endif()

    add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
    if(COMMAND ffmpeg_set_target_folder)
        ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
    endif()
    set_target_properties("${_ffmpeg_target}" PROPERTIES
        INTERFACE_LINK_LIBRARIES "${_ffmpeg_link_targets}")
    if(_feature STREQUAL "libvpl" OR
       (_feature STREQUAL "libmfx" AND "libvpl" IN_LIST FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES))
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_vpl_header_dir "mfxvideo.h")
        if(_ffmpeg_vpl_header_dir)
            set_target_properties("${_ffmpeg_target}" PROPERTIES
                INTERFACE_INCLUDE_DIRECTORIES "${_ffmpeg_vpl_header_dir}")
        endif()
    endif()
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_find_header_library _out_found _out_header_dir _out_library _header)
    _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "${_header}")
    _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
    find_library(_ffmpeg_library NAMES ${ARGN} HINTS ${_ffmpeg_library_dirs})
    _ffmpeg_native_dep_header_available(_ffmpeg_header_available "${_header}")
    if(_ffmpeg_header_available AND _ffmpeg_library)
        set(${_out_found} TRUE PARENT_SCOPE)
        set(${_out_header_dir} "${_ffmpeg_header_dir}" PARENT_SCOPE)
        set(${_out_library} "${_ffmpeg_library}" PARENT_SCOPE)
    else()
        set(${_out_found} FALSE PARENT_SCOPE)
        set(${_out_header_dir} "" PARENT_SCOPE)
        set(${_out_library} "" PARENT_SCOPE)
    endif()
endfunction()

function(_ffmpeg_native_dep_create_manual_target _out_target _out_found _feature)
    set(_ffmpeg_target "FFmpegExternal::${_feature}")
    if(TARGET "${_ffmpeg_target}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    set(_ffmpeg_include_dirs)
    set(_ffmpeg_compile_definitions)
    set(_ffmpeg_link_libraries)
    set(_ffmpeg_found TRUE)

    if(_feature STREQUAL "ffnvcodec")
        foreach(_ffmpeg_header IN ITEMS
                ffnvcodec/nvEncodeAPI.h
                ffnvcodec/dynlink_cuda.h
                ffnvcodec/dynlink_cuviddec.h
                ffnvcodec/dynlink_nvcuvid.h)
            _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "${_ffmpeg_header}")
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            else()
                _ffmpeg_native_dep_header_available(_ffmpeg_header_available "${_ffmpeg_header}")
                if(NOT _ffmpeg_header_available)
                    set(_ffmpeg_found FALSE)
                endif()
            endif()
        endforeach()
    elseif(_feature STREQUAL "amf")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "AMF/core/Version.h")
        if(_ffmpeg_header_dir)
            list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
        else()
            _ffmpeg_native_dep_header_available(_ffmpeg_header_available "AMF/core/Version.h")
            if(NOT _ffmpeg_header_available)
                set(_ffmpeg_found FALSE)
            endif()
        endif()
        if(NOT FFMPEG_AMF_HEADERS_USABLE)
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "d3d11va")
        if(WIN32)
            set(_ffmpeg_link_libraries d3d11 dxgi dxguid)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "d3d12va")
        if(WIN32)
            set(_ffmpeg_link_libraries d3d12 dxgi dxguid)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "dxva2")
        if(WIN32)
            set(_ffmpeg_link_libraries dxva2 d3d9 dxguid ole32 user32)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "mediafoundation")
        if(WIN32)
            set(_ffmpeg_link_libraries mfplat mfuuid ole32 strmiids)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "dshow_indev")
        if(WIN32)
            _ffmpeg_native_dep_header_available(_ffmpeg_header_available "dshow.h")
            if(_ffmpeg_header_available)
                set(_ffmpeg_link_libraries psapi ole32 strmiids uuid oleaut32 shlwapi)
            else()
                set(_ffmpeg_found FALSE)
            endif()
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "gdigrab_indev")
        if(WIN32)
            set(_ffmpeg_link_libraries gdi32 user32)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "vfwcap_indev")
        if(WIN32)
            set(_ffmpeg_link_libraries vfw32 user32)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "lcms2")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "lcms2.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_lcms2_library NAMES lcms2 liblcms2 HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "lcms2.h")
        if(_ffmpeg_header_available AND _ffmpeg_lcms2_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_lcms2_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libmfx")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_root "mfx/mfxvideo.h")
        if(_ffmpeg_header_root)
            set(_ffmpeg_header_dir "${_ffmpeg_header_root}/mfx")
        else()
            _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "mfxvideo.h")
        endif()
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_mfx_library NAMES mfx libmfx HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "mfx/mfxvideo.h")
        if(_ffmpeg_header_available AND _ffmpeg_mfx_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_mfx_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libass")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "ass/ass.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_ass_library NAMES ass libass HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_ass_freetype_library NAMES freetype freetype_static libfreetype HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_ass_harfbuzz_library NAMES harfbuzz libharfbuzz HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_ass_fribidi_library NAMES fribidi libfribidi HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_ass_fontconfig_library NAMES fontconfig libfontconfig HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_ass_expat_library NAMES expat expatMT libexpat libexpatMT HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "ass/ass.h")
        if(_ffmpeg_header_available AND _ffmpeg_ass_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_ass_library}")
            foreach(_ffmpeg_ass_dep IN ITEMS
                    _ffmpeg_ass_freetype_library
                    _ffmpeg_ass_harfbuzz_library
                    _ffmpeg_ass_fribidi_library
                    _ffmpeg_ass_fontconfig_library
                    _ffmpeg_ass_expat_library)
                if(${_ffmpeg_ass_dep})
                    list(APPEND _ffmpeg_link_libraries "${${_ffmpeg_ass_dep}}")
                endif()
            endforeach()
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libbluray")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "libbluray/bluray.h" bluray libbluray)
        if(_ffmpeg_simple_found)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libdav1d")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "dav1d/dav1d.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_dav1d_library NAMES dav1d libdav1d HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "dav1d/dav1d.h")
        if(_ffmpeg_header_available AND _ffmpeg_dav1d_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_dav1d_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libfdk_aac")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "fdk-aac/aacenc_lib.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_fdk_aac_library NAMES fdk-aac fdk_aac libfdk-aac libfdk_aac HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "fdk-aac/aacenc_lib.h")
        if(_ffmpeg_header_available AND _ffmpeg_fdk_aac_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_fdk_aac_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libfontconfig")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "fontconfig/fontconfig.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_fontconfig_library NAMES fontconfig libfontconfig HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_expat_library NAMES expat expatMT libexpat libexpatMT HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "fontconfig/fontconfig.h")
        if(_ffmpeg_header_available AND _ffmpeg_fontconfig_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_fontconfig_library}")
            if(_ffmpeg_expat_library)
                list(APPEND _ffmpeg_link_libraries "${_ffmpeg_expat_library}")
            endif()
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libfribidi")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "fribidi.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_fribidi_library NAMES fribidi libfribidi HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "fribidi.h")
        if(_ffmpeg_header_available AND _ffmpeg_fribidi_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_fribidi_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libjxl")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "jxl/decode.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_jxl_library NAMES jxl libjxl HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_jxl_cms_library NAMES jxl_cms libjxl_cms HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_hwy_library NAMES hwy libhwy HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_brotlienc_library NAMES brotlienc libbrotlienc HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_brotlidec_library NAMES brotlidec libbrotlidec HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_brotlicommon_library NAMES brotlicommon libbrotlicommon HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_lcms2_library NAMES lcms2 liblcms2 HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "jxl/decode.h")
        if(_ffmpeg_header_available AND _ffmpeg_jxl_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_jxl_library}")
            foreach(_ffmpeg_jxl_dep IN ITEMS
                    _ffmpeg_jxl_cms_library
                    _ffmpeg_hwy_library
                    _ffmpeg_brotlienc_library
                    _ffmpeg_brotlidec_library
                    _ffmpeg_brotlicommon_library
                    _ffmpeg_lcms2_library)
                if(${_ffmpeg_jxl_dep})
                    list(APPEND _ffmpeg_link_libraries "${${_ffmpeg_jxl_dep}}")
                endif()
            endforeach()
            list(APPEND _ffmpeg_compile_definitions JXL_STATIC_DEFINE JXL_CMS_STATIC_DEFINE HWY_STATIC_DEFINE)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libjxl_threads")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "jxl/thread_parallel_runner.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_jxl_threads_library NAMES jxl_threads libjxl_threads HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "jxl/thread_parallel_runner.h")
        if(_ffmpeg_header_available AND _ffmpeg_jxl_threads_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_jxl_threads_library}")
            list(APPEND _ffmpeg_compile_definitions JXL_THREADS_STATIC_DEFINE)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libkvazaar")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "kvazaar.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_kvazaar_library NAMES kvazaar libkvazaar HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "kvazaar.h")
        if(_ffmpeg_header_available AND _ffmpeg_kvazaar_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_kvazaar_library}")
            list(APPEND _ffmpeg_compile_definitions KVZ_STATIC_LIB)
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libmp3lame")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "lame/lame.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_mp3lame_library NAMES mp3lame libmp3lame HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "lame/lame.h")
        if(_ffmpeg_header_available AND _ffmpeg_mp3lame_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_mp3lame_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libopenh264")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "wels/codec_api.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_openh264_library NAMES openh264 libopenh264 HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "wels/codec_api.h")
        if(_ffmpeg_header_available AND _ffmpeg_openh264_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_openh264_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libopenmpt")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "libopenmpt/libopenmpt.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_openmpt_library NAMES openmpt libopenmpt HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "libopenmpt/libopenmpt.h")
        if(_ffmpeg_header_available AND _ffmpeg_openmpt_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_openmpt_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libmysofa")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "mysofa.h" mysofa libmysofa)
        if(_ffmpeg_simple_found)
            _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
            find_library(_ffmpeg_zlib_library NAMES z zlib zlibstatic libz libzlib HINTS ${_ffmpeg_library_dirs})
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
            if(_ffmpeg_zlib_library)
                list(APPEND _ffmpeg_link_libraries "${_ffmpeg_zlib_library}")
            endif()
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libopencore_amrnb")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "opencore-amrnb/interf_dec.h" opencore-amrnb libopencore-amrnb)
        if(_ffmpeg_simple_found)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libopencore_amrwb")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "opencore-amrwb/dec_if.h" opencore-amrwb libopencore-amrwb)
        if(_ffmpeg_simple_found)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "librav1e")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "rav1e.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_rav1e_library NAMES rav1e librav1e HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "rav1e.h")
        if(_ffmpeg_header_available AND _ffmpeg_rav1e_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_rav1e_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libshine")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "shine/layer3.h" shine libshine)
        if(_ffmpeg_simple_found)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libsnappy")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "snappy-c.h" snappy libsnappy)
        if(_ffmpeg_simple_found)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
            if(NOT MSVC AND NOT WIN32)
                list(APPEND _ffmpeg_link_libraries stdc++)
            endif()
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libsoxr")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "soxr.h" soxr libsoxr)
        if(_ffmpeg_simple_found)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libspeex")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "speex/speex.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_speex_library NAMES speex libspeex HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "speex/speex.h")
        if(_ffmpeg_header_available AND _ffmpeg_speex_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_speex_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libsvtav1")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "EbSvtAv1Enc.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_svtav1_library NAMES SvtAv1Enc SvtAv1EncStatic libSvtAv1Enc libSvtAv1EncStatic HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "EbSvtAv1Enc.h")
        if(_ffmpeg_header_available AND _ffmpeg_svtav1_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_svtav1_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libtheora")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "theora/theoraenc.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_theoraenc_library NAMES theoraenc libtheoraenc HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_theoradec_library NAMES theoradec libtheoradec HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_ogg_library NAMES ogg libogg HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "theora/theoraenc.h")
        if(_ffmpeg_header_available AND _ffmpeg_theoraenc_library AND _ffmpeg_theoradec_library AND _ffmpeg_ogg_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries
                "${_ffmpeg_theoraenc_library}"
                "${_ffmpeg_theoradec_library}"
                "${_ffmpeg_ogg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libtwolame")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "twolame.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_twolame_library NAMES twolame libtwolame HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "twolame.h")
        if(_ffmpeg_header_available AND _ffmpeg_twolame_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_twolame_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libvidstab")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "vid.stab/libvidstab.h" vidstab libvidstab)
        if(_ffmpeg_simple_found)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libvo_amrwbenc")
        _ffmpeg_native_dep_find_header_library(_ffmpeg_simple_found _ffmpeg_header_dir _ffmpeg_library "vo-amrwbenc/enc_if.h" vo-amrwbenc libvo-amrwbenc)
        if(_ffmpeg_simple_found)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libvorbis")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "vorbis/codec.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_vorbis_library NAMES vorbis libvorbis HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_ogg_library NAMES ogg libogg HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "vorbis/codec.h")
        if(_ffmpeg_header_available AND _ffmpeg_vorbis_library AND _ffmpeg_ogg_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_vorbis_library}" "${_ffmpeg_ogg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libvorbisenc")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "vorbis/vorbisenc.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_vorbisenc_library NAMES vorbisenc libvorbisenc HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_vorbis_library NAMES vorbis libvorbis HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_ogg_library NAMES ogg libogg HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "vorbis/vorbisenc.h")
        if(_ffmpeg_header_available AND _ffmpeg_vorbisenc_library AND _ffmpeg_vorbis_library AND _ffmpeg_ogg_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_vorbisenc_library}" "${_ffmpeg_vorbis_library}" "${_ffmpeg_ogg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libvpl")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_root "vpl/mfxvideo.h")
        if(_ffmpeg_header_root)
            set(_ffmpeg_header_dir "${_ffmpeg_header_root}/vpl")
        else()
            _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "mfxvideo.h")
        endif()
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_vpl_library NAMES vpl libvpl HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "vpl/mfxvideo.h")
        if(_ffmpeg_header_available AND _ffmpeg_vpl_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_vpl_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libwebp")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "webp/encode.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_webp_library NAMES webp libwebp HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_webpmux_library NAMES webpmux libwebpmux HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_sharpyuv_library NAMES sharpyuv libsharpyuv HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "webp/encode.h")
        if(_ffmpeg_header_available AND _ffmpeg_webp_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_webp_library}")
            if(_ffmpeg_webpmux_library)
                list(APPEND _ffmpeg_link_libraries "${_ffmpeg_webpmux_library}")
            endif()
            if(_ffmpeg_sharpyuv_library)
                list(APPEND _ffmpeg_link_libraries "${_ffmpeg_sharpyuv_library}")
            endif()
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libx264")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "x264.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_x264_library NAMES x264 libx264 HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "x264.h")
        if(_ffmpeg_header_available AND _ffmpeg_x264_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_x264_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libx265")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "x265.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_x265_library NAMES x265-static x265 libx265 HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "x265.h")
        if(_ffmpeg_header_available AND _ffmpeg_x265_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_x265_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libxvid")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "xvid.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_xvid_library NAMES xvidcore libxvidcore xvid libxvid HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "xvid.h")
        if(_ffmpeg_header_available AND _ffmpeg_xvid_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_xvid_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "libzimg")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "zimg.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_zimg_library NAMES zimg libzimg HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "zimg.h")
        if(_ffmpeg_header_available AND _ffmpeg_zimg_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_zimg_library}")
        else()
            set(_ffmpeg_found FALSE)
        endif()
    elseif(_feature STREQUAL "vulkan")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "vulkan/vulkan.h")
        if(_ffmpeg_header_dir)
            list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
        else()
            _ffmpeg_native_dep_header_available(_ffmpeg_header_available "vulkan/vulkan.h")
            if(NOT _ffmpeg_header_available)
                set(_ffmpeg_found FALSE)
            endif()
        endif()
    elseif(_feature STREQUAL "network")
        if(WIN32)
            set(_ffmpeg_link_libraries ws2_32)
        endif()
    elseif(_feature STREQUAL "openssl")
        _ffmpeg_native_dep_find_header_dir(_ffmpeg_header_dir "openssl/ssl.h")
        _ffmpeg_native_dep_library_dirs(_ffmpeg_library_dirs)
        find_library(_ffmpeg_ssl_library NAMES ssl libssl HINTS ${_ffmpeg_library_dirs})
        find_library(_ffmpeg_crypto_library NAMES crypto libcrypto HINTS ${_ffmpeg_library_dirs})
        _ffmpeg_native_dep_header_available(_ffmpeg_header_available "openssl/ssl.h")
        if(_ffmpeg_header_available AND _ffmpeg_ssl_library AND _ffmpeg_crypto_library)
            if(_ffmpeg_header_dir)
                list(APPEND _ffmpeg_include_dirs "${_ffmpeg_header_dir}")
            endif()
            list(APPEND _ffmpeg_link_libraries "${_ffmpeg_ssl_library}" "${_ffmpeg_crypto_library}")
            if(WIN32)
                list(APPEND _ffmpeg_link_libraries crypt32 ws2_32 user32 advapi32 bcrypt)
            endif()
        else()
            set(_ffmpeg_found FALSE)
        endif()
    else()
        set(_ffmpeg_found FALSE)
    endif()

    if(NOT _ffmpeg_found)
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} FALSE PARENT_SCOPE)
        return()
    endif()

    add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
    if(COMMAND ffmpeg_set_target_folder)
        ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
    endif()
    if(_ffmpeg_include_dirs)
        list(REMOVE_DUPLICATES _ffmpeg_include_dirs)
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${_ffmpeg_include_dirs}")
    endif()
    if(_ffmpeg_compile_definitions)
        list(REMOVE_DUPLICATES _ffmpeg_compile_definitions)
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_COMPILE_DEFINITIONS "${_ffmpeg_compile_definitions}")
    endif()
    if(_ffmpeg_link_libraries)
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_LINK_LIBRARIES "${_ffmpeg_link_libraries}")
    endif()
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_try_import _out_target _out_found _feature)
    set(_ffmpeg_import_feature "${_feature}")
    if(_feature MATCHES "^libvpx_vp[89]_(decoder|encoder)$")
        set(_ffmpeg_import_feature libvpx)
    elseif(_feature MATCHES "^libwebp(_anim)?_encoder$")
        set(_ffmpeg_import_feature libwebp)
    endif()

    if(_ffmpeg_import_feature STREQUAL "threads" OR _ffmpeg_import_feature STREQUAL "pthreads")
        _ffmpeg_native_dep_create_threads_target(_ffmpeg_target _ffmpeg_found)
    elseif(_ffmpeg_import_feature STREQUAL "libdl")
        _ffmpeg_native_dep_create_libdl_target(_ffmpeg_target _ffmpeg_found)
    elseif(_ffmpeg_import_feature STREQUAL "sdl2")
        _ffmpeg_native_dep_create_sdl2_target(_ffmpeg_target _ffmpeg_found)
    else()
        _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_ffmpeg_import_feature}")
        set(_ffmpeg_pkgs "${FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix}}")
        if(_ffmpeg_import_feature STREQUAL "libmfx" AND "libvpl" IN_LIST FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES)
            list(PREPEND _ffmpeg_pkgs vpl)
            list(REMOVE_DUPLICATES _ffmpeg_pkgs)
        endif()
        set(_ffmpeg_found FALSE)
        foreach(_ffmpeg_pkg IN LISTS _ffmpeg_pkgs)
            _ffmpeg_native_dep_create_pkg_target(_ffmpeg_target _ffmpeg_found "${_ffmpeg_import_feature}" "${_ffmpeg_pkg}")
            if(_ffmpeg_found)
                break()
            endif()
        endforeach()
        if(NOT _ffmpeg_found)
            _ffmpeg_native_dep_create_cmake_target(_ffmpeg_target _ffmpeg_found "${_ffmpeg_import_feature}")
        endif()
        if(NOT _ffmpeg_found)
            _ffmpeg_native_dep_create_manual_target(_ffmpeg_target _ffmpeg_found "${_ffmpeg_import_feature}")
        endif()
    endif()

    if(NOT DEFINED _ffmpeg_target)
        set(_ffmpeg_target "FFmpegExternal::${_ffmpeg_import_feature}")
    endif()
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} "${_ffmpeg_found}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_write_target _content_var _target)
    string(REPLACE "FFmpegExternal::" "" _ffmpeg_feature "${_target}")
    _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_ffmpeg_feature}")
    string(APPEND ${_content_var} "if(NOT TARGET \"${_target}\")\n")
    string(APPEND ${_content_var} "    add_library(\"${_target}\" INTERFACE IMPORTED)\n")

    set(_ffmpeg_property_text)
    foreach(_ffmpeg_property IN ITEMS
            INTERFACE_INCLUDE_DIRECTORIES
            INTERFACE_COMPILE_DEFINITIONS
            INTERFACE_COMPILE_OPTIONS
            INTERFACE_LINK_DIRECTORIES
            INTERFACE_LINK_LIBRARIES)
        get_target_property(_ffmpeg_values "${_target}" "${_ffmpeg_property}")
        if(_ffmpeg_values AND NOT _ffmpeg_values MATCHES "-NOTFOUND$")
            set(_ffmpeg_var "_FFmpegExternal_${_ffmpeg_suffix}_${_ffmpeg_property}")
            _ffmpeg_native_dep_append_list(${_content_var} "${_ffmpeg_var}" ${_ffmpeg_values})
            string(APPEND _ffmpeg_property_text "        ${_ffmpeg_property} \"\${${_ffmpeg_var}}\"\n")
        endif()
    endforeach()

    if(_ffmpeg_property_text)
        string(APPEND ${_content_var} "    set_target_properties(\"${_target}\" PROPERTIES\n")
        string(APPEND ${_content_var} "${_ffmpeg_property_text}")
        string(APPEND ${_content_var} "    )\n")
    endif()
    string(APPEND ${_content_var} "endif()\n\n")
    set(${_content_var} "${${_content_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_package_for_link _out _link_item)
    set(_ffmpeg_package)
    if(_link_item STREQUAL "Threads::Threads")
        set(_ffmpeg_package Threads)
    elseif(_link_item STREQUAL "ZLIB::ZLIB")
        set(_ffmpeg_package ZLIB)
    elseif(_link_item STREQUAL "BZip2::BZip2")
        set(_ffmpeg_package BZip2)
    elseif(_link_item STREQUAL "LibLZMA::LibLZMA")
        set(_ffmpeg_package LibLZMA)
    elseif(_link_item STREQUAL "PNG::PNG")
        set(_ffmpeg_package PNG)
    elseif(_link_item STREQUAL "Iconv::Iconv")
        set(_ffmpeg_package Iconv)
    elseif(_link_item MATCHES "^OpenSSL::")
        set(_ffmpeg_package OpenSSL)
    elseif(_link_item STREQUAL "LibXml2::LibXml2")
        set(_ffmpeg_package LibXml2)
    elseif(_link_item MATCHES "^AOM::")
        set(_ffmpeg_package AOM)
    elseif(_link_item MATCHES "^lcms2::")
        set(_ffmpeg_package lcms2)
    elseif(_link_item STREQUAL "Freetype::Freetype")
        set(_ffmpeg_package Freetype)
    elseif(_link_item MATCHES "^(harfbuzz::|HarfBuzz::)")
        set(_ffmpeg_package harfbuzz)
    elseif(_link_item STREQUAL "openjp2")
        set(_ffmpeg_package OpenJPEG)
    elseif(_link_item MATCHES "^Opus::")
        set(_ffmpeg_package Opus)
    elseif(_link_item MATCHES "^VPL::")
        set(_ffmpeg_package VPL)
    elseif(_link_item STREQUAL "unofficial::libvpx::libvpx")
        set(_ffmpeg_package unofficial-libvpx)
    elseif(_link_item STREQUAL "Vulkan::Vulkan")
        set(_ffmpeg_package Vulkan)
    elseif(_link_item STREQUAL "OpenCL::OpenCL")
        set(_ffmpeg_package OpenCL)
    elseif(_link_item MATCHES "^SDL2::")
        set(_ffmpeg_package SDL2)
    endif()
    set(${_out} "${_ffmpeg_package}" PARENT_SCOPE)
endfunction()

function(ffmpeg_native_import_dependencies _out_file _out_targets)
    _ffmpeg_native_dep_collect_pkg_rules()

    set(_ffmpeg_enabled_features
        ${FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES}
        ${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES})
    list(REMOVE_DUPLICATES _ffmpeg_enabled_features)

    set(_ffmpeg_targets)
    set(_ffmpeg_found_features)
    set(_ffmpeg_missing)
    foreach(_ffmpeg_feature IN LISTS _ffmpeg_enabled_features)
        _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_ffmpeg_feature}")
        _ffmpeg_native_dep_cmake_fallback(_ffmpeg_cmake_package _ffmpeg_unused_targets "${_ffmpeg_feature}")
        _ffmpeg_native_dep_has_manual_fallback(_ffmpeg_manual_fallback "${_ffmpeg_feature}")
        if(DEFINED FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix} OR
           _ffmpeg_cmake_package OR
           _ffmpeg_manual_fallback OR
           _ffmpeg_feature STREQUAL "threads" OR
           _ffmpeg_feature STREQUAL "pthreads" OR
           _ffmpeg_feature STREQUAL "libdl")
            _ffmpeg_native_dep_try_import(_ffmpeg_target _ffmpeg_found "${_ffmpeg_feature}")
            if(_ffmpeg_found)
                list(APPEND _ffmpeg_targets "${_ffmpeg_target}")
                list(APPEND _ffmpeg_found_features "${_ffmpeg_feature}")
            else()
                list(APPEND _ffmpeg_missing "${_ffmpeg_feature}")
            endif()
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_targets)
    list(REMOVE_DUPLICATES _ffmpeg_found_features)
    list(REMOVE_DUPLICATES _ffmpeg_missing)
    list(SORT _ffmpeg_found_features)
    list(SORT _ffmpeg_missing)
    set(FFMPEG_NATIVE_FOUND_EXTERNAL_DEPENDENCIES "${_ffmpeg_found_features}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_MISSING_EXTERNAL_DEPENDENCIES "${_ffmpeg_missing}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_DEPENDENCY_TARGETS "${_ffmpeg_targets}" PARENT_SCOPE)
    if(_ffmpeg_missing AND FFMPEG_NATIVE_REQUIRE_EXTERNAL_DEPENDENCIES)
        string(REPLACE ";" ", " _ffmpeg_missing_text "${_ffmpeg_missing}")
        message(FATAL_ERROR "Native FFmpeg dependencies were enabled but not found: ${_ffmpeg_missing_text}")
    endif()

    set(_ffmpeg_dep_file "${CMAKE_CURRENT_BINARY_DIR}/ffmpeg-native/FFmpegNativeDependencies.cmake")
    set(_ffmpeg_content "# Generated by ffmpeg-cmake native backend.\n\n")
    set(_ffmpeg_find_packages)
    foreach(_ffmpeg_target IN LISTS _ffmpeg_targets)
        get_target_property(_ffmpeg_link_libraries "${_ffmpeg_target}" INTERFACE_LINK_LIBRARIES)
        foreach(_ffmpeg_link_item IN LISTS _ffmpeg_link_libraries)
            _ffmpeg_native_dep_package_for_link(_ffmpeg_find_package "${_ffmpeg_link_item}")
            if(_ffmpeg_find_package)
                list(APPEND _ffmpeg_find_packages "${_ffmpeg_find_package}")
            endif()
        endforeach()
    endforeach()
    if(_ffmpeg_find_packages)
        list(REMOVE_DUPLICATES _ffmpeg_find_packages)
        string(APPEND _ffmpeg_content "include(CMakeFindDependencyMacro)\n")
        if(FFMPEG_BUILD_STATIC AND NOT WIN32)
            string(APPEND _ffmpeg_content "set(_FFmpegNativeDependency_FIND_LIBRARY_SUFFIXES \${CMAKE_FIND_LIBRARY_SUFFIXES})\n")
            string(APPEND _ffmpeg_content "if(CMAKE_STATIC_LIBRARY_SUFFIX)\n")
            string(APPEND _ffmpeg_content "    set(CMAKE_FIND_LIBRARY_SUFFIXES \"\${CMAKE_STATIC_LIBRARY_SUFFIX}\" \${CMAKE_FIND_LIBRARY_SUFFIXES})\n")
            string(APPEND _ffmpeg_content "    list(REMOVE_DUPLICATES CMAKE_FIND_LIBRARY_SUFFIXES)\n")
            string(APPEND _ffmpeg_content "endif()\n")
        endif()
        foreach(_ffmpeg_find_package IN LISTS _ffmpeg_find_packages)
            string(APPEND _ffmpeg_content "find_dependency(${_ffmpeg_find_package})\n")
        endforeach()
        if(FFMPEG_BUILD_STATIC AND NOT WIN32)
            string(APPEND _ffmpeg_content "set(CMAKE_FIND_LIBRARY_SUFFIXES \${_FFmpegNativeDependency_FIND_LIBRARY_SUFFIXES})\n")
            string(APPEND _ffmpeg_content "unset(_FFmpegNativeDependency_FIND_LIBRARY_SUFFIXES)\n")
        endif()
        string(APPEND _ffmpeg_content "\n")
    endif()
    foreach(_ffmpeg_target IN LISTS _ffmpeg_targets)
        _ffmpeg_native_dep_write_target(_ffmpeg_content "${_ffmpeg_target}")
    endforeach()
    _ffmpeg_native_write_file_if_changed("${_ffmpeg_dep_file}" "${_ffmpeg_content}")

    set(${_out_file} "${_ffmpeg_dep_file}" PARENT_SCOPE)
    set(${_out_targets} "${_ffmpeg_targets}" PARENT_SCOPE)
endfunction()
