include_guard(GLOBAL)

include(FFmpegPkgConfigTargets)

option(FFMPEG_NATIVE_REQUIRE_EXTERNAL_DEPENDENCIES "Stop configure when a requested native FFmpeg dependency cannot be found or imported." ON)

function(_ffmpeg_native_dep_var_suffix _out _name)
    string(TOUPPER "${_name}" _ffmpeg_suffix)
    string(REGEX REPLACE "[^A-Z0-9_]" "_" _ffmpeg_suffix "${_ffmpeg_suffix}")
    set(${_out} "${_ffmpeg_suffix}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_escape _out _value)
    string(REPLACE "\\" "\\\\" _ffmpeg_value "${_value}")
    string(REPLACE "\"" "\\\"" _ffmpeg_value "${_ffmpeg_value}")
    set(${_out} "${_ffmpeg_value}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_append_list _out _var)
    string(APPEND ${_out} "    set(${_var}\n")
    foreach(_ffmpeg_value IN LISTS ARGN)
        _ffmpeg_native_dep_escape(_ffmpeg_escaped "${_ffmpeg_value}")
        string(APPEND ${_out} "        \"${_ffmpeg_escaped}\"\n")
    endforeach()
    string(APPEND ${_out} "    )\n")
    set(${_out} "${${_out}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_split_words _out _text)
    set(_ffmpeg_text "${_text}")
    set(_ffmpeg_words)
    foreach(_ffmpeg_unused RANGE 0 64)
        string(STRIP "${_ffmpeg_text}" _ffmpeg_text)
        if(_ffmpeg_text STREQUAL "")
            break()
        elseif(_ffmpeg_text MATCHES "^\"([^\"]*)\"[ \t]*(.*)$")
            list(APPEND _ffmpeg_words "${CMAKE_MATCH_1}")
            set(_ffmpeg_text "${CMAKE_MATCH_2}")
        elseif(_ffmpeg_text MATCHES "^'([^']*)'[ \t]*(.*)$")
            list(APPEND _ffmpeg_words "${CMAKE_MATCH_1}")
            set(_ffmpeg_text "${CMAKE_MATCH_2}")
        elseif(_ffmpeg_text MATCHES "^([^ \t;&|{}()]+)[ \t]*(.*)$")
            list(APPEND _ffmpeg_words "${CMAKE_MATCH_1}")
            set(_ffmpeg_text "${CMAKE_MATCH_2}")
        else()
            break()
        endif()
    endforeach()

    set(${_out} "${_ffmpeg_words}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_add_pkg_rule _feature _pkg)
    if(_feature STREQUAL "" OR _pkg STREQUAL "")
        return()
    endif()
    if(_pkg MATCHES "^([A-Za-z0-9_.+-]+)")
        set(_pkg "${CMAKE_MATCH_1}")
    endif()
    if(_feature MATCHES "[^A-Za-z0-9_]" OR _feature MATCHES "^\\$" OR _pkg MATCHES "\\$")
        return()
    endif()

    _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_feature}")
    set(_ffmpeg_var "FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix}")
    list(APPEND ${_ffmpeg_var} "${_pkg}")
    list(REMOVE_DUPLICATES ${_ffmpeg_var})
    set(${_ffmpeg_var} "${${_ffmpeg_var}}" PARENT_SCOPE)

    set(FFMPEG_NATIVE_DEP_FEATURES "${FFMPEG_NATIVE_DEP_FEATURES};${_feature}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_collect_pkg_rules)
    file(STRINGS "${FFMPEG_SOURCE_DIR}/configure" _ffmpeg_lines)
    set(FFMPEG_NATIVE_DEP_FEATURES)
    foreach(_ffmpeg_line IN LISTS _ffmpeg_lines)
        set(_ffmpeg_rest "${_ffmpeg_line}")
        foreach(_ffmpeg_unused RANGE 0 8)
            if(_ffmpeg_rest MATCHES "((require|check|test)_pkg_config(_[A-Za-z0-9_]+)?)[ \t]+(.+)$")
                set(_ffmpeg_after "${CMAKE_MATCH_4}")
                _ffmpeg_native_dep_split_words(_ffmpeg_words "${_ffmpeg_after}")
                list(LENGTH _ffmpeg_words _ffmpeg_word_count)
                if(_ffmpeg_word_count GREATER 1)
                    list(GET _ffmpeg_words 0 _ffmpeg_feature)
                    list(GET _ffmpeg_words 1 _ffmpeg_pkg)
                    _ffmpeg_native_dep_add_pkg_rule("${_ffmpeg_feature}" "${_ffmpeg_pkg}")
                endif()
                set(_ffmpeg_rest "${_ffmpeg_after}")
            else()
                break()
            endif()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES FFMPEG_NATIVE_DEP_FEATURES)
    foreach(_ffmpeg_feature IN LISTS FFMPEG_NATIVE_DEP_FEATURES)
        _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_ffmpeg_feature}")
        set(FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix} "${FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix}}" PARENT_SCOPE)
    endforeach()
    set(FFMPEG_NATIVE_DEP_FEATURES "${FFMPEG_NATIVE_DEP_FEATURES}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_create_pkg_target _out_target _out_found _feature _pkg)
    set(_ffmpeg_target "FFmpegExternal::${_feature}")
    if(TARGET "${_ffmpeg_target}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    _ffmpeg_pkg_config_path(_ffmpeg_pc_path "")
    _ffmpeg_pkg_config_output(_ffmpeg_unused _ffmpeg_exists "${_ffmpeg_pc_path}" --exists "${_pkg}")
    if(NOT _ffmpeg_exists EQUAL 0)
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} FALSE PARENT_SCOPE)
        return()
    endif()

    add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
    if(COMMAND ffmpeg_set_target_folder)
        ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
    endif()
    _ffmpeg_apply_pkg_config_target("${_ffmpeg_target}" "${_ffmpeg_pc_path}" "${FFMPEG_BUILD_STATIC}" "${_pkg}")
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_create_threads_target _out_target _out_found)
    set(_ffmpeg_target "FFmpegExternal::threads")
    if(NOT TARGET "${_ffmpeg_target}")
        find_package(Threads QUIET)
        if(NOT Threads_FOUND)
            set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
            set(${_out_found} FALSE PARENT_SCOPE)
            return()
        endif()
        add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
        if(COMMAND ffmpeg_set_target_folder)
            ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
        endif()
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_LINK_LIBRARIES "Threads::Threads")
    endif()
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_create_libdl_target _out_target _out_found)
    set(_ffmpeg_target "FFmpegExternal::libdl")
    if(NOT TARGET "${_ffmpeg_target}")
        add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
        if(COMMAND ffmpeg_set_target_folder)
            ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
        endif()
        if(CMAKE_DL_LIBS)
            set_target_properties("${_ffmpeg_target}" PROPERTIES
                INTERFACE_LINK_LIBRARIES "${CMAKE_DL_LIBS}")
        endif()
    endif()
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_sdl2_candidate_dirs _out)
    set(_ffmpeg_dirs)
    if(SDL2_DIR)
        list(APPEND _ffmpeg_dirs "${SDL2_DIR}")
    endif()

    foreach(_ffmpeg_prefix IN LISTS CMAKE_PREFIX_PATH)
        if(_ffmpeg_prefix STREQUAL "")
            continue()
        endif()
        foreach(_ffmpeg_suffix IN ITEMS "" lib/cmake/SDL2 lib64/cmake/SDL2)
            if(_ffmpeg_suffix STREQUAL "")
                set(_ffmpeg_dir "${_ffmpeg_prefix}")
            else()
                set(_ffmpeg_dir "${_ffmpeg_prefix}/${_ffmpeg_suffix}")
            endif()
            if(EXISTS "${_ffmpeg_dir}/SDL2Config.cmake")
                list(APPEND _ffmpeg_dirs "${_ffmpeg_dir}")
            endif()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_dirs)
    set(${_out} "${_ffmpeg_dirs}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_sdl2_include_config _target _dir _export _config)
    if(NOT TARGET "${_target}")
        return()
    endif()

    get_target_property(_ffmpeg_aliased "${_target}" ALIASED_TARGET)
    if(_ffmpeg_aliased)
        return()
    endif()

    string(TOUPPER "${_config}" _ffmpeg_config_uc)
    get_target_property(_ffmpeg_imported_configs "${_target}" IMPORTED_CONFIGURATIONS)
    if(_ffmpeg_imported_configs)
        list(FIND _ffmpeg_imported_configs "${_ffmpeg_config_uc}" _ffmpeg_existing_config)
        if(NOT _ffmpeg_existing_config EQUAL -1)
            return()
        endif()
    endif()

    string(TOLOWER "${_config}" _ffmpeg_config_lc)
    set(_ffmpeg_config_file "${_dir}/${_export}-${_ffmpeg_config_lc}.cmake")
    if(NOT EXISTS "${_ffmpeg_config_file}")
        return()
    endif()

    get_filename_component(_IMPORT_PREFIX "${_dir}/../../../" ABSOLUTE)
    include("${_ffmpeg_config_file}")
    unset(_IMPORT_PREFIX)
endfunction()

function(_ffmpeg_native_dep_augment_sdl2_configs)
    _ffmpeg_native_dep_sdl2_candidate_dirs(_ffmpeg_sdl2_dirs)
    foreach(_ffmpeg_dir IN LISTS _ffmpeg_sdl2_dirs)
        foreach(_ffmpeg_config IN ITEMS Debug Release RelWithDebInfo MinSizeRel)
            _ffmpeg_native_dep_sdl2_include_config(SDL2::SDL2-static "${_ffmpeg_dir}" SDL2staticTargets "${_ffmpeg_config}")
            _ffmpeg_native_dep_sdl2_include_config(SDL2::SDL2main "${_ffmpeg_dir}" SDL2mainTargets "${_ffmpeg_config}")
            _ffmpeg_native_dep_sdl2_include_config(SDL2::SDL2 "${_ffmpeg_dir}" SDL2Targets "${_ffmpeg_config}")
        endforeach()
    endforeach()
endfunction()

function(_ffmpeg_native_dep_create_sdl2_target _out_target _out_found)
    set(_ffmpeg_target "FFmpegExternal::sdl2")
    if(TARGET "${_ffmpeg_target}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    find_package(SDL2 CONFIG QUIET)
    _ffmpeg_native_dep_augment_sdl2_configs()

    set(_ffmpeg_sdl2_link_targets)
    if(WIN32 AND TARGET SDL2::SDL2main)
        list(APPEND _ffmpeg_sdl2_link_targets SDL2::SDL2main)
    endif()
    if(FFMPEG_BUILD_STATIC AND TARGET SDL2::SDL2-static)
        list(APPEND _ffmpeg_sdl2_link_targets SDL2::SDL2-static)
    elseif(TARGET SDL2::SDL2)
        list(APPEND _ffmpeg_sdl2_link_targets SDL2::SDL2)
    elseif(TARGET SDL2::SDL2-static)
        list(APPEND _ffmpeg_sdl2_link_targets SDL2::SDL2-static)
    endif()

    if(_ffmpeg_sdl2_link_targets)
        add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
        if(COMMAND ffmpeg_set_target_folder)
            ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
        endif()
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_LINK_LIBRARIES "${_ffmpeg_sdl2_link_targets}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    set(_ffmpeg_sdl2_include_dirs ${SDL2_INCLUDE_DIRS})
    if(NOT _ffmpeg_sdl2_include_dirs AND SDL2_INCLUDE_DIR)
        set(_ffmpeg_sdl2_include_dirs "${SDL2_INCLUDE_DIR}")
    endif()

    set(_ffmpeg_sdl2_libraries ${SDL2_LIBRARIES})
    if(NOT _ffmpeg_sdl2_libraries AND SDL2_LIBRARY)
        set(_ffmpeg_sdl2_libraries "${SDL2_LIBRARY}")
    endif()
    if(WIN32 AND SDL2MAIN_LIBRARY)
        list(PREPEND _ffmpeg_sdl2_libraries "${SDL2MAIN_LIBRARY}")
    endif()

    if(_ffmpeg_sdl2_libraries)
        add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
        if(COMMAND ffmpeg_set_target_folder)
            ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
        endif()
        set_target_properties("${_ffmpeg_target}" PROPERTIES
            INTERFACE_LINK_LIBRARIES "${_ffmpeg_sdl2_libraries}")
        if(_ffmpeg_sdl2_include_dirs)
            set_target_properties("${_ffmpeg_target}" PROPERTIES
                INTERFACE_INCLUDE_DIRECTORIES "${_ffmpeg_sdl2_include_dirs}")
        endif()
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} FALSE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_cmake_fallback _out_package _out_targets _feature)
    set(_ffmpeg_package)
    set(_ffmpeg_targets)

    if(_feature STREQUAL "zlib")
        set(_ffmpeg_package ZLIB)
        set(_ffmpeg_targets ZLIB::ZLIB)
    elseif(_feature STREQUAL "bzlib")
        set(_ffmpeg_package BZip2)
        set(_ffmpeg_targets BZip2::BZip2)
    elseif(_feature STREQUAL "lzma")
        set(_ffmpeg_package LibLZMA)
        set(_ffmpeg_targets LibLZMA::LibLZMA)
    elseif(_feature STREQUAL "iconv")
        set(_ffmpeg_package Iconv)
        set(_ffmpeg_targets Iconv::Iconv)
    elseif(_feature STREQUAL "openssl")
        set(_ffmpeg_package OpenSSL)
        set(_ffmpeg_targets OpenSSL::SSL OpenSSL::Crypto)
    elseif(_feature STREQUAL "libxml2")
        set(_ffmpeg_package LibXml2)
        set(_ffmpeg_targets LibXml2::LibXml2)
    elseif(_feature STREQUAL "vulkan")
        set(_ffmpeg_package Vulkan)
        set(_ffmpeg_targets Vulkan::Vulkan)
    elseif(_feature STREQUAL "opencl")
        set(_ffmpeg_package OpenCL)
        set(_ffmpeg_targets OpenCL::OpenCL)
    elseif(_feature STREQUAL "sdl2")
        set(_ffmpeg_package SDL2)
        set(_ffmpeg_targets FFmpegExternal::sdl2)
    endif()

    set(${_out_package} "${_ffmpeg_package}" PARENT_SCOPE)
    set(${_out_targets} "${_ffmpeg_targets}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_find_package _package)
    if(FFMPEG_BUILD_STATIC AND NOT WIN32)
        set(_ffmpeg_saved_suffixes ${CMAKE_FIND_LIBRARY_SUFFIXES})
        set(CMAKE_FIND_LIBRARY_SUFFIXES "${CMAKE_STATIC_LIBRARY_SUFFIX}" ${_ffmpeg_saved_suffixes})
        list(REMOVE_DUPLICATES CMAKE_FIND_LIBRARY_SUFFIXES)
        find_package("${_package}" QUIET)
        set(CMAKE_FIND_LIBRARY_SUFFIXES ${_ffmpeg_saved_suffixes})
    else()
        find_package("${_package}" QUIET)
    endif()
endfunction()

function(_ffmpeg_native_dep_create_cmake_target _out_target _out_found _feature)
    set(_ffmpeg_target "FFmpegExternal::${_feature}")
    if(TARGET "${_ffmpeg_target}")
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} TRUE PARENT_SCOPE)
        return()
    endif()

    _ffmpeg_native_dep_cmake_fallback(_ffmpeg_package _ffmpeg_link_targets "${_feature}")
    if(NOT _ffmpeg_package)
        set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
        set(${_out_found} FALSE PARENT_SCOPE)
        return()
    endif()

    _ffmpeg_native_dep_find_package("${_ffmpeg_package}")
    foreach(_ffmpeg_link_target IN LISTS _ffmpeg_link_targets)
        if(NOT TARGET "${_ffmpeg_link_target}")
            set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
            set(${_out_found} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()

    add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
    if(COMMAND ffmpeg_set_target_folder)
        ffmpeg_set_target_folder("${_ffmpeg_target}" "FFmpeg/Dependencies")
    endif()
    set_target_properties("${_ffmpeg_target}" PROPERTIES
        INTERFACE_LINK_LIBRARIES "${_ffmpeg_link_targets}")
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} TRUE PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_try_import _out_target _out_found _feature)
    if(_feature STREQUAL "threads" OR _feature STREQUAL "pthreads")
        _ffmpeg_native_dep_create_threads_target(_ffmpeg_target _ffmpeg_found)
    elseif(_feature STREQUAL "libdl")
        _ffmpeg_native_dep_create_libdl_target(_ffmpeg_target _ffmpeg_found)
    elseif(_feature STREQUAL "sdl2")
        _ffmpeg_native_dep_create_sdl2_target(_ffmpeg_target _ffmpeg_found)
    else()
        _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_feature}")
        set(_ffmpeg_pkgs "${FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix}}")
        set(_ffmpeg_found FALSE)
        foreach(_ffmpeg_pkg IN LISTS _ffmpeg_pkgs)
            _ffmpeg_native_dep_create_pkg_target(_ffmpeg_target _ffmpeg_found "${_feature}" "${_ffmpeg_pkg}")
            if(_ffmpeg_found)
                break()
            endif()
        endforeach()
        if(NOT _ffmpeg_found)
            _ffmpeg_native_dep_create_cmake_target(_ffmpeg_target _ffmpeg_found "${_feature}")
        endif()
    endif()

    if(NOT DEFINED _ffmpeg_target)
        set(_ffmpeg_target "FFmpegExternal::${_feature}")
    endif()
    set(${_out_target} "${_ffmpeg_target}" PARENT_SCOPE)
    set(${_out_found} "${_ffmpeg_found}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_write_target _content_var _target)
    string(REPLACE "FFmpegExternal::" "" _ffmpeg_feature "${_target}")
    _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_ffmpeg_feature}")
    string(APPEND ${_content_var} "if(NOT TARGET \"${_target}\")\n")
    string(APPEND ${_content_var} "    add_library(\"${_target}\" INTERFACE IMPORTED)\n")

    set(_ffmpeg_property_text)
    foreach(_ffmpeg_property IN ITEMS
            INTERFACE_INCLUDE_DIRECTORIES
            INTERFACE_COMPILE_DEFINITIONS
            INTERFACE_COMPILE_OPTIONS
            INTERFACE_LINK_DIRECTORIES
            INTERFACE_LINK_LIBRARIES)
        get_target_property(_ffmpeg_values "${_target}" "${_ffmpeg_property}")
        if(_ffmpeg_values AND NOT _ffmpeg_values MATCHES "-NOTFOUND$")
            set(_ffmpeg_var "_FFmpegExternal_${_ffmpeg_suffix}_${_ffmpeg_property}")
            _ffmpeg_native_dep_append_list(${_content_var} "${_ffmpeg_var}" ${_ffmpeg_values})
            string(APPEND _ffmpeg_property_text "        ${_ffmpeg_property} \"\${${_ffmpeg_var}}\"\n")
        endif()
    endforeach()

    if(_ffmpeg_property_text)
        string(APPEND ${_content_var} "    set_target_properties(\"${_target}\" PROPERTIES\n")
        string(APPEND ${_content_var} "${_ffmpeg_property_text}")
        string(APPEND ${_content_var} "    )\n")
    endif()
    string(APPEND ${_content_var} "endif()\n\n")
    set(${_content_var} "${${_content_var}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_native_dep_package_for_link _out _link_item)
    set(_ffmpeg_package)
    if(_link_item STREQUAL "Threads::Threads")
        set(_ffmpeg_package Threads)
    elseif(_link_item STREQUAL "ZLIB::ZLIB")
        set(_ffmpeg_package ZLIB)
    elseif(_link_item STREQUAL "BZip2::BZip2")
        set(_ffmpeg_package BZip2)
    elseif(_link_item STREQUAL "LibLZMA::LibLZMA")
        set(_ffmpeg_package LibLZMA)
    elseif(_link_item STREQUAL "Iconv::Iconv")
        set(_ffmpeg_package Iconv)
    elseif(_link_item MATCHES "^OpenSSL::")
        set(_ffmpeg_package OpenSSL)
    elseif(_link_item STREQUAL "LibXml2::LibXml2")
        set(_ffmpeg_package LibXml2)
    elseif(_link_item STREQUAL "Vulkan::Vulkan")
        set(_ffmpeg_package Vulkan)
    elseif(_link_item STREQUAL "OpenCL::OpenCL")
        set(_ffmpeg_package OpenCL)
    elseif(_link_item MATCHES "^SDL2::")
        set(_ffmpeg_package SDL2)
    endif()
    set(${_out} "${_ffmpeg_package}" PARENT_SCOPE)
endfunction()

function(ffmpeg_native_import_dependencies _out_file _out_targets)
    _ffmpeg_native_dep_collect_pkg_rules()

    set(_ffmpeg_enabled_features
        ${FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES}
        ${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES})
    list(REMOVE_DUPLICATES _ffmpeg_enabled_features)

    set(_ffmpeg_targets)
    set(_ffmpeg_found_features)
    set(_ffmpeg_missing)
    foreach(_ffmpeg_feature IN LISTS _ffmpeg_enabled_features)
        _ffmpeg_native_dep_var_suffix(_ffmpeg_suffix "${_ffmpeg_feature}")
        _ffmpeg_native_dep_cmake_fallback(_ffmpeg_cmake_package _ffmpeg_unused_targets "${_ffmpeg_feature}")
        if(DEFINED FFMPEG_NATIVE_DEP_PKGS_${_ffmpeg_suffix} OR
           _ffmpeg_cmake_package OR
           _ffmpeg_feature STREQUAL "threads" OR
           _ffmpeg_feature STREQUAL "pthreads" OR
           _ffmpeg_feature STREQUAL "libdl")
            _ffmpeg_native_dep_try_import(_ffmpeg_target _ffmpeg_found "${_ffmpeg_feature}")
            if(_ffmpeg_found)
                list(APPEND _ffmpeg_targets "${_ffmpeg_target}")
                list(APPEND _ffmpeg_found_features "${_ffmpeg_feature}")
            else()
                list(APPEND _ffmpeg_missing "${_ffmpeg_feature}")
            endif()
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_targets)
    list(REMOVE_DUPLICATES _ffmpeg_found_features)
    list(REMOVE_DUPLICATES _ffmpeg_missing)
    list(SORT _ffmpeg_found_features)
    list(SORT _ffmpeg_missing)
    set(FFMPEG_NATIVE_FOUND_EXTERNAL_DEPENDENCIES "${_ffmpeg_found_features}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_MISSING_EXTERNAL_DEPENDENCIES "${_ffmpeg_missing}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_DEPENDENCY_TARGETS "${_ffmpeg_targets}" PARENT_SCOPE)
    if(_ffmpeg_missing AND FFMPEG_NATIVE_REQUIRE_EXTERNAL_DEPENDENCIES)
        string(REPLACE ";" ", " _ffmpeg_missing_text "${_ffmpeg_missing}")
        message(FATAL_ERROR "Native FFmpeg dependencies were enabled but not found: ${_ffmpeg_missing_text}")
    endif()

    set(_ffmpeg_dep_file "${CMAKE_CURRENT_BINARY_DIR}/ffmpeg-native/FFmpegNativeDependencies.cmake")
    set(_ffmpeg_content "# Generated by ffmpeg-cmake native backend.\n\n")
    set(_ffmpeg_find_packages)
    foreach(_ffmpeg_target IN LISTS _ffmpeg_targets)
        get_target_property(_ffmpeg_link_libraries "${_ffmpeg_target}" INTERFACE_LINK_LIBRARIES)
        foreach(_ffmpeg_link_item IN LISTS _ffmpeg_link_libraries)
            _ffmpeg_native_dep_package_for_link(_ffmpeg_find_package "${_ffmpeg_link_item}")
            if(_ffmpeg_find_package)
                list(APPEND _ffmpeg_find_packages "${_ffmpeg_find_package}")
            endif()
        endforeach()
    endforeach()
    if(_ffmpeg_find_packages)
        list(REMOVE_DUPLICATES _ffmpeg_find_packages)
        string(APPEND _ffmpeg_content "include(CMakeFindDependencyMacro)\n")
        if(FFMPEG_BUILD_STATIC AND NOT WIN32)
            string(APPEND _ffmpeg_content "set(_FFmpegNativeDependency_FIND_LIBRARY_SUFFIXES \${CMAKE_FIND_LIBRARY_SUFFIXES})\n")
            string(APPEND _ffmpeg_content "if(CMAKE_STATIC_LIBRARY_SUFFIX)\n")
            string(APPEND _ffmpeg_content "    set(CMAKE_FIND_LIBRARY_SUFFIXES \"\${CMAKE_STATIC_LIBRARY_SUFFIX}\" \${CMAKE_FIND_LIBRARY_SUFFIXES})\n")
            string(APPEND _ffmpeg_content "    list(REMOVE_DUPLICATES CMAKE_FIND_LIBRARY_SUFFIXES)\n")
            string(APPEND _ffmpeg_content "endif()\n")
        endif()
        foreach(_ffmpeg_find_package IN LISTS _ffmpeg_find_packages)
            string(APPEND _ffmpeg_content "find_dependency(${_ffmpeg_find_package})\n")
        endforeach()
        if(FFMPEG_BUILD_STATIC AND NOT WIN32)
            string(APPEND _ffmpeg_content "set(CMAKE_FIND_LIBRARY_SUFFIXES \${_FFmpegNativeDependency_FIND_LIBRARY_SUFFIXES})\n")
            string(APPEND _ffmpeg_content "unset(_FFmpegNativeDependency_FIND_LIBRARY_SUFFIXES)\n")
        endif()
        string(APPEND _ffmpeg_content "\n")
    endif()
    foreach(_ffmpeg_target IN LISTS _ffmpeg_targets)
        _ffmpeg_native_dep_write_target(_ffmpeg_content "${_ffmpeg_target}")
    endforeach()
    _ffmpeg_native_write_file_if_changed("${_ffmpeg_dep_file}" "${_ffmpeg_content}")

    set(${_out_file} "${_ffmpeg_dep_file}" PARENT_SCOPE)
    set(${_out_targets} "${_ffmpeg_targets}" PARENT_SCOPE)
endfunction()
