include_guard(GLOBAL)

function(_ffmpeg_report_value _label _value)
    if("${_value}" STREQUAL "")
        set(_value "none")
    endif()
    message(STATUS "  ${_label}: ${_value}")
endfunction()

function(_ffmpeg_report_list _label _values)
    if("${_values}" STREQUAL "")
        set(_ffmpeg_text "none")
    else()
        string(REPLACE ";" ", " _ffmpeg_text "${_values}")
    endif()
    message(STATUS "  ${_label}: ${_ffmpeg_text}")
endfunction()

function(_ffmpeg_report_bool _label _value)
    if(${_value})
        message(STATUS "  ${_label}: yes")
    else()
        message(STATUS "  ${_label}: no")
    endif()
endfunction()

function(_ffmpeg_report_append_components _out _var _suffix)
    foreach(_ffmpeg_name IN LISTS ${_var})
        if(NOT _ffmpeg_name STREQUAL "")
            if(_ffmpeg_name MATCHES "_${_suffix}$")
                list(APPEND ${_out} "${_ffmpeg_name}")
            else()
                list(APPEND ${_out} "${_ffmpeg_name}_${_suffix}")
            endif()
        endif()
    endforeach()
    set(${_out} "${${_out}}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_report_requested_features _out)
    set(_ffmpeg_requested ${FFMPEG_ENABLE_FEATURES} ${FFMPEG_ENABLE_EXTERNAL_LIBRARIES})
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_ENCODERS encoder)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_DECODERS decoder)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_HWACCELS hwaccel)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_MUXERS muxer)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_DEMUXERS demuxer)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_PARSERS parser)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_BSFS bsf)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_PROTOCOLS protocol)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_INDEVS indev)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_OUTDEVS outdev)
    _ffmpeg_report_append_components(_ffmpeg_requested FFMPEG_ENABLE_FILTERS filter)
    list(REMOVE_DUPLICATES _ffmpeg_requested)
    list(SORT _ffmpeg_requested)
    set(${_out} "${_ffmpeg_requested}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_report_disabled_features _out)
    set(_ffmpeg_disabled ${FFMPEG_DISABLE_FEATURES} ${FFMPEG_DISABLE_EXTERNAL_LIBRARIES})
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_ENCODERS encoder)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_DECODERS decoder)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_HWACCELS hwaccel)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_MUXERS muxer)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_DEMUXERS demuxer)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_PARSERS parser)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_BSFS bsf)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_PROTOCOLS protocol)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_INDEVS indev)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_OUTDEVS outdev)
    _ffmpeg_report_append_components(_ffmpeg_disabled FFMPEG_DISABLE_FILTERS filter)
    list(REMOVE_DUPLICATES _ffmpeg_disabled)
    list(SORT _ffmpeg_disabled)
    set(${_out} "${_ffmpeg_disabled}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_report_build_libraries _out_enabled _out_disabled)
    set(_ffmpeg_enabled)
    set(_ffmpeg_disabled)
    foreach(_ffmpeg_lib IN ITEMS AVCODEC AVDEVICE AVFILTER AVFORMAT AVUTIL SWRESAMPLE SWSCALE)
        string(TOLOWER "${_ffmpeg_lib}" _ffmpeg_lib_lc)
        if(FFMPEG_ENABLE_${_ffmpeg_lib})
            list(APPEND _ffmpeg_enabled "${_ffmpeg_lib_lc}")
        else()
            list(APPEND _ffmpeg_disabled "${_ffmpeg_lib_lc}")
        endif()
    endforeach()
    set(${_out_enabled} "${_ffmpeg_enabled}" PARENT_SCOPE)
    set(${_out_disabled} "${_ffmpeg_disabled}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_report_installed_import)
    if(NOT FFMPEG_FIND_INSTALLED)
        return()
    endif()

    set(_ffmpeg_missing)
    foreach(_ffmpeg_component IN LISTS FFMPEG_IMPORT_COMPONENTS)
        if(NOT FFmpeg_${_ffmpeg_component}_FOUND)
            list(APPEND _ffmpeg_missing "${_ffmpeg_component}")
        endif()
    endforeach()

    message(STATUS "")
    message(STATUS " Installed FFmpeg import:")
    _ffmpeg_report_bool("Use static pkg-config closure" "${FFmpeg_USE_STATIC_LIBS}")
    _ffmpeg_report_value("FFmpeg root" "${FFmpeg_ROOT}")
    _ffmpeg_report_value("Version" "${FFmpeg_VERSION}")
    _ffmpeg_report_list("Found components" "${FFmpeg_COMPONENTS}")
    _ffmpeg_report_list("Missing components" "${_ffmpeg_missing}")
    _ffmpeg_report_list("Imported targets" "${FFmpeg_TARGETS}")
endfunction()

function(_ffmpeg_report_source_build)
    if(NOT FFMPEG_BUILD_FROM_SOURCE)
        return()
    endif()

    _ffmpeg_report_build_libraries(_ffmpeg_enabled_libraries _ffmpeg_disabled_libraries)
    _ffmpeg_report_requested_features(_ffmpeg_requested_features)
    _ffmpeg_report_disabled_features(_ffmpeg_disabled_features)
    if(FFMPEG_EFFECTIVE_BUILD_BACKEND STREQUAL "NATIVE_CMAKE" AND FFMPEG_NATIVE_COMPONENTS)
        set(_ffmpeg_enabled_libraries "${FFMPEG_NATIVE_COMPONENTS}")
        set(_ffmpeg_disabled_libraries)
        foreach(_ffmpeg_component IN LISTS FFMPEG_IMPORT_COMPONENTS)
            if(NOT _ffmpeg_component IN_LIST _ffmpeg_enabled_libraries)
                list(APPEND _ffmpeg_disabled_libraries "${_ffmpeg_component}")
            endif()
        endforeach()
    endif()

    message(STATUS "")
    message(STATUS " Source FFmpeg build:")
    _ffmpeg_report_value("Source directory" "${FFMPEG_SOURCE_DIR}")
    _ffmpeg_report_value("Backend" "${FFMPEG_EFFECTIVE_BUILD_BACKEND}")
    _ffmpeg_report_value("Install prefix" "${FFMPEG_INSTALL_PREFIX}")
    _ffmpeg_report_bool("Static libraries" "${FFMPEG_BUILD_STATIC}")
    _ffmpeg_report_bool("Shared libraries" "${FFMPEG_BUILD_SHARED}")
    _ffmpeg_report_bool("Programs" "${FFMPEG_BUILD_PROGRAMS}")
    _ffmpeg_report_bool("Documentation" "${FFMPEG_BUILD_DOC}")
    set(_ffmpeg_autodetect ON)
    if(FFMPEG_DISABLE_AUTODETECT)
        set(_ffmpeg_autodetect OFF)
    endif()
    _ffmpeg_report_bool("Autodetect" "${_ffmpeg_autodetect}")
    _ffmpeg_report_list("Enabled FFmpeg libraries" "${_ffmpeg_enabled_libraries}")
    _ffmpeg_report_list("Disabled FFmpeg libraries" "${_ffmpeg_disabled_libraries}")
    _ffmpeg_report_bool("GPL" "${FFMPEG_ENABLE_GPL}")
    _ffmpeg_report_bool("Version3" "${FFMPEG_ENABLE_VERSION3}")
    _ffmpeg_report_bool("Nonfree" "${FFMPEG_ENABLE_NONFREE}")
    _ffmpeg_report_list("Requested feature enables" "${_ffmpeg_requested_features}")
    _ffmpeg_report_list("Requested feature disables" "${_ffmpeg_disabled_features}")
    _ffmpeg_report_value("Assembler (--as)" "${FFMPEG_AS}")
    _ffmpeg_report_value("x86 assembler (--x86asmexe)" "${FFMPEG_X86ASM}")

    if(FFMPEG_EFFECTIVE_BUILD_BACKEND STREQUAL "OFFICIAL_CONFIGURE")
        _ffmpeg_report_value("Configure shell" "${FFMPEG_CONFIGURE_SHELL}")
        _ffmpeg_report_value("Make program" "${FFMPEG_MAKE_PROGRAM}")
        _ffmpeg_report_list("Configure options" "${FFMPEG_OFFICIAL_CONFIGURE_OPTIONS}")
        _ffmpeg_report_value("Not-found dependencies" "resolved by FFmpeg configure during the external configure step")
    elseif(FFMPEG_EFFECTIVE_BUILD_BACKEND STREQUAL "NATIVE_CMAKE")
        _ffmpeg_report_value("Native license" "${FFMPEG_NATIVE_LICENSE}")
        _ffmpeg_report_list("Native components" "${FFMPEG_NATIVE_COMPONENTS}")
        _ffmpeg_report_list("Native enabled config features" "${FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES}")
        _ffmpeg_report_list("Native enabled component features" "${FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES}")
        _ffmpeg_report_list("Native enabled arch features" "${FFMPEG_NATIVE_ENABLED_ARCH_FEATURES}")
        _ffmpeg_report_list("Native enabled HAVE features" "${FFMPEG_NATIVE_ENABLED_HAVE_FEATURES}")
        _ffmpeg_report_list("Native external deps found" "${FFMPEG_NATIVE_FOUND_EXTERNAL_DEPENDENCIES}")
        _ffmpeg_report_list("Native external deps not found" "${FFMPEG_NATIVE_MISSING_EXTERNAL_DEPENDENCIES}")
        _ffmpeg_report_list("Native dependency targets" "${FFMPEG_NATIVE_DEPENDENCY_TARGETS}")
    endif()
endfunction()

function(ffmpeg_print_report)
    message(STATUS "")
    message(STATUS "=========================================================================")
    message(STATUS "= FFmpeg CMake report                                                   =")
    message(STATUS "=========================================================================")
    message(STATUS "")
    message(STATUS " General:")
    _ffmpeg_report_value("CMake version" "${CMAKE_VERSION}")
    _ffmpeg_report_value("System" "${CMAKE_SYSTEM_NAME}")
    _ffmpeg_report_value("Generator" "${CMAKE_GENERATOR}")
    _ffmpeg_report_value("Build type" "${CMAKE_BUILD_TYPE}")
    _ffmpeg_report_list("Configuration types" "${CMAKE_CONFIGURATION_TYPES}")
    _ffmpeg_report_value("C compiler" "${CMAKE_C_COMPILER}")
    _ffmpeg_report_list("CMAKE_PREFIX_PATH" "${CMAKE_PREFIX_PATH}")
    _ffmpeg_report_bool("CMAKE_POSITION_INDEPENDENT_CODE" "${CMAKE_POSITION_INDEPENDENT_CODE}")
    if(WIN32)
        _ffmpeg_report_value("CMAKE_DEBUG_POSTFIX" "${CMAKE_DEBUG_POSTFIX}")
    endif()
    if(MSVC)
        _ffmpeg_report_value("CMAKE_MSVC_RUNTIME_LIBRARY" "${CMAKE_MSVC_RUNTIME_LIBRARY}")
    endif()

    _ffmpeg_report_installed_import()
    _ffmpeg_report_source_build()

    message(STATUS "")
    message(STATUS "=========================================================================")
    message(STATUS "")
endfunction()
