include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/native/FFmpegNativeConfigureParser.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/native/FFmpegNativeComponents.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/native/FFmpegNativeFeatureGraph.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/native/FFmpegNativePlatform.cmake")

function(ffmpeg_native_autoconfig)
    _ffmpeg_native_expand_configure_list(_ffmpeg_config CONFIG_LIST)
    _ffmpeg_native_expand_configure_list(_ffmpeg_config_extra CONFIG_EXTRA)
    _ffmpeg_native_expand_configure_list(_ffmpeg_have HAVE_LIST)
    _ffmpeg_native_expand_configure_list(_ffmpeg_arch ARCH_LIST)
    _ffmpeg_native_expand_configure_list(_ffmpeg_external_gpl EXTERNAL_LIBRARY_GPL_LIST)
    _ffmpeg_native_expand_configure_list(_ffmpeg_external_nonfree EXTERNAL_LIBRARY_NONFREE_LIST)
    _ffmpeg_native_expand_configure_list(_ffmpeg_external_version3 EXTERNAL_LIBRARY_VERSION3_LIST)
    _ffmpeg_native_expand_configure_list(_ffmpeg_external_gplv3 EXTERNAL_LIBRARY_GPLV3_LIST)
    _ffmpeg_native_expand_configure_list(_ffmpeg_hwaccel_nonfree HWACCEL_LIBRARY_NONFREE_LIST)
    list(APPEND _ffmpeg_external_nonfree ${_ffmpeg_hwaccel_nonfree})
    list(REMOVE_DUPLICATES _ffmpeg_external_nonfree)
    _ffmpeg_native_collect_component_lists()
    _ffmpeg_native_load_dependency_rules()
    _ffmpeg_native_detect_base_have()
    _ffmpeg_native_detect_arch()

    if(FFMPEG_NATIVE_EFFECTIVE_ENABLE_ASM)
        list(FIND _ffmpeg_enabled_have aligned_malloc _ffmpeg_has_aligned_malloc)
        list(FIND _ffmpeg_enabled_have memalign _ffmpeg_has_memalign)
        list(FIND _ffmpeg_enabled_have posix_memalign _ffmpeg_has_posix_memalign)
        if(_ffmpeg_has_aligned_malloc EQUAL -1 AND
           _ffmpeg_has_memalign EQUAL -1 AND
           _ffmpeg_has_posix_memalign EQUAL -1)
            message(FATAL_ERROR "Native FFmpeg assembly requires aligned memory allocation support. Provide _aligned_malloc/memalign/posix_memalign support or configure with -DFFMPEG_NATIVE_ENABLE_ASM=OFF.")
        endif()
    endif()

    set(_ffmpeg_all_config ${_ffmpeg_config} ${_ffmpeg_config_extra})
    set(_ffmpeg_all_have ${_ffmpeg_have})
    set(_ffmpeg_all_arch ${_ffmpeg_arch})
    set(_ffmpeg_all_components ${FFMPEG_NATIVE_ALL_COMPONENTS})
    list(REMOVE_DUPLICATES _ffmpeg_all_config)
    list(REMOVE_DUPLICATES _ffmpeg_all_have)
    list(REMOVE_DUPLICATES _ffmpeg_all_arch)

    set(_ffmpeg_enabled_config)
    set(_ffmpeg_explicit_config)
    set(_ffmpeg_enabled_components)
    set(_ffmpeg_explicit_components)
    set(_ffmpeg_explicit_have)
    set(_ffmpeg_explicit_arch)

    list(APPEND _ffmpeg_enabled_config
        runtime_cpudetect
        safe_bitstream_reader)

    if(NOT FFMPEG_DISABLE_AUTODETECT)
        list(APPEND _ffmpeg_enabled_config autodetect ${FFMPEG_NATIVE_DETECTED_CONFIG_FEATURES})
    endif()
    if(FFMPEG_BUILD_STATIC)
        list(APPEND _ffmpeg_enabled_config static)
    endif()
    if(FFMPEG_BUILD_SHARED)
        list(APPEND _ffmpeg_enabled_config shared)
    endif()
    if(FFMPEG_BUILD_SHARED OR CMAKE_POSITION_INDEPENDENT_CODE)
        list(APPEND _ffmpeg_enabled_config pic)
    endif()
    if(FFMPEG_ENABLE_GPL)
        list(APPEND _ffmpeg_enabled_config gpl)
    endif()
    if(FFMPEG_ENABLE_VERSION3)
        list(APPEND _ffmpeg_enabled_config version3)
    endif()
    if(FFMPEG_ENABLE_NONFREE)
        list(APPEND _ffmpeg_enabled_config nonfree)
    endif()
    if(FFMPEG_NATIVE_ENABLE_THREADS)
        list(APPEND _ffmpeg_enabled_config threads)
    endif()
    if(WIN32)
        list(APPEND _ffmpeg_enabled_config atomics_win32)
    else()
        list(APPEND _ffmpeg_enabled_config stdatomic)
    endif()
    if(FFMPEG_BUILD_PROGRAMS)
        if(FFMPEG_NATIVE_BUILD_FFMPEG)
            list(APPEND _ffmpeg_enabled_config ffmpeg)
            list(APPEND _ffmpeg_explicit_config ffmpeg)
        endif()
        if(FFMPEG_NATIVE_BUILD_FFPROBE)
            list(APPEND _ffmpeg_enabled_config ffprobe)
            list(APPEND _ffmpeg_explicit_config ffprobe)
        endif()
        if(FFMPEG_NATIVE_BUILD_FFPLAY)
            list(APPEND _ffmpeg_enabled_config ffplay sdl2)
            list(APPEND _ffmpeg_explicit_config ffplay sdl2)
        endif()
    endif()

    if(FFMPEG_NATIVE_BUILD_EXAMPLES)
        _ffmpeg_native_collect_example_config_features(_ffmpeg_examples)
        list(APPEND _ffmpeg_enabled_config ${_ffmpeg_examples})
    endif()

    foreach(_ffmpeg_component IN LISTS FFMPEG_NATIVE_COMPONENTS)
        list(APPEND _ffmpeg_enabled_config "${_ffmpeg_component}")
    endforeach()

    if(FFMPEG_NATIVE_ENABLE_DEFAULT_COMPONENTS)
        _ffmpeg_native_append_default_components(_ffmpeg_enabled_components)
    endif()
    _ffmpeg_native_append_windows_indev_components(_ffmpeg_enabled_components)
    _ffmpeg_native_append_detected_device_components(_ffmpeg_enabled_components)
    _ffmpeg_native_append_hardware_smoke_components(_ffmpeg_enabled_components)

    _ffmpeg_native_append_user_features(FFMPEG_ENABLE_FEATURES)
    _ffmpeg_native_append_user_features(FFMPEG_ENABLE_EXTERNAL_LIBRARIES)

    _ffmpeg_native_append_hardware_components(_ffmpeg_enabled_components _ffmpeg_enabled_config)
    _ffmpeg_native_append_external_components(_ffmpeg_enabled_components _ffmpeg_enabled_config)
    _ffmpeg_native_append_network_components(_ffmpeg_enabled_components _ffmpeg_enabled_config)

    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_ENCODERS encoder)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_DECODERS decoder)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_HWACCELS hwaccel)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_MUXERS muxer)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_DEMUXERS demuxer)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_PARSERS parser)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_BSFS bsf)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_PROTOCOLS protocol)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_INDEVS indev)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_OUTDEVS outdev)
    _ffmpeg_native_append_user_components(_ffmpeg_enabled_components _ffmpeg_explicit_components FFMPEG_ENABLE_FILTERS filter)
    _ffmpeg_native_refresh_component_family_features(_ffmpeg_enabled_config _ffmpeg_enabled_components)

    set(_ffmpeg_disabled_features)
    _ffmpeg_native_expand_disabled_features(
        _ffmpeg_disabled_features
        "${FFMPEG_DISABLE_FEATURES};${FFMPEG_DISABLE_EXTERNAL_LIBRARIES}")
    set(_ffmpeg_disabled_components)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_ENCODERS encoder)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_DECODERS decoder)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_HWACCELS hwaccel)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_MUXERS muxer)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_DEMUXERS demuxer)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_PARSERS parser)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_BSFS bsf)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_PROTOCOLS protocol)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_INDEVS indev)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_OUTDEVS outdev)
    _ffmpeg_native_append_disabled_components(_ffmpeg_disabled_components FFMPEG_DISABLE_FILTERS filter)

    _ffmpeg_native_remove_disabled(_ffmpeg_enabled_config "${_ffmpeg_disabled_features}")
    _ffmpeg_native_remove_disabled(_ffmpeg_enabled_components "${_ffmpeg_disabled_components}")
    _ffmpeg_native_remove_disabled(_ffmpeg_enabled_have "${_ffmpeg_disabled_features}")
    _ffmpeg_native_remove_disabled(_ffmpeg_enabled_arch "${_ffmpeg_disabled_features}")
    _ffmpeg_native_remove_disabled(_ffmpeg_explicit_config "${_ffmpeg_disabled_features}")
    _ffmpeg_native_remove_disabled(_ffmpeg_explicit_components "${_ffmpeg_disabled_components}")
    _ffmpeg_native_remove_disabled(_ffmpeg_explicit_have "${_ffmpeg_disabled_features}")
    _ffmpeg_native_remove_disabled(_ffmpeg_explicit_arch "${_ffmpeg_disabled_features}")
    _ffmpeg_native_resolve_dependency_rules()
    _ffmpeg_native_refresh_component_family_features(_ffmpeg_enabled_config _ffmpeg_enabled_components)
    _ffmpeg_native_remove_disabled(_ffmpeg_enabled_config "${_ffmpeg_disabled_features}")
    _ffmpeg_native_remove_disabled(_ffmpeg_enabled_components "${_ffmpeg_disabled_components}")
    _ffmpeg_native_remove_disabled(_ffmpeg_enabled_have "${_ffmpeg_disabled_features}")
    _ffmpeg_native_remove_disabled(_ffmpeg_enabled_arch "${_ffmpeg_disabled_features}")
    _ffmpeg_native_validate_explicit_feature_deps()
    _ffmpeg_native_validate_license_gates()

    list(REMOVE_DUPLICATES _ffmpeg_enabled_config)
    list(REMOVE_DUPLICATES _ffmpeg_enabled_components)
    list(REMOVE_DUPLICATES _ffmpeg_enabled_have)
    list(REMOVE_DUPLICATES _ffmpeg_enabled_arch)
    list(SORT _ffmpeg_all_config)
    list(SORT _ffmpeg_all_components)
    list(SORT _ffmpeg_all_have)
    list(SORT _ffmpeg_all_arch)
    list(SORT _ffmpeg_enabled_config)
    list(SORT _ffmpeg_enabled_components)
    list(SORT _ffmpeg_enabled_have)
    list(SORT _ffmpeg_enabled_arch)

    set(_ffmpeg_license "LGPL version 2.1 or later")
    if(FFMPEG_ENABLE_NONFREE)
        set(_ffmpeg_license "nonfree and unredistributable")
    elseif(FFMPEG_ENABLE_GPL AND FFMPEG_ENABLE_VERSION3)
        set(_ffmpeg_license "GPL version 3 or later")
    elseif(FFMPEG_ENABLE_GPL)
        set(_ffmpeg_license "GPL version 2 or later")
    elseif(FFMPEG_ENABLE_VERSION3)
        set(_ffmpeg_license "LGPL version 3 or later")
    endif()

    set(_ffmpeg_qsv_backend "${FFMPEG_NATIVE_QSV_BACKEND}")
    if(_ffmpeg_qsv_backend STREQUAL "" OR _ffmpeg_qsv_backend STREQUAL "none")
        if(libvpl IN_LIST _ffmpeg_enabled_config)
            set(_ffmpeg_qsv_backend "oneVPL")
        elseif(libmfx IN_LIST _ffmpeg_enabled_config)
            set(_ffmpeg_qsv_backend "MediaSDK/libmfx")
        else()
            set(_ffmpeg_qsv_backend "none")
        endif()
    endif()
    set(FFMPEG_NATIVE_QSV_BACKEND "${_ffmpeg_qsv_backend}")

    if(FFMPEG_NATIVE_QSV_BACKEND STREQUAL "MediaSDK/libmfx" AND
       FFMPEG_NATIVE_QSV_BACKEND_NOTE STREQUAL "")
        _ffmpeg_native_cmake_target_available(_ffmpeg_vpl_candidate VPL VPL::dispatcher)
        if(NOT _ffmpeg_vpl_candidate)
            _ffmpeg_native_header_and_library_available(_ffmpeg_vpl_candidate "vpl/mfxvideo.h" vpl libvpl)
        endif()
        if(_ffmpeg_vpl_candidate)
            set(FFMPEG_NATIVE_QSV_BACKEND_NOTE "oneVPL was found but failed the link probe; using MediaSDK/libmfx.")
        endif()
    endif()

    set(FFMPEG_NATIVE_ALL_CONFIG_FEATURES "${_ffmpeg_all_config}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_ALL_COMPONENT_FEATURES "${_ffmpeg_all_components}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_ALL_HAVE_FEATURES "${_ffmpeg_all_have}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_ALL_ARCH_FEATURES "${_ffmpeg_all_arch}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_ENABLED_CONFIG_FEATURES "${_ffmpeg_enabled_config}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_ENABLED_COMPONENT_FEATURES "${_ffmpeg_enabled_components}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_ENABLED_HAVE_FEATURES "${_ffmpeg_enabled_have}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_ENABLED_ARCH_FEATURES "${_ffmpeg_enabled_arch}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_LICENSE "${_ffmpeg_license}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_QSV_BACKEND "${FFMPEG_NATIVE_QSV_BACKEND}" PARENT_SCOPE)
    set(FFMPEG_NATIVE_QSV_BACKEND_NOTE "${FFMPEG_NATIVE_QSV_BACKEND_NOTE}" PARENT_SCOPE)
endfunction()
