include_guard(GLOBAL)

set(_FFMPEG_KNOWN_COMPONENTS avutil swresample swscale avcodec avformat avfilter avdevice)
set(_FFMPEG_LINK_ORDER avdevice avfilter avformat avcodec swresample swscale avutil)

function(_ffmpeg_normalize_components _out)
    set(_ffmpeg_components ${ARGN})
    if(NOT _ffmpeg_components)
        set(_ffmpeg_components ${_FFMPEG_KNOWN_COMPONENTS})
    endif()

    set(_ffmpeg_result)
    foreach(_ffmpeg_component IN LISTS _ffmpeg_components)
        if(_ffmpeg_component STREQUAL "")
            continue()
        endif()
        if(_ffmpeg_component STREQUAL "FFmpeg" OR _ffmpeg_component STREQUAL "all")
            list(APPEND _ffmpeg_result ${_FFMPEG_KNOWN_COMPONENTS})
            continue()
        endif()
        string(REGEX REPLACE "^lib" "" _ffmpeg_component "${_ffmpeg_component}")
        list(FIND _FFMPEG_KNOWN_COMPONENTS "${_ffmpeg_component}" _ffmpeg_index)
        if(_ffmpeg_index EQUAL -1)
            message(FATAL_ERROR "Unknown FFmpeg component '${_ffmpeg_component}'. Known components: ${_FFMPEG_KNOWN_COMPONENTS}")
        endif()
        list(APPEND _ffmpeg_result "${_ffmpeg_component}")
    endforeach()

    list(REMOVE_DUPLICATES _ffmpeg_result)
    set(${_out} "${_ffmpeg_result}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_pkg_config_path _out _root)
    if(WIN32)
        set(_ffmpeg_path_sep ";")
    else()
        set(_ffmpeg_path_sep ":")
    endif()

    set(_ffmpeg_prefixes)
    foreach(_ffmpeg_prefix IN ITEMS "${_root}" "${FFmpeg_ROOT}" "$ENV{FFmpeg_ROOT}" "$ENV{FFMPEG_ROOT}")
        if(NOT _ffmpeg_prefix STREQUAL "")
            list(APPEND _ffmpeg_prefixes "${_ffmpeg_prefix}")
        endif()
    endforeach()
    foreach(_ffmpeg_prefix IN LISTS CMAKE_PREFIX_PATH)
        if(NOT _ffmpeg_prefix STREQUAL "")
            list(APPEND _ffmpeg_prefixes "${_ffmpeg_prefix}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_prefixes)

    set(_ffmpeg_paths)
    foreach(_ffmpeg_prefix IN LISTS _ffmpeg_prefixes)
        foreach(_ffmpeg_suffix IN ITEMS lib/pkgconfig lib64/pkgconfig share/pkgconfig)
            if(IS_DIRECTORY "${_ffmpeg_prefix}/${_ffmpeg_suffix}")
                list(APPEND _ffmpeg_paths "${_ffmpeg_prefix}/${_ffmpeg_suffix}")
            endif()
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_paths)

    if(_ffmpeg_paths)
        string(JOIN "${_ffmpeg_path_sep}" _ffmpeg_path ${_ffmpeg_paths})
    else()
        set(_ffmpeg_path "")
    endif()

    if(DEFINED ENV{PKG_CONFIG_PATH} AND NOT "$ENV{PKG_CONFIG_PATH}" STREQUAL "")
        if(_ffmpeg_path)
            string(APPEND _ffmpeg_path "${_ffmpeg_path_sep}$ENV{PKG_CONFIG_PATH}")
        else()
            set(_ffmpeg_path "$ENV{PKG_CONFIG_PATH}")
        endif()
    endif()

    set(${_out} "${_ffmpeg_path}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_pkg_config_command _out _pc_path)
    if(NOT PKG_CONFIG_EXECUTABLE)
        find_program(PKG_CONFIG_EXECUTABLE NAMES pkg-config)
    endif()
    if(NOT PKG_CONFIG_EXECUTABLE)
        set(${_out} "" PARENT_SCOPE)
        return()
    endif()

    if(_pc_path)
        set(${_out} "${CMAKE_COMMAND}" -E env "PKG_CONFIG_PATH=${_pc_path}" "${PKG_CONFIG_EXECUTABLE}" PARENT_SCOPE)
    else()
        set(${_out} "${PKG_CONFIG_EXECUTABLE}" PARENT_SCOPE)
    endif()
endfunction()

function(_ffmpeg_pkg_config_output _out _result _pc_path)
    _ffmpeg_pkg_config_command(_ffmpeg_pkg_config "${_pc_path}")
    if(NOT _ffmpeg_pkg_config)
        set(${_out} "" PARENT_SCOPE)
        set(${_result} 127 PARENT_SCOPE)
        return()
    endif()

    execute_process(
        COMMAND ${_ffmpeg_pkg_config} ${ARGN}
        RESULT_VARIABLE _ffmpeg_result
        OUTPUT_VARIABLE _ffmpeg_output
        ERROR_VARIABLE _ffmpeg_error
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_STRIP_TRAILING_WHITESPACE)
    if(NOT _ffmpeg_result EQUAL 0 AND _ffmpeg_error)
        set(FFmpeg_NOT_FOUND_MESSAGE "${_ffmpeg_error}" PARENT_SCOPE)
    endif()
    set(${_out} "${_ffmpeg_output}" PARENT_SCOPE)
    set(${_result} "${_ffmpeg_result}" PARENT_SCOPE)
endfunction()

function(_ffmpeg_resolve_static_library _out _name)
    set(_ffmpeg_dirs ${ARGN})
    if(_name MATCHES "^:(.+)$")
        set(_ffmpeg_candidates "${CMAKE_MATCH_1}")
    elseif(WIN32)
        set(_ffmpeg_candidates "${_name}.lib" "lib${_name}.a" "${_name}.a")
    else()
        set(_ffmpeg_candidates "lib${_name}.a")
    endif()

    foreach(_ffmpeg_dir IN LISTS _ffmpeg_dirs)
        foreach(_ffmpeg_candidate IN LISTS _ffmpeg_candidates)
            if(EXISTS "${_ffmpeg_dir}/${_ffmpeg_candidate}")
                set(${_out} "${_ffmpeg_dir}/${_ffmpeg_candidate}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endforeach()

    set(${_out} "" PARENT_SCOPE)
endfunction()

function(_ffmpeg_apply_pkg_config_target _target _pc_path _static)
    set(_ffmpeg_modules ${ARGN})
    set(_ffmpeg_static_arg)
    if(_static)
        list(APPEND _ffmpeg_static_arg --static)
    endif()

    _ffmpeg_pkg_config_output(_ffmpeg_cflags _ffmpeg_cflags_result "${_pc_path}" ${_ffmpeg_static_arg} --cflags ${_ffmpeg_modules})
    if(NOT _ffmpeg_cflags_result EQUAL 0)
        return()
    endif()
    separate_arguments(_ffmpeg_cflag_tokens NATIVE_COMMAND "${_ffmpeg_cflags}")

    set(_ffmpeg_include_dirs)
    set(_ffmpeg_compile_defs)
    set(_ffmpeg_compile_opts)
    foreach(_ffmpeg_token IN LISTS _ffmpeg_cflag_tokens)
        if(_ffmpeg_token MATCHES "^-I(.+)$")
            list(APPEND _ffmpeg_include_dirs "${CMAKE_MATCH_1}")
        elseif(_ffmpeg_token MATCHES "^-D(.+)$")
            list(APPEND _ffmpeg_compile_defs "${CMAKE_MATCH_1}")
        else()
            list(APPEND _ffmpeg_compile_opts "${_ffmpeg_token}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_include_dirs)
    list(REMOVE_DUPLICATES _ffmpeg_compile_defs)
    list(REMOVE_DUPLICATES _ffmpeg_compile_opts)

    _ffmpeg_pkg_config_output(_ffmpeg_libs _ffmpeg_libs_result "${_pc_path}" ${_ffmpeg_static_arg} --libs ${_ffmpeg_modules})
    if(NOT _ffmpeg_libs_result EQUAL 0)
        return()
    endif()
    separate_arguments(_ffmpeg_link_tokens NATIVE_COMMAND "${_ffmpeg_libs}")

    set(_ffmpeg_link_dirs)
    set(_ffmpeg_link_items)
    foreach(_ffmpeg_token IN LISTS _ffmpeg_link_tokens)
        if(_ffmpeg_token MATCHES "^-L(.+)$")
            list(APPEND _ffmpeg_link_dirs "${CMAKE_MATCH_1}")
        else()
            list(APPEND _ffmpeg_link_items "${_ffmpeg_token}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _ffmpeg_link_dirs)

    if(_static)
        foreach(_ffmpeg_module IN LISTS _ffmpeg_modules)
            _ffmpeg_pkg_config_output(_ffmpeg_module_libdir _ffmpeg_module_libdir_result "${_pc_path}" --variable=libdir "${_ffmpeg_module}")
            if(_ffmpeg_module_libdir_result EQUAL 0 AND NOT _ffmpeg_module_libdir STREQUAL "")
                list(APPEND _ffmpeg_link_dirs "${_ffmpeg_module_libdir}")
            endif()
        endforeach()
        list(REMOVE_DUPLICATES _ffmpeg_link_dirs)

        set(_ffmpeg_static_link_items)
        foreach(_ffmpeg_token IN LISTS _ffmpeg_link_items)
            if(_ffmpeg_token MATCHES "^-l(.+)$")
                _ffmpeg_resolve_static_library(_ffmpeg_static_library "${CMAKE_MATCH_1}" ${_ffmpeg_link_dirs})
                if(_ffmpeg_static_library)
                    list(APPEND _ffmpeg_static_link_items "${_ffmpeg_static_library}")
                else()
                    list(APPEND _ffmpeg_static_link_items "${_ffmpeg_token}")
                endif()
            else()
                list(APPEND _ffmpeg_static_link_items "${_ffmpeg_token}")
            endif()
        endforeach()
        set(_ffmpeg_link_items ${_ffmpeg_static_link_items})
    endif()

    set_property(TARGET "${_target}" PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${_ffmpeg_include_dirs}")
    set_property(TARGET "${_target}" PROPERTY INTERFACE_COMPILE_DEFINITIONS "${_ffmpeg_compile_defs}")
    set_property(TARGET "${_target}" PROPERTY INTERFACE_COMPILE_OPTIONS "${_ffmpeg_compile_opts}")
    set_property(TARGET "${_target}" PROPERTY INTERFACE_LINK_DIRECTORIES "${_ffmpeg_link_dirs}")
    set_property(TARGET "${_target}" PROPERTY INTERFACE_LINK_LIBRARIES "${_ffmpeg_link_items}")
endfunction()

function(ffmpeg_pkg_config_import_targets)
    set(_ffmpeg_options GLOBAL REQUIRED STATIC)
    set(_ffmpeg_one_value NAMESPACE ROOT)
    set(_ffmpeg_multi_value COMPONENTS)
    cmake_parse_arguments(FFMPEG_PKG "${_ffmpeg_options}" "${_ffmpeg_one_value}" "${_ffmpeg_multi_value}" ${ARGN})

    if(NOT FFMPEG_PKG_NAMESPACE)
        set(FFMPEG_PKG_NAMESPACE FFmpeg::)
    endif()

    if(NOT FFMPEG_PKG_STATIC AND (FFmpeg_USE_STATIC_LIBS OR FFMPEG_USE_STATIC_LIBS))
        set(FFMPEG_PKG_STATIC TRUE)
    endif()

    _ffmpeg_normalize_components(_ffmpeg_components ${FFMPEG_PKG_COMPONENTS})
    _ffmpeg_pkg_config_path(_ffmpeg_pc_path "${FFMPEG_PKG_ROOT}")
    _ffmpeg_pkg_config_command(_ffmpeg_pkg_config "${_ffmpeg_pc_path}")
    if(NOT _ffmpeg_pkg_config)
        set(FFmpeg_FOUND FALSE PARENT_SCOPE)
        set(FFmpeg_NOT_FOUND_MESSAGE "pkg-config executable was not found" PARENT_SCOPE)
        if(FFMPEG_PKG_REQUIRED)
            message(FATAL_ERROR "pkg-config executable was not found")
        endif()
        return()
    endif()

    set(_ffmpeg_found_components)
    set(_ffmpeg_missing_components)
    set(_ffmpeg_all_include_dirs)
    set(_ffmpeg_all_targets)
    set(_ffmpeg_aggregate_modules)

    foreach(_ffmpeg_component IN LISTS _ffmpeg_components)
        set(_ffmpeg_module "lib${_ffmpeg_component}")
        _ffmpeg_pkg_config_output(_ffmpeg_unused _ffmpeg_exists "${_ffmpeg_pc_path}" --exists "${_ffmpeg_module}")
        if(NOT _ffmpeg_exists EQUAL 0)
            list(APPEND _ffmpeg_missing_components "${_ffmpeg_component}")
            set(FFmpeg_${_ffmpeg_component}_FOUND FALSE PARENT_SCOPE)
            continue()
        endif()

        _ffmpeg_pkg_config_output(_ffmpeg_version _ffmpeg_version_result "${_ffmpeg_pc_path}" --modversion "${_ffmpeg_module}")

        set(_ffmpeg_target "${FFMPEG_PKG_NAMESPACE}${_ffmpeg_component}")
        if(NOT TARGET "${_ffmpeg_target}")
            if(FFMPEG_PKG_GLOBAL)
                add_library("${_ffmpeg_target}" INTERFACE IMPORTED GLOBAL)
            else()
                add_library("${_ffmpeg_target}" INTERFACE IMPORTED)
            endif()
        endif()
        _ffmpeg_apply_pkg_config_target("${_ffmpeg_target}" "${_ffmpeg_pc_path}" "${FFMPEG_PKG_STATIC}" "${_ffmpeg_module}")

        get_target_property(_ffmpeg_target_includes "${_ffmpeg_target}" INTERFACE_INCLUDE_DIRECTORIES)
        if(_ffmpeg_target_includes)
            list(APPEND _ffmpeg_all_include_dirs ${_ffmpeg_target_includes})
        endif()

        set(FFmpeg_${_ffmpeg_component}_FOUND TRUE PARENT_SCOPE)
        if(_ffmpeg_version_result EQUAL 0)
            set(FFmpeg_${_ffmpeg_component}_VERSION "${_ffmpeg_version}" PARENT_SCOPE)
            if(NOT DEFINED _ffmpeg_first_version)
                set(_ffmpeg_first_version "${_ffmpeg_version}")
            endif()
        endif()

        list(APPEND _ffmpeg_found_components "${_ffmpeg_component}")
        list(APPEND _ffmpeg_all_targets "${_ffmpeg_target}")
    endforeach()

    foreach(_ffmpeg_component IN LISTS _FFMPEG_LINK_ORDER)
        list(FIND _ffmpeg_found_components "${_ffmpeg_component}" _ffmpeg_component_index)
        if(NOT _ffmpeg_component_index EQUAL -1)
            list(APPEND _ffmpeg_aggregate_modules "lib${_ffmpeg_component}")
        endif()
    endforeach()

    set(_ffmpeg_aggregate_target "${FFMPEG_PKG_NAMESPACE}FFmpeg")
    if(_ffmpeg_aggregate_modules AND NOT TARGET "${_ffmpeg_aggregate_target}")
        if(FFMPEG_PKG_GLOBAL)
            add_library("${_ffmpeg_aggregate_target}" INTERFACE IMPORTED GLOBAL)
        else()
            add_library("${_ffmpeg_aggregate_target}" INTERFACE IMPORTED)
        endif()
    endif()
    if(_ffmpeg_aggregate_modules)
        _ffmpeg_apply_pkg_config_target("${_ffmpeg_aggregate_target}" "${_ffmpeg_pc_path}" "${FFMPEG_PKG_STATIC}" ${_ffmpeg_aggregate_modules})
        list(APPEND _ffmpeg_all_targets "${_ffmpeg_aggregate_target}")
    endif()

    list(REMOVE_DUPLICATES _ffmpeg_all_include_dirs)

    set(FFmpeg_FOUND TRUE PARENT_SCOPE)
    set(FFmpeg_COMPONENTS "${_ffmpeg_found_components}" PARENT_SCOPE)
    set(FFmpeg_TARGETS "${_ffmpeg_all_targets}" PARENT_SCOPE)
    set(FFmpeg_LIBRARIES "${_ffmpeg_all_targets}" PARENT_SCOPE)
    set(FFmpeg_INCLUDE_DIRS "${_ffmpeg_all_include_dirs}" PARENT_SCOPE)
    if(DEFINED _ffmpeg_first_version)
        set(FFmpeg_VERSION "${_ffmpeg_first_version}" PARENT_SCOPE)
    endif()

    if(_ffmpeg_missing_components)
        string(REPLACE ";" ", " _ffmpeg_missing_text "${_ffmpeg_missing_components}")
        set(FFmpeg_NOT_FOUND_MESSAGE "Missing FFmpeg pkg-config modules for components: ${_ffmpeg_missing_text}" PARENT_SCOPE)
        if(FFMPEG_PKG_REQUIRED)
            message(FATAL_ERROR "Missing FFmpeg pkg-config modules for components: ${_ffmpeg_missing_text}")
        endif()
    endif()
endfunction()
